### ISSUE TITLE
Integration tests seem flaky

### ISSUE THREAD

**Issue by sixolet** [knative/client#100]
In a way that doesn't seem to relate to any client code

**Comment by maximilien** [comment]
Seems like there was an issue with getting Istio from servers. Seems fixed now.

**Comment by rhuss** [comment]
We have now a new kind of Flake for the E2E when using the new go based workflow. Looks like a timing issue:


```
Failed to successfully execute 'kn service update hello --env TARGET=kn -n kne2etests': Execution error: stderr: 'Operation cannot be fulfilled on services.serving.knative.dev "hello": the object has been modified; please apply your changes to the latest version and try again
' error: 'exit status 1'FAIL	github.com/knative/client/test/e2e	1.792s
```

E.g. in https://github.com/knative/client/pull/198

**Comment by rhuss** [comment]
Sorry, overlooked #211 . Let's continue over there ....

**Comment by rhuss** [comment]
I think it is fixed now. Let's close this issue and reopen or create a new one, if we see another flake.
