### ISSUE TITLE
--min-scale/max-scale are broken

### ISSUE THREAD

**Issue by duglin** [knative/client#1008]
the latest `kn` seems to support --min-scale and --max-scale, at least it doesn't complain when I try to use them. But nothing is set in the ksvc - so they have no effect. If we're not going to generate an error (due to them not being valid flag) then we should still support them on the backend properly.

I suspect this might catch a lot of people - took me a while to figure out why my services kept scaling down to zero despite specifying --min-scale=1  :-) 

IMO we should back-port the fix for this

**Comment by navidshaikh** [comment]
Thanks Doug! This should've been caught in e2e, which alerts missing e2e. The fix should contain e2e for visible + hidden variant of these flags.
