### ISSUE TITLE
Update to 1.18 client-go library

### ISSUE THREAD

**Issue by rhuss** [knative/client#1009]
Update the dependency on client-go to version 1.18 which introduces some backward incompatible changes. See also https://knative.slack.com/archives/C01AK3YNHPW for the knative coordinated effort to make the switch.

**Comment by MIBc** [comment]
Should we update only client-go or all k8s library ?

**Comment by rhuss** [comment]
We should align with the other knative projects, I think they have updated everything to k8s 1.18

**Comment by mattmoor** [comment]
Generally we move all K8s libs in sync.

**Comment by MIBc** [comment]
I think this issue has been solved by https://github.com/knative/client/pull/1025. We can close it.

**Comment by rhuss** [comment]
Correct
