### ISSUE TITLE
Sample API Usage page is a bit confusing

### ISSUE THREAD

**Issue by vaikas** [knative/client#101]
/kind doc

## Expected Behavior
Sample API documentation that works

## Actual Behavior
Sample API documentation page here:
https://github.com/knative/serving/blob/master/docs/spec/normative_examples.md#4-deploy-a-revision-from-source

talks about knative tool that doesn't exist and users find it confusing. It would seem clearer to update to use a kubectl example files rather than the tool itself.

## Steps to Reproduce the Problem

1. Bring up this page: https://github.com/knative/serving/blob/master/docs/spec/normative_examples.md#4-deploy-a-revision-from-source
2. Though it mentions that these are samples for CLI it's a bit odd to talk about Sample API Usage and then demo it with a CLI tool that doesn't exist.
3.

**Comment by maximilien** [comment]
I am also happy to submit a PR to the serving API docs to get it up to date with `kn` --- at least everywhere we can so far. Let me know.

**Comment by rhuss** [comment]
As  https://github.com/knative/serving/blob/master/docs/spec/normative_examples.md has been replaced by a pointer to the knative client githup repo, I think we can close this issue. The examples that have been used included in this document will be moved more less over to the forthcoming user manual (#650)

btw, I think  https://github.com/knative/serving/blob/master/docs/spec/normative_examples.md could be completely removed as it looks like that it is not referenced from anywhere
