### ISSUE TITLE
Add support for volume sub-paths

### ISSUE THREAD

**Issue by theckang** [knative/client#1015]
### Feature request

Add the ability in `kn service create` and `kn service update` to specify a sub-path, in addition to the volume's mount path.

### Use case

I have AWS config and credentials stored in `.aws/config` and `.aws/credentials` respectively.  I generate a `configmap` for the config and a `secret` for the credentials.  In order to mount the config and secret to the same path in a service template, I need to specify the volume's sub-path.  Here's an example: https://github.com/RedHatGov/serverless-workshop-code/blob/main/model/prediction/prediction-service.yaml

In this example, I could switch to ENV variables but it illustrates use cases where someone may want to inject multiple config maps or secrets into the same mount path.

```

```

**Comment by rhuss** [comment]
Definitely a good idea. We have to think about though, how we can seamlessly and backwards-compatibly add this to the volume specification which already a bit complex and uses our own encoding.

Any suggestion on how to add the subpath to the `--mount` option of `kn service create` would be quite helpful to kick off this feature.

**Comment by dsimansk** [comment]
This's done by the PR #1655 and included in`1.4` release.

/close
