### ISSUE TITLE
[release-0.18] Early kn release v0.18.0

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#1035]
See https://github.com/knative/client/releases/tag/v0.18.0 thats a week ahead of the schedule.

I see branch release-0.18.0 pushed today triggering this build, cc: @ZhiminXiang 

I think we should delete this release and the respective branch for now.

**Comment by rhuss** [comment]
@ZhiminXiang please note that the client still releases 1 week after serving/eventing to get the dependencies (on serving and eventing) right. We plan to reduce that, but not for now.

**Comment by ZhiminXiang** [comment]
I have manually delete release-0.18 branch as well as v0.18.0 tag. It should be good now.
