### ISSUE TITLE
Add integration tests to match the Basic workflow

### ISSUE THREAD

**Issue by maximilien** [knative/client#104]
This should be structured as start of e2e tests and for the first cut cover the proposed [Basic workflow](https://github.com/knative/client/pull/99). So includes:

1. `create service`
2. `service get`, `service describe` newly created service
3. `service list` that service in in the list
4. `delete service` and verify deleted

Subsequence e2e tests can follow additional advanced workflows with more commands, e.g., `service update`, `service replace`

**Comment by maximilien** [comment]
Unless I hear otherwise, I will add this test and verify it on IKS to also have another additional platform for testing.

**Comment by navidshaikh** [comment]
@maximilien : I added few basic workflow commands in script, if you plan to address this in different way, please let me know.

**Comment by maximilien** [comment]
Nice @navidshaikh. Thanks! I'll try it on IKS and submit any changes as needed. Cheers 🍻

**Comment by maximilien** [comment]
Also, while this is great to start with. I also wanted the tests to be written in Golang. I'll create small example and tee it up for next call so we can discuss.

However, what you have is fine for now. Especially since it follows what @sixolet had in the first e2e.

Cheers.

**Comment by maximilien** [comment]
FYI: Once #112 is merged I will close this. I opened #114 for the Golang version discussion above.
