### ISSUE TITLE
Support more aliases for really long options

### ISSUE THREAD

**Issue by duglin** [knative/client#1042]
Now that our validating webhook will flag revision annotation that appear on the service, it'll force people to type `--annotation-revision xxx=yyy` and that's a lot typing. Can we look into supporting some alias? For example:
- `--ar` for `--annotation-revision`
- `--as` for `--annotation-service`
- `--lr` for `--label-revision`
- `--ls` for `--label-service`

**Comment by navidshaikh** [comment]
How about


`--a-rev` for `--annotation-revision`
`--a-ksvc` for `--annotation-service`
`--l-rev` for `--label-revision`
`--l-ksvc` for `--label-service`

?

this way, we keep the parity with other aliases and maintain the flag format?

**Comment by duglin** [comment]
I still kind of prefer the two letter version (one letter per word), but what you suggested is still better than what we have today :-)

**Comment by duglin** [comment]
Per the call today, I think the list of auto-scaling annotations can be found here:
https://github.com/knative/serving/blob/master/pkg/apis/autoscaling/register.go
and serving:
https://github.com/knative/serving/blob/master/pkg/apis/serving/register.go

Not all of these are really user settable tho

**Comment by arghya88** [comment]
@navidshaikh do we have a consensus on this to move forward?

**Comment by navidshaikh** [comment]
flag alias with more than single letter / double dash seems odd to me
@rhuss wdyt ?

**Comment by rhuss** [comment]
We should not introduce shortcuts with double-dash options. This is totally unexpected to use a long option with an acronym as a name. That is reserved for single-letter options. Of course, we can think about using the single letter namespace for certain abbreviation but this should be carefully considered (as removing them afterwards is not easy).

So -1 from me to use shortcuts/aliases with `--` (also `-a` for annotation and `--ar` for revision annotations is not consistent at all and totally not memorizable). We should level up on our bash completion game to make that less to type for users (`--a<TAB>-r<TAB>` which is just 3 keystrokes more then the initial suggestion)

**Comment by rhuss** [comment]
How should we continue with the feature request ? I'm still -1 for adding two letter long options as they (a) would pollute the help message with extra entries, (b) can be confused with single letter options that start with a single dash and that are aliases to long options and ( c) are not a common thing for CLI tools (do we know any other CLI that would do this ?)

My suggestion would be to level up our auto-completion game as mentioned above. I.e. focussing on allowing context-sensitive completion of entity names and also on long options. I opened corresponding feature requests for those (#1374 and #1373)

If we could agree on this direction I would close this issue. @duglin @dsimansk @navidshaikh would this be an acceptable  solution for this UX issue with long option names ?

**Comment by duglin** [comment]
Keep in mind that not all uses of the client are interactive. Often it's being used in bash scripts, so that means lots of typing (or copy-n-pasting) and really long cmd lines. Personally, I don't care about -- vs -, I just want to avoid flags that are 15+ characters long
