### ISSUE TITLE
KnServingClient::WaitForService continues to wait if app is deleted

### ISSUE THREAD

**Issue by ericmillin** [knative/client#1047]
### Bug report

If you delete an app while you are waiting for it start, the create wait will continue until it times out

### Expected behavior
Wait ends

### Steps to reproduce the problem

In terminal A:
```
kn service create testit --image docker.io/ibmcom/helloworld
```
In terminal B:
```
kn service delete testit
```

### kn version

```
Version:      v20200821-4ea31c44
Build Date:   2020-08-21 10:36:33
Git Revision: 4ea31c44
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.17.0)
* Eventing
  - sources.knative.dev/v1alpha2 (knative-eventing v0.17.0)
  - eventing.knative.dev/v1beta1 (knative-eventing v0.17.0)
```

**Comment by rhuss** [comment]
Thanks for the report ! (and sorry for that very delayed response).

That definitely looks like an bug and we should add in the general wait loop the case when an `DELETE` event occurs, that the wait should abort then, too.

/label good-first-issue

**Comment by dsimansk** [comment]
@rhuss it sounds similar to the race condition issues, that was fixed a few weeks ago. https://github.com/knative/client/issues/1109
