### ISSUE TITLE
GitHub Action for kn

### ISSUE THREAD

**Issue by danielhelfand** [knative/client#1066]
### Feature request

It would be helpful for developers using GitHub Actions to have an easy way to use `kn`. Wondering if there has been any discussion around supporting an official GitHub Action and making it available through the [GitHub Actions Marketplace](https://github.com/marketplace).

Creating a GitHub Action docs: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions

### Use case

For developers working with GitHub Actions for CI/CD, having an action that allows users to specify a specific version of `kn` to use and include in a build would help with automation around working with Knative.

### UI Example

N/A

**Comment by rhuss** [comment]
I wonder whether we need a dedicated action or if our container image for kn that could be used as an action would be good enough ? (saying that with being a github action noob )

**Comment by danielhelfand** [comment]
I think the challenge with GitHub Actions right now is that there isn't the perfect pattern for including CLIs as part of a build. In a lot of cases, actions have been developed to install CLIs on the host, which is not the most ideal pattern. 

And the challenge with using an image (i.e. `uses: docker://gcr.io/knative-releases/knative.dev/client/cmd/kn:latest`) is properly utilizing things on the host (e.g. resource definitions and a kubeconfig) in an easy way. So if there is a way to abstract this further, I think it would make sense. But what I can do to start with this is look into the nuances of using the image in actions to see if it's worth making something.

**Comment by navidshaikh** [comment]
cc @kameshsampath

**Comment by kameshsampath** [comment]
thanks @navidshaikh , I have a early version of the action https://github.com/kameshsampath/kn-service-action and an example using it https://github.com/kameshsampath/kn-service-action-example. Right now tested only on OpenShift

**Comment by kameshsampath** [comment]
@danielhelfand ^^

**Comment by rhuss** [comment]
@kameshsampath thanks a lot @kameshsampath ! Eventually we could move to a `knative-sandbox/kn-github-atcion` for wider visibility. We can discuss the implementation details over there at kamesh' repo, before moving on. E.g. when it comes to authentication and other configuration requirements.

**Comment by mattwelke** [comment]
I recently added a step in a GitHub Actions workflow to install kn:

```yaml
- name: Setup kn
  run: |-
    echo "Downloading kn $KN_VERSION to $KN_INSTALL_PATH..."
    sudo wget --quiet -O $KN_INSTALL_PATH "https://github.com/knative/client/releases/download/$KN_VERSION/kn-linux-amd64"
    sudo chmod +x $KN_INSTALL_PATH
    echo "Installed kn $KN_VERSION"
```

GitHub Actions has been an area of interest for me lately, and I wanted to try making an action of my own, so I thought this would be a fun project to do. I planned to start it this weekend, but decided to search and found this issue first.

> the challenge with using an image (i.e. uses: docker://gcr.io/knative-releases/knative.dev/client/cmd/kn:latest) is properly utilizing things on the host (e.g. resource definitions and a kubeconfig) in an easy way

I think this is why the pattern so far is to have JavaScript actions that mutate the host. That way, CLIs can be installed and used by steps further down in the workflow's job. Docker actions run in a separate container (which has read only access to the host's file system), so they can't be used to install CLIs on the host. Docker actions can use CLI tools though, as long as they accept everything they need in the parameters of the action for the self-contained CLI tool to do what it needs to do.

**Comment by mattwelke** [comment]
I did some more reading on JavaScript vs. Docker actions and I read that Docker actions can actually mutate the host file system too. I was wrong about that before.

I took a stab at creating `setup-kn` as my first real action: https://github.com/mattwelke/github-action-setup-kn

I made it as a JavaScript action, taking inspiration from the setup-gcloud action from Google. It doesn't have a build pipeline though right now. I just put it in `.github/actions` in the repo for testing. It lets people specify version, and defaults to v0.19.1 right now (I'd add some smart semver functionality later to make it grab the latest version or latest major version a user specifies).

![image](https://user-images.githubusercontent.com/7719209/102158363-4e2f6700-3e4f-11eb-9b2a-073ddbe85989.png)

It skips the install if it's already installed and errors out if users specify something invalid:

![image](https://user-images.githubusercontent.com/7719209/102158294-25a76d00-3e4f-11eb-9cc2-4adf5d503e8f.png)

@kameshsampath I'm interested what your thoughts are on it. I do like your action for deploying services because it is self contained.

**Comment by kameshsampath** [comment]
@mattwelke  - the biggest adv I see with Dockerfile based approach is that you dont need to be JS expert :)  and enables people w/o JS knowledge to collaborate easily. But I do feel the native JS actions do have some advantages but never tried

**Comment by mattwelke** [comment]
After talking on Slack, we decided it would be worth looking more into Docker actions for all actions, including setting up kn. I will look more into them before continuing with this and collaborating.

Another goal is to use the existing kn Docker image as is, as the Docker action, or with the refactorong needed to use it both as it's used right now and as a Docker action.

**Comment by rhuss** [comment]
Is there still interest in this feature, or can we close this issue ? (asking because it went stale)

**Comment by kameshsampath** [comment]
I think we can close it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Divyansh42** [comment]
@danielhelfand we have created an action https://github.com/redhat-actions/kn-service-manager to manage knative services, but knative should be installed in your kubernetes cluster to work with this action. May be this action can partially fulfill your requirement.
We would love to see your views on this and do let us know if you want some improvements/features in this, we can discuss that further.

P.S. Initial work is done by @kameshsampath (he has already mentioned that repos earlier in comments) we have tried to add some other features to make it more usable.

**Comment by Divyansh42** [comment]
@mattwelke Based on your comment:

> I made it as a JavaScript action, taking inspiration from the setup-gcloud action from Google. It doesn't have a build pipeline though right now. I just put it in .github/actions in the repo for testing. It lets people specify version, and defaults to v0.19.1 right now (I'd add some smart semver functionality later to make it grab the latest version or latest major version a user specifies).

[OpenShift Tools Installer](https://github.com/redhat-actions/openshift-tools-installer) action can install `kn` and it has semver support too and also caches the binary for faster installation in future jobs. You can give this a try!

**Comment by rhuss** [comment]
@kameshsampath @mattwelke If you don't mind I'm closing this issue as there is a good, fully-featured implementation provided by the OpenShift Tools installer (which despite the name also includes vanilla non-openshift tools like kubectl or kn) that is actively maintained.

For the near future, I don't think we have the people to work on our own GitHub action. It's not so much about the initial implementation, more about the constant maintenance effort. This might change when we offer Kn distributions that come included with various plugins.

Feel free to reopen the issue if I'm wrong.

**Comment by rhuss** [comment]
One caveat though is, that the [OpenShift Tools Installer](https://github.com/redhat-actions/openshift-tools-installer) references the Red Hat productized version of kn (that include some plugins and is two minor versions behind the upstream version). @Divyansh42 , I guess there are no plans to add the possibility to download upstream binaries ?

**Comment by Divyansh42** [comment]
@rhuss It can also install upstream binaries that are present here https://github.com/knative/client/releases
You can use it in your workflow as shown in [example workflow](https://github.com/redhat-actions/openshift-tools-installer/blob/main/.github/workflows/example_github.yml#L34).

**Comment by rhuss** [comment]
> @rhuss It can also install upstream binaries that are present here https://github.com/knative/client/releases

Cool, thanks ! That's awesome and really helpful.
