### ISSUE TITLE
docs/DEVELOPMENT.md points to old contributing docs

### ISSUE THREAD

**Issue by abrennan89** [knative/client#1071]
### Bug report

https://github.com/knative/client/blob/master/docs/DEVELOPMENT.md#development points to https://knative.dev/contributing/ - which looks weird and outdated.

### Expected behavior

I think it should actually point to here: https://knative.dev/community/contributing/

Also, serving, eventing and docs are listed here https://knative.dev/community/contributing/#contributors but CLI is not.
Should it be added?

/kind doc

**Comment by rhuss** [comment]
@abrennan89 sorry for the late response, just going through my backlog of open issues.

I agree that the contributing link needs to be updated, but I also think that  https://knative.dev/contributing/ should be removed, too. Let me open issue over there at docs, too.

> Also, serving, eventing and docs are listed here https://knative.dev/community/contributing/#contributors but CLI is not.
> Should it be added?

Yes, definitely ! Good find. I will address this with a PR, too.
