### ISSUE TITLE
Reuse conflict retry loop from client-go/util/retry

### ISSUE THREAD

**Issue by rhuss** [knative/client#1102]
Instead of our homegrown algorithm for retrying updates in case of a conflict, we should reuse https://github.com/kubernetes/client-go/blob/1eb2027cd51eefaca0f851d5a2c90f8dd9b2a71d/util/retry/util.go#L68-L75 from the kubernetes client lib.

The goal of this refactoring task is to identify the spots where we are doing retries and switch over to this utility method, much like the `kn service import` pr does.

**Comment by rhuss** [comment]
/remove-lifecycle stale

I think this is still a good idea to move this feature to a shared place

**Comment by rhuss** [comment]
/remove-lifecycle stale
/good-first-issue

Still a valid improvement to reduce our code footprint. Also, I think this would be a good first issue.

**Comment by dsimansk** [comment]
On top of the original proposal. There might be a good enhancement to use the conflict retry loop in other update operations, e.g. sources, triggers, etc. to avoid cases like we see in E2E tests.

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1419/pull-knative-client-integration-tests/1425048794432540672#1:build-log.txt%3A839
