### ISSUE TITLE
Unkown subcommand doesn't return any errors

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#111]
For example, we've renamed `kn service list` -> `kn service get`, however if ran `list`, it just shows the `help` text for `service` group and doesn't return with exit status 1 or prints that `list` is unkown command.
```
➜ kn service list
Service command group

Usage:
  kn service [command]

Available Commands:
  create      Create a service.
  delete      Delete a service.
  describe    Describe available services.
  get         Get available services.
  update      Update a service.

Flags:
  -h, --help   help for service

Global Flags:
      --config string       config file (default is $HOME/.kn.yaml)
      --kubeconfig string   kubectl config file (default is $HOME/.kube/config)

Use "kn service [command] --help" for more information about a command.
➜ echo $?
0
```

This seems to be a known inconsistency with only sub-commands and not with commands. 

However, we've a false positive https://github.com/knative/client/blob/master/test/e2e-tests.sh#L50 .

**Comment by navidshaikh** [comment]
Issue at https://github.com/spf13/cobra/issues/706

**Comment by maximilien** [comment]
We can easily fix this for all command grouped. I'll submit a PR and we can discuss details there.

/assign @maximilien

**Comment by navidshaikh** [comment]
Fixed by https://github.com/knative/client/pull/218
