### ISSUE TITLE
e2e test failures: TestSink and TestSourcePing 

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#1129]
TestSink and TestSourcePing e2e tests are failing 
ref: [logs](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1128/pull-knative-client-integration-tests/1329670780031602688)

**Comment by rhuss** [comment]
Is this still the case ?

**Comment by navidshaikh** [comment]
We're carrying a workaround #1117 for it in client by embedding the namespace in the POST. The original issue with eventing is still open https://github.com/knative/eventing/issues/4514. Lets keep it open until its fixed in eventing to track reverting the workaround in client.

**Comment by rhuss** [comment]
Lets keep it still open until  knative/eventing#4514 is fixed or closed

**Comment by rhuss** [comment]
Just changed my mind, I think we can close this issuer here and continue to track it in eventing. We have a workaround that fixes the tests.
