### ISSUE TITLE
Add support for namespaces for all commands that take a --sink option

### ISSUE THREAD

**Issue by rhuss** [knative/client#1143]
### Feature request

It should be possible to specify the namespace of a sink for all commands that support a `--sink` option

### Use case

Allowing the namespace for a sink allows to create cross-namespace eventing meshes, which is a not uncommon use case. It adds a new level of flexibility for creating complex eventing architectures.

### UI Example

```
kn source ping ... --sink channel:mychannel:myothernamespace
```

would create a destination which points to another namespace. the last component after the last colon should be optional, and if not provided the namespace of the source itself is used (aka the current namespace)

**Comment by duglin** [comment]
@lionelvillard does eventing have a flag to disable support for this? There are some envs where it would not be allowed. And if there is a way to disable it how would that error be surfaced to the user with this new CLI feature?

**Comment by rhuss** [comment]
tbh, at the current state of eventing disabling cross-namespace support doesn't make much sense. A user can always provide the URL to the sink which is not secured on an eventing level. you can work with k8s authentication to avoid accessing the sink on the control plane level, but still, if you have the URL (and you can easily guess it as it follows a common naming scheme) you can access anything (broker, channel, services).

So I wouldn't mind too much about this.

**Comment by Kaustubh-pande** [comment]
I would like to work on this
/assign
