### ISSUE TITLE
Upgrading to Eventing sources and messaging latest api version

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/client#1160]
### Feature request

Eventing has changes their APIs to v1, including:
- Channels from v1beta1 to v1
- Subscription from v1beta1 to v1
- ContainerSource to v1
- pingsource resource to v1beta1
- apiserversource to v1beta1
- binding to v1beta1

We may want to support the latest version in Client.

**Comment by rhuss** [comment]
@daisy-ycguo Actually, our strategy is a bit more defensive: We want to use the *smallest* support version of any API right now. The reasoning for this is laid out in https://github.com/knative/client/issues/462

**Comment by rhuss** [comment]
Maybe its a good time now to revisit the eventing API and what we are supporting and whether we need some alignment. Any volunteer to check those API versions ?

/remove-lifecycle stale

**Comment by rhuss** [comment]
I _think_ we already updated to the v1 versions where the beta versions were removed, so I'm good with closing this issue.
