### ISSUE TITLE
kn seems to re-order the environment variables

### ISSUE THREAD

**Issue by ctron** [knative/client#1165]
### Bug report

It seems that `kn` does re-order the environment variables defined for a container.

### Expected behavior

I would expect the environment variables to stay in the same order.

### Steps to reproduce the problem

Deploy a Knative service with `kubectl apply`. Execute `kn service update -e N=1`.

The the order of environment variables is import, e.g. in the following case:

~~~yaml
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: databaseName
              name: postgres-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin.password
              name: postgres-secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: admin.username
              name: postgres-secret
        - name: DATABASE_URL
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres/$(POSTGRES_DB)
~~~

In the order show above, the `$(DATABASE_URL)` will properly be constructed. Doing a `kn update` will destroy that order, and the evaluation of variables will fail.

### kn version

```
Version:      v0.19.1
Build Date:   2020-11-25 18:27:45
Git Revision: f128d045
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.19.0)
* Eventing
  - sources.knative.dev/v1alpha2 (knative-eventing v0.19.0)
  - eventing.knative.dev/v1beta1 (knative-eventing v0.19.0)
```

### Knative (serving/eventing) version

> Nightly
> 0.12.x
> 0.11.x
> 0.10.x
> 0.9.x

**Comment by rhuss** [comment]
/remove-lifecycle stale

this is indeed a serious bug that we should address. The order of environment variables is important and should reflect the order as given on the command line.

For updates, new environment variables should be added to the end as I consider the intention that those are the most specific. I would *not* try to add a feature for allowing to reorder env variables, nor to allow to add them in the first place on the list.
