### ISSUE TITLE
Removed hard-coded "kn" in usage/error messages

### ISSUE THREAD

**Issue by rhuss** [knative/client#1191]
Instead use `argv[0]`, the first argument provided on the command line. If the command is called with a path, that path should be stripped off from the given argument.

See https://github.com/knative/client/pull/1175 for more context.

**Comment by hzliangbin** [comment]
@rhuss hi, plz let me know if I could take this issue? thanks.

**Comment by rhuss** [comment]
@hzliangbin That's great ! Please go ahead and take this issue.

**Comment by hzliangbin** [comment]
@rhuss sorry for being late. 
![kn](https://user-images.githubusercontent.com/9740458/144347645-218269d0-614b-498f-b30a-6e1236a8691b.png)
kn in root cmd usage and help should be modified too?

**Comment by rhuss** [comment]
no worries.

@hzliangbin yes, ideally everywhere where `kn` is hardcoded, that should be replaced by the real command name, without path.

**Comment by rhuss** [comment]
@hzliangbin happy new year ;-) Do you have any news on this issue ? No worries if you hadn't any time yet, but we want to tackle this story possibly for the next release.

**Comment by hzliangbin** [comment]
@rhuss haven't got any new ideas.

**Comment by rhuss** [comment]
No worries. If you don't mind, I would unassign you from this issue and add you as a reviewer when a PR comes in ?
