### ISSUE TITLE
Add support for DomainMapping resource

### ISSUE THREAD

**Issue by dsimansk** [knative/client#1197]
### Feature request

It'd be great is if we could add support for `DomainMapping` custom [resource](url), that was recently added to Serving API.

### Use case

With the use of `DomainMapping` it's possible to create custom domains per namespace and per Service reference to address the endpoints. 

The required parameters are domain name (fqdn) and reference (`Addressable`, currently only [ksvc](https://github.com/knative/serving/blob/master/pkg/apis/serving/v1alpha1/domainmapping_types.go#L75-L76)). The initial goal should be to have CRUD ops available on pair with other cmds.

### UI Example

```
kn domain create <custom-domain> --ref <Service-name> --namespace <namespace>
kn domain delete <custom-domain> 
kn domain describe <custom-domain> 
kn domain list
```

/kind good-first-issue
/kind proposal

/cc @nak3

**Comment by rhuss** [comment]
Thanks, definitely something we should add !

I wonder whether we should call it `--sink` as it is essentially the same type that a sink uses. But on the other hand sink is an eventing concept and only because it is sharing the same type doesn't mean it has to be the same option name. So `--ref` or `--reference` (with a short `-r` option) would be fine IMO.

**Comment by dsimansk** [comment]
> Thanks, definitely something we should add !
> 
> I wonder whether we should call it `--sink` as it is essentially the same type that a sink uses. But on the other hand sink is an eventing concept and only because it is sharing the same type doesn't mean it has to be the same option name. So `--ref` or `--reference` (with a short `-r` option) would be fine IMO.

I give it a thought during writing the initial description and it seemed to me that `--reference|--ref` is more suitable as it reflects the naming from DomainMapping as well.  
As pointed out by @navidshaikh, the sink flag is [extensible](https://github.com/knative/client/blob/master/pkg/kn/commands/flags/sink.go#L38) with custom flag name.

**Comment by julz** [comment]
Agree with @dsimansk that ref is better. As well as `ref` being what the yaml version uses, as of now the requirements for `ref` are slightly stricter than for sink (can't resolve to an address with a path, for example) so I think it's less confusing to keep them distinct.
