### ISSUE TITLE
./hack/build.sh failing

### ISSUE THREAD

**Issue by maximilien** [knative/client#120]
```bash
client git:(master) ./hack/build.sh
./hack/build.sh: line 22: /Users/maximilien/Desktop/github/knative-client/src/github.com/knative/client/hack/util/flags.sh: No such file or directory
```

Looks liken the file was deleted in #115 but still present in [line 22 of build.sh](https://github.com/knative/client/blob/9ec9671b2ebf8f2094ee3435e009a0f64d9f98db/hack/build.sh#L22)

Commenting that out results in:

```bash
➜  client git:(master) ✗ ./hack/build.sh
📋 Formatting
🚧 Building
./hack/build.sh: line 29: ld_flags: command not found
```

So not clear we can remove it.

**Comment by rhuss** [comment]
It looks like that the shared code between `build.sh` and `build-binaries.sh` has been moved to `release.sh` exclusively.

I send a PR to re-introduce that part.

**Comment by maximilien** [comment]
Sweet. Thx @rhuss

**Comment by adrcunha** [comment]
Sorry, my bad. #123 fixes that.
