### ISSUE TITLE
Initialize a .config/kn/config.yaml if not already exist

### ISSUE THREAD

**Issue by rhuss** [knative/client#1232]
### Feature request

If no configuration file exists, then a new one with examples and e.g a default sink mapping should be created. Maybe also add a `--no-init` option to prevent that creation and a `--init` for re-initializing the config (with doing a backup of an old one).

### Use case

This feature would be very helpful to add custom mappings by default, like discussed in https://github.com/knative/client/issues/1222#issuecomment-780203493 , which IMO could be a good compromise for supporting K8s intrinsic constructs.

**Comment by rhuss** [comment]
/remove-lifecycle stale

I still think that this feature might be helpful. What do you think ?

**Comment by boaz0** [comment]
/assign
@rhuss can you assign this to me?

**Comment by rhuss** [comment]
@boaz0 yes, sure. Thanks for your support !

**Comment by boaz0** [comment]
@rhuss & @dsimansk feel free to close this ticket :door:

**Comment by rhuss** [comment]
Thanks, @boaz0 !
