### ISSUE TITLE
Support serving 0.6.0

### ISSUE THREAD

**Issue by rhuss** [knative/client#126]
Currently running `kn` against a 0.6.0 serving version is problematic because of the changed CRD structure. Kn currently supports 0.5.2.

The two possible solutions:

1. Unconditionally upgrade to 0.6.0 which then will break usage with 0.5.2 installation.
2. Support both 0.5.2 and 0.6.0 versions, where commands discriminate on the API version and act accordingly.

I'm all for the second option, as a client should be really backwards compatible and usable with older versions of a cluster.

This is also a good occasion to exercise multi API version support already in this early stage (where APIs versions are quite volatile).

**Comment by sixolet** [comment]
Yes. Let's do the "lemonade" procedure for the next release.

**Comment by rhuss** [comment]
@sixolet Sorry for my ignorance, but what actually do you mean with 'lemonade procedure'  ?

**Comment by rhuss** [comment]
Ah, found it ;-) https://docs.google.com/presentation/d/1mOhnhy8kA4-K9Necct-NeIwysxze_FUule-8u5ZHmwA/edit#slide=id.p

**Comment by rhuss** [comment]
We already updated to 0.6.0 dependencies. I think we are good for now, except maybe we should now double check for old and new fields when retrieving objects (step #1 of the lemonade approach).

**Comment by sixolet** [comment]
Blocked by #144

**Comment by rhuss** [comment]
I think its fixed with #144 being fixed.
