### ISSUE TITLE
kn broker create with broker class

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/client#1269]
### Feature request

It would be nice to be able to specify the broker class when creating a broker, in order to create brokers with classes different from default. For more info: https://knative.dev/docs/eventing/broker/#configuring-broker-classes

### Use case

Create a Kafka Broker without setting it as default broker class: https://knative.dev/docs/eventing/broker/kafka-broker/#create-a-kafka-broker

### UI Example

```
kn create broker mybroker --broker-class="Kafka"
```

**Comment by dsimansk** [comment]
@Kaustubh-pande FYI would you like to take it?

/kind good-first-issue

**Comment by Kaustubh-pande** [comment]
Thanks, I will
/assign

**Comment by rhuss** [comment]
Sounds good. However I would call the option `--class` as `broker` seems to be redundant (we are dealing with a broker anyway)

**Comment by rhuss** [comment]
@Kaustubh-pande are you still on it ? If not, could you please unassign yourself. Thx!
