### ISSUE TITLE
List revisions for given service

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#127]
Presently, `kn revision get` will return all available revisions. `kn` should be able to filter the revisions for a given service, for eg: `kn revision get --service svc1`.

**Comment by navidshaikh** [comment]
The fix should also update [this](https://github.com/knative/client/blob/master/docs/README.md#revision-management) section of docs as well.

**Comment by rhuss** [comment]
FYI, #75 introduced a client facade which has a `GetRevisionsForService` method.

**Comment by rhuss** [comment]
#75 also implements the listing of all revisions as part of `kn service describe` (see screenshots)
