### ISSUE TITLE
Expose context to client APIs

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#1272]
### Feature request
During upgrade to k8s 1.18 libs, around knative 0.18 release timeframe, it was required to pass additional arguments for context and create/update/delete options, see https://github.com/knative/serving/pull/9367/files and https://github.com/knative/client/pull/1025/files . We worked around by adding `context.TODO` and empty create/update options.
To be consistent with the API usage pattern like in serving, eventing, k8s, we should allow the user to provide their own context.

### Use case
- Allow user to provide context while using the client APIs for more control over request lifecycle.
- Align API usage pattern with serving/eventing/k8s.

### UI Example
```go
// user's own context 'ctx'
ctx, cancel := context.WithCancel(context.Background())
knClient := NewServiceClient(namespace)
knClient.ListServices(context, ...)
```

### Implementation
This applies to different clients exposed by the kn; dynamic, serving, eventing clients.
We'd need to update the APIs of kn client to take additional argument of context, and update all the callers (and also plugins).

**Comment by matejvasek** [comment]
@navidshaikh @rhuss I started working on possible implementation.
https://github.com/knative/client/compare/main...matejvasek:knservigclient-ctx

**Comment by matejvasek** [comment]
The two last commits are not needed:
Using cmd.Context() in pkg/kn/commands 57437b7
Handling SIGINT and SIGTERM 9ca1e16

**Comment by navidshaikh** [comment]
@matejvasek nice! Can you create the PR so we've the CI verifying the changes as you keep updating the clients? 

> Using cmd.Context() in pkg/kn/commands 57437b7
Handling SIGINT and SIGTERM 9ca1e16

We can have them in a follow up PR?
