### ISSUE TITLE
Allow for tests to run in a pre-created NS

### ISSUE THREAD

**Issue by mvinkler** [knative/client#1304]
### Feature request

In some environments, it is not possible for the testing infrastructure to easily create new namespaces at will, so it would be nice if there was a way to run the e2e tests all within a single, pre-created, namespace.

### Use case

Running the kn client e2e TS on Openshift Dedicated cluster as a regular user.

**Comment by rhuss** [comment]
So you mean to separate the part where the test namespaces are created and where the tests are run and make the 'namespace create' step optional ?  Sounds like a good idea to me.

**Comment by rhuss** [comment]
Can we track the issue together with #1352 ? Closing this issue, for now, feel free to reopen it if needed.
