### ISSUE TITLE
Increase code coverage to be larger than 80%

### ISSUE THREAD

**Issue by rhuss** [knative/client#1322]
Codecov is now active and measures the code coverage which is currently ~ 73%

In order to meet the 1.0 criteria, we need to raise the coverage to 80%

The coverage with a drill down can be found at https://codecov.io/gh/knative/client/tree/main

**Comment by navidshaikh** [comment]
Pasting numbers from https://codecov.io/gh/knative/client/tree/main for files under https://github.com/knative/client/tree/main/pkg which can be picked in order


Files | tracked-lines | lines-hit | lines-partial | lines-missed | Coverage
-- | -- | -- | -- | -- | --
printers | 122 | 24 | 0 | 98 | 19.67%
wait | 192 | 126 | 17 | 49 | 65.63%
serving | 683 | 481 | 61 | 141 | 70.42%
kn | 5,984 | 4,352 | 577 | 1,055 | 72.73%
util | 233 | 188 | 12 | 33 | 80.69%
eventing/v1 | 156 | 128 | 10 | 18 | 82.05%
sources | 373 | 307 | 23 | 43 | 82.31%
templates | 106 | 89 | 8 | 9 | 83.96%
dynamic | 192 | 169 | 11 | 12 | 88.02%
errors | 40 | 38 | 1 | 1 | 95.00%


and for cmd/kn/main.go

Files | &nbsp; | • | • | • | Coverage
-- | -- | -- | -- | -- | --
pkg | 8,081 | 5,902 | 720 | 1,459 | 73.04%
cmd/kn/main.go | 70 | 46 | 7 | 17 | 65.71%


kind/good-first-issue

**Comment by dsimansk** [comment]
There's still some work to do. :)
/reopen

**Comment by dsimansk** [comment]
Files | tracked-lines | lines-hit | lines-partial | lines-missed | Coverage
-- | -- | -- | -- | -- | --
dynamic | 192 | 169 | 11 | 12 | 88.02%
errors | 40 | 38 | 1 | 1 | 95.00%
eventing/v1 | 157 | 132 | 9 | 16 | 84.08%
kn | 6,034 | 4,465 | 558 | 1,011 | **74.00%**
printers | 122 | 114 | 1 | 7 | 93.44%
serving | 684 | 494 | 62 | 128 | **72.22%**
sources | 373 | 307 | 23 | 43 | 82.31%
templates | 106 | 89 | 8 | 9 | 83.96%
util | 233 | 188 | 12 | 33 | 80.69%
wait | 203 | 142 | 15 | 46 | **69.95%**

**Comment by rhuss** [comment]
I think we are good for now but should continuously take care about keeping the coverage high (we have a PR test for that). Thanks everyone who was involved in this effort !
