### ISSUE TITLE
kn is presenting API server errors incorrectly 

### ISSUE THREAD

**Issue by avnish80** [knative/client#1342]
![image (5)](https://user-images.githubusercontent.com/47804703/121544519-6c090d80-ca27-11eb-9919-44438bc1c012.png)
![image (4)](https://user-images.githubusercontent.com/47804703/121544480-627fa580-ca27-11eb-9259-3e35d665f98b.png)

export WORKLOAD_NS=serverless-demo
kubectl create ns ${WORKLOAD_NS}

then When i run this - kn service create helloworld-go -n ${WORKLOAD_NS} \
  --image gcr.io/knative-samples/helloworld-go --env TARGET="from Serverless"

Error: Internal error occurred: failed calling webhook "webhook.serving.knative.dev": Post https://webhook.knative-serving.svc:443/defaulting?timeout=10s: context deadline exceeded

**Comment by dprotaso** [comment]
To clarify I think the API server is reporting an error invoking the webhook but the client presents this as if `kn` cannot connect

![image](https://user-images.githubusercontent.com/18562/121551456-a948ad80-c9dd-11eb-96e9-6e4cbfe76c7c.png)

**Comment by rhuss** [comment]
Hmm, I don't according to the original error report, it looks like that the client accurately reports the problem, i.e. that the webhook  has an issue (not that it does not connect).

Tbh, I'm a bit confused about the error message and what has been done (the initial issue description contains twice the same call with different output).

Could you please describe the context a bit more in depth ? (non-screenshot pastes preferred, they come out very tiny here)

**Comment by dprotaso** [comment]
if the API server returns 500 with `i/o timeout` in the error response the CLI prints 'can't connect to the cluster' which is not correct.

ie. this block of code here should be used only if a response from the API Server wasn't received/sent
https://github.com/knative/client/blob/3f424c371e6ab72f2b284165fcf9f6de032b7bc0/pkg/errors/factory.go#L35-L37
