### ISSUE TITLE
Suggestion: mixed offline/online mode for `kn create ... --target`

### ISSUE THREAD

**Issue by pianohacker** [knative/client#1346]
### Feature request

Add a new flag, `--with-target`, that creates/updates objects locally _and_ in the cluster.

### Use case

As a new user, I want to switch cleanly from creating objects with the CLI to managing them as local YAML, so that I can get started easily then switch to a GitOps workflow with the same services/triggers/etc.

### UI Example

```console
$ kn service create example --with-target my-objects/ --image helloworld-go
$ kn service update example --with-target my-objects/ ...
$ kubectl apply -f my-objects/ ...
```

/kind proposal

**Comment by rhuss** [comment]
I see your use case, but maybe `kn export` would be helpful for your case? `kn service export` and `kn service import` were created for exactly this gitops workflow, where one first interactively and imperatively build up a service but then export it for storage in an SCM.

**Comment by navidshaikh** [comment]
/remove-lifecycle stale

cc: @pianohacker
