### ISSUE TITLE
Race in waiting loop

### ISSUE THREAD

**Issue by ericmillin** [knative/client#1349]
I saw you [reverted the `resourceVersion` solution](https://github.com/knative/client/pull/1321). I have a fix for the race, though it does not do it "the right way" by watching `resourceVersion`. I can submit it if you think it is helpful as a temporary fix. There are a couple small change I will make before submitting, such as removing the paincs.

https://github.com/ericmillin/client/commit/a523953b635c6e8272ae4cd80e5569ed6c705a36

@rhuss

**Comment by dsimansk** [comment]
The fix was reverted as it seemed to cause instability in nightly/release CI jobs. However, it isn't manifesting now in the PR https://github.com/knative/client/pull/1333. Could you please take a look, maybe we can iron out any possible nits?

**Comment by ericmillin** [comment]
@dsimansk Assuming that the wait will see the `DELETED` event even if it starts after `deleteService` is called, then it looks good.

**Comment by rhuss** [comment]
@ericmillin thanks for the heads up ! Let's close this issue and continue on #1333
