### ISSUE TITLE
Improve traffic split UX

### ISSUE THREAD

**Issue by rhuss** [knative/client#1365]
The current way how to specify a traffic split has its limitations. It is at least a two-step process with setting a tag and referencing it for the split. Or at least one has to look up a revision name manually.

In this feature track https://docs.google.com/document/d/15IGutQM7TQblXJ0tTbn1Eqfi-RJZYcDhl0Rhz1QXabk/edit#heading=h.n8a530nnrb we collected the various use case which we see for a traffic split along with some proposal to improve it by introducing additional symbolic labels.

Please comment on this FT until July 20th. This issue is for tracking the work on the feature track and eventually for any following implementation work.

**Comment by vyasgun** [comment]
Pull requests for feature implementation: 
- https://github.com/knative/client/pull/1483
- https://github.com/knative/client/pull/1514

**Comment by rhuss** [comment]
Thanks a lot @vyasgun , greate work ! There might be some minor issue (e.g. when specifying a tag during service creation is should IMO stick to the created revision, not to the 'isLatest' tag. 

But let's close this issue for now
