### ISSUE TITLE
Context sensitive Bash completion

### ISSUE THREAD

**Issue by rhuss** [knative/client#1373]
### Feature request

`kn completion` is currently based on the auto generation of the bash/zsh completion code by cobra. It lacks the the possibility to complete on context sensitive information likes service or revision names, something that e.g. kubectl allows. 

We should extend the completion code to allow completion on those resources. The way how `kubectl` does it could be taken as an inspiration.

### UI Example

```
kn service describe my<TAB>
```

would complete to "myservice" if there would be a Knative service installed that is called "myservice".

Here are the smaller issues tracked by this issue:

- [x] #1374 
- [x] #1547 
- [x] #1559
- [x] #1560
- [x] #1561
- [ ] #1562

**Comment by rhuss** [comment]
Let's add #1374 first and then continue with this story.

**Comment by vyasgun** [comment]
@rhuss @dsimansk should we reopen this as only one resource has been addressed?

**Comment by rhuss** [comment]
Good point, let's keep this issue for tracking the overall story.

**Comment by rhuss** [comment]
Here are the smaller issues tracked by this issue:

- [ ] #1374 
- [ ] #1547

**Comment by vyasgun** [comment]
Sorry about the mess from too many PRs. I think we can reopen the issue and I can create subtasks for the remaining resources so this doesn't get closed before completion
