### ISSUE TITLE
Better labels and templates for issues needed for this repo

### ISSUE THREAD

**Issue by abrennan89** [knative/client#140]
We probably need more labels for issues - I don't see one for `kind/doc` and some others that exist for example in https://github.com/knative/serving/labels ?

**Comment by navidshaikh** [comment]
@abrennan89 : thanks for bringing this topic! 
/cc @sixolet

**Comment by evankanderson** [comment]
I added a few more labels, including kind/doc. I didn't copy any of:

area/* -- I can add these if needed, but wasn't sure if they were needed.
auto:flaky -- Will let test-infra add if needed
kind/good-first-issue -- /good-first-issue should work, doesn't seem like it should be a kind
kind/process -- Can add if you want
kind/question -- Again, doesn't feel like a "kind"
kind/spec -- Again, can add if needed

**Comment by abrennan89** [comment]
Sounds good, many thanks @evankanderson :)
