### ISSUE TITLE
Unmark release as "pre-release"

### ISSUE THREAD

**Issue by rhuss** [knative/client#1404]
Currently all Knative releases are marked as "pre-release":

![image](https://user-images.githubusercontent.com/99080/127296674-27499069-f9c3-49ff-a907-cc31c882dd93.png)

However, for getting `kn` into the core homebrew repository, a pre-requisite is, that the releases on GitHub must not be pre-releases. See the discussion in https://github.com/sameersbn/homebrew-core/pull/1#issuecomment-888124068

I think it should be decided on a TOC level, whether we 

* want un-mark the next release generally to be a real release
* do this only for the client repo
* or wait until we get to 1.0 (which would prevent getting `kn` to the core homebrew repo which would allow users to install kn without a homebrew tap)

/cc @sameersbn

**Comment by sebgoa** [comment]
it feels like an oversight to me. Why would the releases be marked as pre-release ? Just because this is pre 1.0 ?

**Comment by evankanderson** [comment]
I think removing the pre-release tag makes sense.

I noticed that _one_ eventing release (v0.24.0) was marked as not-pre-release, which actually hid the fact that there was a v0.24.1 patch.

@julz also agrees from TOC. (Other members weren't present at the meeting.)

Going to approve via lazy consensus unless there ends up being an objection.

**Comment by evankanderson** [comment]
Sent mail and slack; this issue will be the discussion point for enabling official releases for at least the following repos:

* knative/serving
* knative/eventing
* knative/client
* knative/operator
* knative-sandbox/net-istio
* knative-sandbox/net-contour
* knative-sandbox/net-kourier
* knative-sandbox/eventing-kafka
* knative-sandbox/eventing-kafka-broker

**Comment by csantanapr** [comment]
+1

**Comment by rhuss** [comment]
+1 to remove the pre-release tag to the repository referenced, and we can adjust the list later (e.g. for client plugins)

**Comment by evankanderson** [comment]
Marking the most-recent 6 release from the following repos as "official":

```shell
for r in knative/serving knative/eventing knative/client knative/operator knative-sandbox/net-istio knative-sandbox/net-contour knative-sandbox/net-kourier knative-sandbox/eventing-kafka knative-sandbox/eventing-kafka-broker; do
  for u in $(gh api /repos/$r/releases | jq -r 'map({url: .url,name: .name, tag: .tag_name, prerelease: .prerelease}) | .[:6] | .[] | .url'); do
    gh api -X PATCH -q ".name" -f prerelease=false $u;
  done;
done
```

**Comment by evankanderson** [comment]
Knative Serving v0.24.0
Knative Serving release v0.23.1
Knative Serving release v0.20.2
Knative Serving release v0.22.2
Knative Serving release v0.23.0
Knative Serving release v0.21.1
Knative Eventing release v0.24.1
Knative Eventing release v0.23.4
Knative Eventing release v0.22.2
Knative Eventing release v0.24.0
Knative Eventing release v0.23.3
Knative Eventing release v0.23.2
Knative Client release v0.23.2
Knative Client release v0.24.0
Knative Client release v0.23.1
Knative Client release v0.23.0
Knative Client release v0.22.0
Knative Client release v0.21.0
Knative Operator release v0.24.0
Knative Operator release v0.23.2
Knative Operator release v0.23.1
Knative Operator release v0.23.0
Knative Operator release v0.22.1
Knative Operator release v0.22.0
Knative Net Istio release v0.24.0
Knative Net Istio release v0.23.1
Knative Net Istio release v0.23.0
Knative Net Istio release v0.22.1
Knative Net Istio release v0.22.0
Knative Net Istio release v0.21.0
Knative Net Contour release v0.24.0
Knative Net Contour release v0.23.0
Knative Net Contour release v0.22.0
Knative Net Contour release v0.21.0
Knative Net Contour release v0.20.0
Knative Net Contour release v0.19.0
Knative Net Kourier release v0.24.0
Knative Net Kourier release v0.23.0
Knative Net Kourier release v0.22.0
Knative Net Kourier release v0.21.0
Knative Net Kourier release v0.20.0
Knative Net Kourier release v0.19.1
Knative Eventing Kafka release v0.24.2
Knative Eventing Kafka release v0.22.6
Knative Eventing Kafka release v0.24.1
Knative Eventing Kafka release v0.24.0
Knative Eventing Kafka release v0.23.3
Knative Eventing Kafka release v0.23.2
Knative Eventing Kafka Broker release v0.24.0
Knative Eventing Kafka Broker release v0.21.3
Knative Eventing Kafka Broker release v0.22.4
Knative Eventing Kafka Broker release v0.23.0
Knative Eventing Kafka Broker release v0.22.3
Knative Eventing Kafka Broker release v0.22.2

**Comment by evankanderson** [comment]
I need to update the release script, too.
