### ISSUE TITLE
Need to add logging to commands and tests

### ISSUE THREAD

**Issue by maximilien** [knative/client#141]
Currently we use no logs in our commands nor tests. 

IMO we *at least* need to have some logging when handling errors in commands and when failing tests so that we have some traces of the errors or failed tests. 

This is especially becoming important as we have more commands and implement integration tests across commands. And also since running these tests locally may have different results than CI/CD.

I plan to make a proposal soon unless the discussion here makes good arguments for not having any logs. Please chime in if you have opinions. Thx.

**Comment by rhuss** [comment]
With logging do you mean extra verbose output `--verbose` switch on more fine granular with logging levels ?

* With `--verbose` we could extra, also human-readable output, which fits nicely in the regular output of the command, probably also on STDOUT. 

* With `--debug <level>` we could add extra information which is more of an internal nature and e.g. could also carry timestamps and other context information which might have meaning only for os kn developers. We could put that on STDERR, so to not interfere with eg. `-o yaml` which creates machine-readable output which should be "pure".

As mentioned, I'd prefer to not call this "logs" (like for long running processes) but more like verbose and debug output for that CLI.

**Comment by sixolet** [comment]
Also this needs to be differentiated from "get logs from a running service", which is also a request (RevisionStatus includes LogURL, we can fetch that tail-style, or at least print it)

**Comment by maximilien** [comment]
Yup. Agreed.

I'll open a separate one for `kn service logs <serviceName>`

**Comment by maximilien** [comment]
@rhuss I like your suggestions. So I'll wait for a few days and assuming no additional comments I'd be happy to get to this next and perhaps also #141.

**Comment by rhuss** [comment]
Thanks ! For #141 I believe it's not so easy and needs more help from Knative serving itself. But see my comments over there.

**Comment by maximilien** [comment]
Closing this since much of this can be done with tools.
