### ISSUE TITLE
Point installation instructions to docs site?

### ISSUE THREAD

**Issue by evankanderson** [knative/client#1410]
### Bug report

There are user install instructions (which don't include installing a release version, only nightly) at https://github.com/knative/client/blob/main/docs/README.md, as well as at https://knative.dev/docs/client/install-kn/

### Expected behavior

One set of instructions which guides most users to install a released version
(This caused confusion for a customer getting `kn` tools installed.)

**Comment by kobayashi** [comment]
How about replacing contents [Installing kn](https://github.com/knative/client/blob/main/docs/README.md#installing-kn) section in README to just a link to [installation doc](https://knative.dev/docs/install/client/install-kn/)?

**Comment by garg-dhruv** [comment]
Hi, I find this issue still relevant and would like to work on it.
Which approach do we finally intend to go with?

1. Update README with full instructions to install the release version.
2. Replace the contents of 'Installing kn' subsection with the link to [Installation doc](https://knative.dev/docs/client/install-kn/) on Knative website.

**Comment by dsimansk** [comment]
>     1. Update README with full instructions to install the release version.

Let's go with options #1. Our top-level `README.md` should point to knative.dev site for `kn` installation and customization options. 

In addition I would extract `docs/DEVELOPMENT.md` to be also on top-level and move instructions for installing nightly builds etc.

**Comment by garg-dhruv** [comment]
Thanks for your input. I am working on it and will try to raise a PR by today.

**Comment by garg-dhruv** [comment]
The official website is missing `channel-type-mappings` configuration instructions compared to 'docs/README.md'.

Does `channel-type-mappings` still exist as one of the configuration options? If so, I would like to go ahead and raise a PR in knative/docs repo to amend this.

**Comment by dsimansk** [comment]
> The official website is missing `channel-type-mappings` configuration instructions compared to 'docs/README.md'.
> 
> Does `channel-type-mappings` still exist as one of the configuration options? If so, I would like to go ahead and raise a PR in knative/docs repo to amend this.

Yes, it still exists. I'd be really good to review the content, compare and update accordingly. Especially this page https://knative.dev/docs/client/configure-kn/.
