### ISSUE TITLE
Help message for `kn service apply --env` is appropriate

### ISSUE THREAD

**Issue by rhuss** [knative/client#1449]
### Bug report

`kn service apply --help` yields:

```
-e, --env stringArray                   Environment variable to set. NAME=value; you may provide this flag any number of times to set multiple environment variables. To unset, specify the environment variable name followed by a "-" (e.g., NAME-).
```

This is not correct since you can't add or remove env vars with `apply` but just set the full set of env variables. 

Same possibly for `--labels` and `--annotations` (or any map-based option)

### Expected behavior

The help message for `--env` should be different for `kn service update` and `kn service apply` as the behaviour is different (`update` : incremental changes by adding/removing, `apply`: full state)

The same is true for `kn service create` where removing env vars also doesn't make any sense.

Thanks to @pmbanugo for reporting this issue.

**Comment by boaz0** [comment]
@rhuss can you assign this to me after I finish with issue 1232
