### ISSUE TITLE
Add support for setting min/max scale

### ISSUE THREAD

**Issue by duglin** [knative/client#146]
I may have missed it, but I didn't see an issue asking for support for `--min-scale` and `--max-scale` type of options during service creation and update. These would result in setting the `autoscaling.knative.dev/minScale` and `autoscaling.knative.dev/maxScale` annotations on the knService.  I use these all the time, so being able to set the via `kn` would be really really helpful.

**Comment by maximilien** [comment]
@duglin this is fixed as @rhuss implemented a while ago. Can we close this issue?

... doing a bit of clean up 🧹 to get the issue list down to actual valid list. Thx 🙏🏽

**Comment by rhuss** [comment]
This is fixed. Let me close this but @duglin feel free to reopen if you think there is still something todo.
