### ISSUE TITLE
Add fig support

### ISSUE THREAD

**Issue by csantanapr** [knative/client#1474]
### Feature request

[fig.io](https://fig.io/) provides a great user experience on the command line, it would be awesome if the client repo provided an integration file for `kn` and plugins

**Comment by rhuss** [comment]
fig.io looks interesting, but I think it is still a bit early. Also, it concerns me a bit that getting access to Fig.app is "invite only" still, and it is not clear to me what the final licensing will be and whether Fig is sold commercially or is available for free (which is important I guess for the adoption rate).

I think we should still wait a bit and in the meantime get our bash/zsh completion story right.

**Comment by csantanapr** [comment]
Do we have issues for kn completion for bash/zsh? I have being using lately and it works for me at least "kn service"

**Comment by rhuss** [comment]
Yes, we have two issues: #1374 and #1373 , and we are planning to work on #1374 first. See also the Client Roadmap at https://github.com/orgs/knative/projects/37/views/1
