### ISSUE TITLE
Kn support for eventtype registry

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/client#1478]
### Feature request
Kn client support [Knative Eventing eventtypes](https://knative.dev/docs/eventing/event-registry/#discovering-events-with-the-registry)

### Use case
Allow users to quickly see eventtypes present on a K8s cluster and fetch a single eventtype. The kn equivalent commands for
- kubectl get eventtypes -n <namespace>
- kubectl get eventtype dev.knative.source.github.push-34cnb -o yaml

## Reference
[Slack thread that kicked this off](https://knative.slack.com/archives/CE4MVFVAQ/p1633629239035000)

I am assuming this is a good first issue for someone to tackle :) 
/kind good-first-issue

**Comment by dsimansk** [comment]
@yuvaldolev so sorry, I've missed your last comment. I'll some details and pointers to follow first thing tomorrow morning.

**Comment by itsmurugappan** [comment]
https://knative.dev/docs/eventing/event-registry/

**Comment by itsmurugappan** [comment]
my 2 cents.

Events can be registered automatically or manually. So ```kn eventtypes``` command can support 
* list
* create
* delete - should not delete automatically registered event types
* Update - not sure if fields are immutable

**Comment by yuvaldolev** [comment]
Thanks! @dsimansk @itsmurugappan

**Comment by dsimansk** [comment]
Per the above there's should basic set of command to support CRUD operations. 

For the code itself:
- `pkg/kn/commands`
  - Take inspiration from e.g. [channel](https://github.com/knative/client/tree/main/pkg/kn/commands/channel)
  - There should be group `eventtype` cmd + child ones 
- Then the client facade needs to extended to support the `Eventtype` resource
  - https://github.com/knative/client/tree/main/pkg/eventing/v1

And some conventions to take a look at: https://github.com/knative/client/tree/main/conventions

**Comment by yuvaldolev** [comment]
Thank you @dsimansk

**Comment by dsimansk** [comment]
@yuvaldolev how's it going with the issue? Please let us know if there you need any more details or explanation.

**Comment by rhuss** [comment]
@yuvaldolev any updates on this ? (no pressure, just asking to maybe reassing the issue if you are too busy)

**Comment by yuvaldolev** [comment]
Hi @rhuss  @dsimansk, I'm really sorry for the delayed response...
I'm currently very busy with work and and I'm not sure if I will have time to work on this issue in the near future.
I will release the issue and will try to work on the project when I'll have more spare time.

Sorry again.

**Comment by rhuss** [comment]
No worry @yuvaldolev , things change :) You are always welcome in case your work situation gives you a bit of spare time. Take care!
