### ISSUE TITLE
Change version display for Serving and Eventing to 1.x scheme

### ISSUE THREAD

**Issue by rhuss** [knative/client#1542]
With `kn version` for 1.0 we still get the 'technical' version of the serving and eventing dependency like in:

```
Version:      v1.0.0
Build Date:   2021-11-02 19:27:09
Git Revision: a1cf5bf8
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.27.0)
* Eventing
  - sources.knative.dev/v1 (knative-eventing v0.27.0)
  - eventing.knative.dev/v1 (knative-eventing v0.27.0)
```

We detected this late in the release process and was discussed at https://knative.slack.com/archives/C02HLGQALCE/p1635874127113600 so we should change this to 

```
Version:      v1.1.0
Build Date:   2021-11-02 19:27:09
Git Revision: a1cf5bf8
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v1.1.0)
* Eventing
  - sources.knative.dev/v1 (knative-eventing v1.1.0)
  - eventing.knative.dev/v1 (knative-eventing v1.1.0)
```

to avoid confusions.

**Comment by rhuss** [comment]
This can be implemented by adapting the code in https://github.com/knative/client/blob/a2bb4049d0f7444fb5c1bd378ca8fa1443acf2ab/hack/build-flags.sh#L32-L42 

I think a good algo could be:

* For `major.minor` pick it up from the client version as given. Alternatively, use the info from the go.mod file and apply the "magic" formular of mapping 0.27 to a 1.0 baseline.
* For `patchlevel` pick up the patch level value from the go. mod dependency.

**Comment by kobayashi** [comment]
@rhuss Please let me know if there's anything to be added to this PR.
