### ISSUE TITLE
Error: no Auth Provider found for name "azure"

### ISSUE THREAD

**Issue by niels-busch-maersk** [knative/client#1615]
### Bug report

`kubectl` works as expeceted but Knative client gives an error.
When using Azure Kubernetes Service with Knative client I get the following error:

```
kn services list
Error: no Auth Provider found for name "azure"
```

### Expected behavior

I would expect a list of my Knative services

### Steps to reproduce the problem

Set the cluster context to Azure cluster
```
kn services list
Error: no Auth Provider found for name "azure"
```

### kn version
1.2.0

```
Version:      v1.2.0
Build Date:   2022-01-26T02:16:44Z
Git Revision: 5030b5df
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving )
* Eventing
  - sources.knative.dev/v1 (knative-eventing )
  - eventing.knative.dev/v1 (knative-eventing )
```

### Knative (serving/eventing) version

> Nightly
> 0.12.x
> 0.11.x
> 0.10.x
> 0.9.x

**Comment by dsimansk** [comment]
Thanks for raising the issue. 
The linked PR should fix the issue. I'm hoping to get the Azure cluster running soon to verify it. Feel free to take a look or build `kn` with that executing `./hack/build.sh -f`.
