### ISSUE TITLE
Running test/presubmit-tests.sh updates go.mod and go.sum

### ISSUE THREAD

**Issue by nak3** [knative/client#163]
Currently `test/presubmit-tests.sh` updates `go.mod` and `go.sum`.
Here is my env info and the step to reproduce:

#### 0. go version

```
$ go version
go version go1.12.5 linux/amd64

$ git rev-parse HEAD
b6a8fa9213e40c1059d39928ca09a016dffc2eec
```

#### 1. Run `test/presubmit-tests.sh`

```
$ bash test/presubmit-tests.sh 
```

#### Actual result

* `go.mod` and `go.sum` are updated. Please refer to https://github.com/knative/client/pull/162 for the diff

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   go.mod
	modified:   go.sum
```

**Comment by maximilien** [comment]
I am still puzzled at this too... and for me, often, there is an added `junit-report` entry that is added. No idea where it comes from. Solving this is :beer: worthy at this point, when I see you in person :)
