### ISSUE TITLE
Issues with go-licenses

### ISSUE THREAD

**Issue by maximilien** [knative/client#1631]
### Bug report

Two issues:

1. on a fresh machine`./hack/build.sh` fails because it tries to `go get ... go-license` but on newer Golang `go get ...` is deprecated for `go install ...`2. 

2. when I manually build `go-licenses` and add it to my PATH I get a series of warming (See below)

# Expected behavior

Successful build with no errors or warnings

### Steps to reproduce the problem

1. Fresh machine (M1 Mac in my case)
2. Install latest version of Golang
3. Git clone client repo
4. `./hack/build/sh`

```bash
➜  client git:(main) ✗ ./hack/build.sh
🚒 Update
=== Update Deps for Golang
--- Go mod tidy and vendor
--- Removing unwanted vendor files
--- Updating licenses
W0314 15:22:23.364165   78912 library.go:86] "golang.org/x/sys/unix" contains non-Go code that can't be inspected for further dependencies:
/Users/maximilien/github/knative-client/src/github.com/knative/client/vendor/golang.org/x/sys/unix/asm_bsd_arm64.s
/Users/maximilien/github/knative-client/src/github.com/knative/client/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.1_13.s
/Users/maximilien/github/knative-client/src/github.com/knative/client/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
W0314 15:22:24.622940   78912 library.go:86] "github.com/modern-go/reflect2" contains non-Go code that can't be inspected for further dependencies:
/Users/maximilien/github/knative-client/src/github.com/knative/client/vendor/github.com/modern-go/reflect2/relfect2_arm64.s
/Users/maximilien/github/knative-client/src/github.com/knative/client/vendor/github.com/modern-go/reflect2/relfect2_mips64x.s
/Users/maximilien/github/knative-client/src/github.com/knative/client/vendor/github.com/modern-go/reflect2/relfect2_mipsx.s
/Users/maximilien/github/knative-client/src/github.com/knative/client/vendor/github.com/modern-go/reflect2/relfect2_ppc64x.s
W0314 15:22:36.579409   78912 library.go:86] "go.starlark.net/starlark" contains non-Go code that can't be inspected for further dependencies:
/Users/maximilien/github/knative-client/src/github.com/knative/client/vendor/go.starlark.net/starlark/empty.s
...
```
### kn version

N/A since trying to build latest

### Knative (serving/eventing) version

N/A

> /kind good-first-issue
> /kind bug

**Comment by dsimansk** [comment]
1. `go get` vs. `go install` is on the radar in knative/hack. We just reuse the existing functions. https://github.com/knative/hack/issues/170

2. After updating my local `go-license` to latest, I can see the same warning output. Maybe we need to fiddle with verbosity param a bit.

**Comment by dsimansk** [comment]
@maximilien I can't see the warning anymore recently. Would you mind if we close the issue?

**Comment by rhuss** [comment]
@maximilien ping, do you think we can close this issue ?
