### ISSUE TITLE
Add support for different volume types

### ISSUE THREAD

**Issue by skonto** [knative/client#1633]
### Feature request

Add support for different volume types. In Serving we have recently added two different volume types: [Emptydir](https://github.com/knative/serving/issues/11664) and [PVCs](https://github.com/knative/serving/issues/12438).

### Use case

It would be nice to extend the cli to support volumes. Users can then use the cli to add volumes as they would normally do with
a yaml file when deploying services. 

### UI Example

This could work similarly to the `--extra-containers` flag. At minimum users should be able to pass the configuration for volumes
at pod level and at container level via json/yaml data. 

If it is found useful defaults could be added. For example if emptydir is used a default volume mount could be done under a predefined dir eg. /cache along with a predefined `emptyDir.medium` eg. memory.

Examples:
```
kn service create helloworld-go --image gcr.io/knative-samples/helloworld-go --emptydir-volumes-config json_data
kn service create helloworld-go --image gcr.io/knative-samples/helloworld-go --pvc-volumes-config json_data
```
`{emptydir, pvc}-volumes-config` refers to the pod voumes field. Regarding the container volume mounts these can be configured either with an extra parameter eg. `--emptydir-volumemounts` for the user container and rely on --extra-containers flag for the rest of the mounts targeting other containers. This should be extended in the future to support [init-containers](https://github.com/knative/serving/issues/12024) too.
 
/cc @rhuss

**Comment by rhuss** [comment]
I think it's best to add support for extra volumes to our existing volume support for configmaps and secrets (`--volume` and `--mount`). We can extend the value syntax to add more volume specific options like in `--volume emptyDir:myVolumeName:type=memory` and then `--mount /path/to/mount=myVolumeName`. This should then also work for multi container ...

**Comment by skonto** [comment]
Sure I was looking for some existing volume support but it didnt come up in my search.

**Comment by vyasgun** [comment]
Reopening this issue as #1679 addresses only half of the requested feature.
