### ISSUE TITLE
Add `url` option for `kn service list --output`

### ISSUE THREAD

**Issue by psschwei** [knative/client#1691]
### Feature request

I'd like to be able to get the client to return only the URL of a particular service, i.e. something like:

```bash
$ kn service list hello -o url
http://hello.default.10.104.80.7.sslip.io
```

In theory, the implementation would be very similar to how `kn service list hello -o name` is done.

### Use case

Oftentimes I find myself creating a service and then wanting to curl it, which requires a bit of gymnastics to accomplish (either an awkward C-(mouseclick) or a `kn service list` followed by a copy/paste or a bunch of wrestling with `jq`). It'd be nice to be able to do something simple, like `curl $(kn service list hello -o url)`, which is pretty simple and wouldn't require my fingers to leave the keyboard.

**Comment by dsimansk** [comment]
It's already supported in `kn service describe`. Would it be worth addition to list command, e.g. to list more than 1 URL at once?

```
➜  ~ kn service describe hello -o url
http://hello.default.127.0.0.1.nip.io
```

https://github.com/knative/client/blob/main/pkg/kn/commands/service/describe.go#L125-L128

**Comment by psschwei** [comment]
I'm usually only working with a single service, so I didn't think to check `describe`... so looks like it's already been implemented.
