### ISSUE TITLE
Add config option to specify `readOnly` volumes

### ISSUE THREAD

**Issue by dsimansk** [knative/client#1712]
### Feature request

Per discussion at PR #1709.

Extend current `--volume` flag to accept config parameter `readOnly=true` to limit volume accessibility.

### UI Example

```
--volume pvc:myvol:readOnly=true
```

/kind good-first-issue
/kind feature

**Comment by rhuss** [comment]
Which options are actually possible ? Would be good to list those in this issue. If multiple Options can be provided that should be dependable via `,`, like in `--volume pvc:myvol:readOnly=true, anotherOption=42`
