### ISSUE TITLE
Add `--scale-activation` flag to match new Serving option

### ISSUE THREAD

**Issue by dsimansk** [knative/client#1713]
### Feature request

Consider adding a new Ksvc flag to specify activation scale value. That represents number of replicas to be scaled from zero when service is activated.

Ref: https://github.com/knative/serving/pull/13161 (note it's an update PR to introduce new & current name of option)
https://github.com/knative/serving/pull/13136 (first PR with former name)

### UI Example

```
kn service create hello --image .../myapp --scale-activation 2
```

/kind good-first-issue

/cc @dprotaso @psschwei

**Comment by rhuss** [comment]
+1, maybe we should think about the naming, to better reflect the annotation. What's about `--scale-min-active` ?

**Comment by dsimansk** [comment]
> +1, maybe we should think about the naming, to better reflect the annotation. What's about `--scale-min-active` ?

It was renamed in Serving's PR #13161 to `activation-scale`. I was a bit confused too, but that's the current naming on `main` https://github.com/knative/serving/blob/main/pkg/apis/autoscaling/register.go#L220-L225.

**Comment by psschwei** [comment]
Yeah, we went back and forth on the name just a bit :smile:  There's a fairly long [slack thread](https://knative.slack.com/archives/C9CV04DNJ/p1658938603476139) where we went over the various iterations.

**Comment by rhuss** [comment]
> Yeah, we went back and forth on the name just a bit 😄 There's a fairly long [slack thread](https://knative.slack.com/archives/C9CV04DNJ/p1658938603476139) where we went over the various iterations.

ah, what a pity that I missed that discussion. Love reasoning about naming ;-P
