### ISSUE TITLE
support uninstallation of local cluster using kn 

### ISSUE THREAD

**Issue by viveksahu26** [knative/client#1771]
### Feature request
Currently, `kn` cli support [installation](https://knative.dev/docs/install/quickstart-install/#run-the-knative-quickstart-plugin) of `knative` on `kind` and `minikube` cluster with the help `quickstart` plugin as a sub-command. But it was does not support  to uninstall them.

For uninstallation of kind it should be:
`kn quickstart kind uninstall`
and for minikube:
`kn quickstart uninstall minikube uninstall`

### Use case
Provide a easiness to do that.
Removes overhead from user.
Beginner friendly.

### UI Example

```

```

**Comment by viveksahu26** [comment]
@aliok , I will love to take this.

**Comment by aliok** [comment]
cc @dsimansk 

I am not 100% sure if we should have such functionality OR if we should simply add instructions to the "Uninstallation" section of the docs here that tells what to delete etc: https://knative.dev/docs/install/uninstall/

**Comment by psschwei** [comment]
We do have a [clean up](https://knative.dev/docs/getting-started/clean-up/) section in the docs for how to delete quickstart clusters, but it's easy to miss given that it's in the tutorial

**Comment by dsimansk** [comment]
There are step by step instruction to remove the cluster. But for the local kind or minikube instances it's probably easier to recreate the whole cluster at once. 

@viveksahu26 do you feel like `quickstart uninstall` would be still a valid addition? E.g. moving between Knative versions maybe?
