### ISSUE TITLE
Eventing TLS: support Eventing TLS in kn-plugin-event 

### ISSUE THREAD

**Issue by pierDipi** [knative/client#1801]
### Feature request

As the [Eventing TLS feature track](https://docs.google.com/document/d/1H-x_oji8LqkCyd7tlsSyclmUe7FAmEJPgRxOU_0pkn8/edit) describes we should support in kn-plugin-event sending events to HTTPS endpoints

I'm opening this issue here instead of on the actual kn-plugin-event repository since I'm tracking the progress on [a project in the knative org](https://github.com/orgs/knative/projects/55/views/4)

### Use case

As a developer
I want to sent events to HTTPS endpoints of Addressables
so that events don't transit in plaintext

### UI Example

I'm not sure, we can discuss this aspect.

```

<!--
Optional Classifications, remove the '> ' to select:
> /kind good-first-issue
/kind proposal
> /kind doc
> /kind cleanup
-->

**Comment by rhuss** [comment]
@pierDipi +1, makes totally sense. I move this issue to https://github.com/knative-sandbox/kn-plugin-event

**Comment by rhuss** [comment]
I moved it manually to https://github.com/knative-sandbox/eventing-kafka/issues/1360 (GitHub does not support transfer of issues across organisations)
