### ISSUE TITLE
Upgrade deprecated v1alpha1 DomainMapping API to newer one

### ISSUE THREAD

**Issue by dsimansk** [knative/client#1854]
The upgrade is failing due to missing v1alpha1 DomainMapping API. We need to upgrade to newer version. 

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1852/unit-tests_client_main/1693436714506260480#

_Originally posted by @dsimansk in https://github.com/knative/client/issues/1852#issuecomment-1686227886_

**Comment by dsimansk** [comment]
@xiangpingjiang feel free to ping me here or on CNCF Slack if you need any pointers. It's mainly "replace old string new string" (with `sed` or similar :)) exercise.

**Comment by xiangpingjiang** [comment]
> @xiangpingjiang feel free to ping me here or on CNCF Slack if you need any pointers. It's mainly "replace old string new string" (with `sed` or similar :)) exercise.
> 
> If you look for `EvenType` bump in the commit history, it's the same deal.

@dsimansk 

I think we should firstly upgrade the latest dependencies, and then I can use the v1beta1 DomainMapping API

**Comment by dsimansk** [comment]
A few helpful steps that should enabled you to proceed: 

1. Rename package to v1beta1 https://github.com/knative/client/tree/main/pkg/serving/v1alpha1
2. Within the package change all the imports from deprecated Serving's `DomainMapping` `v1alpha1` -> `v1beta1` 
3. Run `./hack/update-deps.sh` to update `vendor/` dir
4. Fix any code changes, field names or function signatures etc. (should be minimal)
5. Check for other references to `v1alpha1` in the code base.
