### ISSUE TITLE
Distinguish missing Serving/Eventing API from unsupported version 

### ISSUE THREAD

**Issue by dsimansk** [knative/client#1858]
### Feature request

In the current implementation when `kn` is unable to query Knative resource, we display combined "no or newer" error on missing API or incompatible API. 

Per feedback from users, that might be confusing how to approach the troubleshooting of such issue with the Knative installation. 

```
Error: no or newer Knative Serving API found on the backend, please verify the installation or update the 'kn' client
```

### Use case

There are 2 main scenarios to cover: 

1. There's no Knative Serving/Eventing API found on the cluster. This might be mangled installation, operators still installing, missing CRDs, controllers not up. 

```
Error: no Knative Serving API found on the backend, please verify the installation
```

2. The incompatible API version, e.g. removed `v1alpha1` and therefore backend x `kn` mismatch. 
```
Error: incompatible Knative Serving API found on the backend, please verify the installation or update the 'kn' client to matchin version
```

/cc @rhuss

**Comment by rhuss** [comment]
For scenario 1, I guess `or udpdate the kn client` won't help :-)

**Comment by dsimansk** [comment]
> For scenario 1, I guess `or udpdate the kn client` won't help :-)

Yep, fixed the proposed errors.

**Comment by rhuss** [comment]
Sounds good, I think you can get over the `/apis` endpoint and I also think its good enough to check whether there is a KService resource in any version, then --> "no Knative API found", otherwise just assume that that there is a version mismatch (the only other possible error),. so no need to really check the version.
