### ISSUE TITLE
Update plugin development docs

### ISSUE THREAD

**Issue by dsimansk** [knative/client#1861]
A few points to polish around plugin development readme:

- [ ] References should point to `kn-plugin-sample` as base for the plugin
  - (optional) Check and update the sample plugin code if needed
- [ ] There should inlined code examples that leverage knative.dev/client-pkg only not `client` directly
- [ ] Double-check if the content is still up-to-date in other parts.

https://github.com/knative/client/tree/main/docs/plugins#kn-plugins

/kind doc
/kind good-first-issue

**Comment by asr2003** [comment]
@aliok Is this issue is ready to work? I would like to explore the projects under our knative community.
