### ISSUE TITLE
Wrong version for kn create kafka channel

### ISSUE THREAD

**Issue by Leo6Leo** [knative/client#1885]
https://github.com/knative/client/blob/ae35736892402050eb910d2b43a70f41e1d225c4/docs/cmd/kn_channel_create.md?plain=1#L22

The version here should be v1beta1 as we can refer to [here](https://github.com/knative-extensions/eventing-kafka-broker/blob/main/control-plane/pkg/reconciler/channel/apis/messaging/kafka_channel_lifecycle.go#L24)

**Comment by Cali0707** [comment]
Thanks for reporting @Leo6Leo

**Comment by Cali0707** [comment]
It also shows up here: https://github.com/knative/client/blob/ae35736892402050eb910d2b43a70f41e1d225c4/pkg/kn/flags/channel_types.go#L57

**Comment by Cali0707** [comment]
Thanks for finishing this @MeenuyD !! :tada:
