### ISSUE TITLE
Exchange SERVICE and NAME column in kn revision list output

### ISSUE THREAD

**Issue by rhuss** [knative/client#195]
The NAME should be always first, and only then the service name to which a revision belongs. This not only for consistencies sake, also to make the first column to be the id (and since a revision name typically is prefixed with the service name, you have both info already in the first column)

**Comment by rhuss** [comment]
@navidshaikh what's your opinion on this issue ? I think it would be easy to fix, but we should agree on that.

**Comment by navidshaikh** [comment]
@rhuss : 
> This not only for consistencies sake, also to make the first column to be the id (and since a revision name typically is prefixed with the service name, you have both info already in the first column)

This makes sense to me.

We can also list the revisions for single service, do we want to remove the service name column altogether in that case? (this might require additional work on the printer side to understand when not print given column(s))

**Comment by rhuss** [comment]
> We can also list the revisions for single service, do we want to remove the service name column altogether in that case? (this might require additional work on the printer side to understand when not print given column(s))

Yes, I think it makes sense to hide the service if the revision is listed for a single service only. This is also the behaviour of kubectl when you list for a single namespace only (namespace is not shown) or across namespaces (e.g. with --all-namespaces, then a namespace column is shown).

But I don't have a very strong opinion on that, so would be ok to keep the service in all cases. The difference to the namespace example above is, that a revision doesn't have to be attached to a service (unlikely case, and not possible with `kn` alone, but if someone creates resources outside of kn we should be still able to list those)

**Comment by navidshaikh** [comment]
@rhuss : Alright, lets scope this issue for exchanging the column names, we'll address hiding the SERVICE name column altogether with subsequent iterations.
