### ISSUE TITLE
Implement kn route describe command

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#205]
with `kn route describe` taking an argument for route name

**Comment by zhangtbj** [comment]
Raise a PR #228 to fix this issue.

**Comment by jchesterpivotal** [comment]
Following from the [4 Feb 2020 CLI WG meeting](https://docs.google.com/document/d/1Uh7jTWQruBBmic-WmTvtc9cMF95kQrKb5lsqWhNuikM/edit#heading=h.98s6rrkt5nbu), I think that we need to decide:

1. Whether we're keeping `route describe`, and
2. If we're keeping it, what format it should take.

This issue might need to be closed -- _technically_ there's a command and it does spit out information. But the UX is quite different from `service describe` or `revision describe`.
