### ISSUE TITLE
Implement kn revision describe command

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#206]
with `kn revision describe` taking an argument for revision name

**Comment by zhangtbj** [comment]
Hi @navidshaikh ,

I saw the `kn revision describe` is implemented here:
https://github.com/knative/client/blob/master/pkg/kn/commands/revision/revision_describe.go

I think it is already finished. correctly?

**Comment by navidshaikh** [comment]
Hi @zhangtbj : Present `kn revision describe` prints the yaml output of the object, the goal is to present the revision object in better human readable format with some additional details.

**Comment by zhangtbj** [comment]
Thx @navidshaikh , now I see the yaml output is native revision information output from kube. And kn client also provides other formats like json, name....

what is mean `better human readable format`? And is there any rule or standard that how to present?

**Comment by zhangtbj** [comment]
Oh, I saw the format is discussed in this PR:
https://github.com/knative/client/pull/75

Let us also discuss there. Thanks

**Comment by rhuss** [comment]
@zhangtbj I will split up the #75 PR soonish, focussing first on the non-color options. There won't be much activity on this PR anymore therefor.

At #235 I started a discussion about the general nature of `kn <noun> describe`, so its worth to watch and comment on this, too.

**Comment by navidshaikh** [comment]
This is the only issue pending for v0.8.0 milestone, can we scope this for next milestone and cut v0.8.0?

@rhuss @sixolet @maximilien WDYT ?

**Comment by rhuss** [comment]
I'm fine with postponing this feature for the next release, we already have made quite some progress since 0.2.0 which would justify a release on its own.

**Comment by navidshaikh** [comment]
Implemented by #475 
/close
