### ISSUE TITLE
Operation 'service update' failing in e2e tests

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#211]
Recently PRs are failing e2e tests for `kn service update` operation, specifically
```
Running 'kn service update hello --env TARGET=kn -n kne2etests'...
Failed to successfully execute 'kn service update hello --env TARGET=kn -n kne2etests': Execution error: stderr: 'Operation cannot be fulfilled on services.serving.knative.dev "hello": the object has been modified; please apply your changes to the latest version and try again
```
this is not 100% re-producible, as for few PRs e2e tests passed, for eg: https://github.com/knative/client/pull/207

**Comment by maximilien** [comment]
I’ve never seen this particular error. But good to have a place to track.

Worth noting that I run this on a cluster with an older version of Knative.

@navidshaikh any additional info would be useful. Is this latest release?

**Comment by navidshaikh** [comment]
> Worth noting that I run this on a cluster with an older version of Knative.

same for me, I'd tested the e2e in a cluster running serving 0.6.0.

> @navidshaikh any additional info would be useful. Is this latest release?

I think yes, as we do https://github.com/knative/client/blob/a7d1bc9dc00182d31cb1b946e95c78dba9559060/test/e2e-tests.sh#L38

**Comment by maximilien** [comment]
OK, thanks. I’ll run it a few times and see if I can reproduce. 

NOTE: may have to update any results in a few days as it’s Friday night here in Taipei.

**Comment by rhuss** [comment]
This race might be gone now as we are now defaulting to sync creation so that the service creation which reconciled while the update was called on an outdated version cannot happen. 

Of course we should start other tests for the async mode, too, but for now I think we are good.

**Comment by navidshaikh** [comment]
@rhuss : :+1:
