### ISSUE TITLE
`kn version` doesn't work

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/client#212]
When I ran `kn version`, I got below output. I think it doesn't work.

```
$ kn version
Version:
Build Date:
Git Revision:
Dependencies:
- serving:
```

**Comment by maximilien** [comment]
Never seen this before. Did you build from source? Give more details.

**Comment by rhuss** [comment]
@daisy-ycguo I suspect you did just a plain `go build`. Please use `hack/build.sh` for building as this script will set the relevant information.

**Comment by daisy-ycguo** [comment]
I downloaded the binary file `kn` directly from below link described at https://github.com/knative/client/blob/master/docs/README.md.

 * [Max OS X](https://storage.cloud.google.com/knative-nightly/client/latest/kn-darwin-amd64)

When I get a new `kn` by building from source code, `kn version` works well.

**Comment by rhuss** [comment]
Interesting, when I download & run --> 

```
Version:      v20190630-43b37a6
Build Date:   2019-06-30 10:04:29
Git Revision: 43b37a6
Dependencies:
- serving:
```

So it looks like the version is right, but the dependency version is missing (should be '0.6.0').

@sixolet @cppforlife @adrcunha any idea how these nightly binaries are created ?

**Comment by adrcunha** [comment]
See hack/release.sh

**Comment by rhuss** [comment]
The issue should be fixed now, but we have to verify it with the nightly build which is going to be created this night.
