### ISSUE TITLE
Separate leaf command implementation from cobra RunE

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#230]
Leaf commands' implementation is embedded in cobra's RunE.

How about generating respective leaf command flags in command group and passing over the flags from command group ?

For example, in pkg/kn/commands/service/service.go, we can update the leaf command's signature to
```
  serviceCmd.AddCommand(NewServiceListCommand(p, NewServiceListFlags())) 
````

and the leaf command `service list` flag becomes
```
func NewServiceListCommand(p *commands.KnParams, flags *ServiceListFlags) *cobra.Command {
    [..]
    RunE:  func(cmd *cobra.Command, args []string) error { return flags.Run() },
  }
```

This way we have better separation and a single place in command group (service/service.go) where flags are composed and passed over to leaf commands.

**Comment by maximilien** [comment]
It’s odd to have a `Run()` method on something called `Flags` IMO.
