### ISSUE TITLE
Support tagging resources

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#231]
Add support for labeling resources with particular tags.
This is to track adding code which provides easy interface for consumers to tag given resources.

As we are working on detailing specifics of traffic splitting in #210 , getting this ready should be progress in that direction.

**Comment by rhuss** [comment]
Renamed the subject to avoid confusion, hope its ok.

**Comment by navidshaikh** [comment]
Word `tag` should be referred in terms of traffic splitting of targets while `label` should denote user defined labels for grouping/listing etc. As we'll implement tagging targets part of traffic splitting issue, closing this issue in favor of #328.
