### ISSUE TITLE
Add command for tagging revisions

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#232]
This is followup issue of #231, the idea is to introduce leaf command for labeling revisions.
Couple of verb choices: `tag`, `label` 
I personally like `kn revision tag`.

**Comment by rhuss** [comment]
I definitley all for `tag` to avoid any confustion with `metadata.labels`

**Comment by maximilien** [comment]
Yup. We had that in `knctl`. Should be also useful for how we end up doing #210.

**Comment by sixolet** [comment]
Fixed by #345
