### ISSUE TITLE
Add integration tests for min/max scale options of service create and update

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#254]
For service create and service update, we are missing coverage for following options
```
      --max-scale int            Maximal number of replicas.
      --min-scale int            Minimal number of replicas.
```

**Comment by zhangtbj** [comment]
Hi @navidshaikh ,

If no one looking at this, I would like to take it.

**Comment by navidshaikh** [comment]
@zhangtbj : sure, I think the tests for this should be in service_advance_test.go as done in #256.

**Comment by rhuss** [comment]
> @zhangtbj : sure, I think the tests for this should be in service_advance_test.go as done in #256.

yeah, except maybe rename the file to something more specific. See my PR comments in #256

**Comment by zhangtbj** [comment]
got it. Thx!

**Comment by navidshaikh** [comment]
@zhangtbj : didnt see the tests coming in yet, I will have a PR for this today.

**Comment by zhangtbj** [comment]
Yes, I didn’t work on that. Pls go ahead.
