### ISSUE TITLE
OCI image created with ko in a release misses version informations

### ISSUE THREAD

**Issue by rhuss** [knative/client#257]
## In what area(s)?

Release 

## What version of Knative Client?

```
Version:      v20190710-local-31dc57a-dirty
Build Date:   2019-07-10 09:51:46
Git Revision: 31dc57a
Dependencies:
- serving:    v0.6.0
```

## What version of Knative Serving running on your cluster?

0.7.x

## Expected Behavior

The image created during the release in https://github.com/knative/client/blob/e1614f95e662e9e6f7f520eb2b33181d7b264a28/hack/release.sh#L36 with `ko` should also contain all version informations (propagated via `ldflags`)

## Actual Behavior

Running the created Docker image with the coordinates from the 0.2.0 release  yields:

```
docker run --rm -it gcr.io/knative-releases/github.com/knative/client/cmd/kn@sha256:393035ce99f1e639ba859d35ffb8b3f328722a2f22ab4b4ea1d889b9c015af49 version

Unable to find image 'gcr.io/knative-releases/github.com/knative/client/cmd/kn@sha256:393035ce99f1e639ba859d35ffb8b3f328722a2f22ab4b4ea1d889b9c015af49' locally
sha256:393035ce99f1e639ba859d35ffb8b3f328722a2f22ab4b4ea1d889b9c015af49: Pulling from knative-releases/github.com/knative/client/cmd/kn
155814304360: Pull complete
4003b5b92ca9: Pull complete
1f704ff7c739: Pull complete
Digest: sha256:393035ce99f1e639ba859d35ffb8b3f328722a2f22ab4b4ea1d889b9c015af49
Status: Downloaded newer image for gcr.io/knative-releases/github.com/knative/client/cmd/kn@sha256:393035ce99f1e639ba859d35ffb8b3f328722a2f22ab4b4ea1d889b9c015af49
Version:
Build Date:
Git Revision:
Dependencies:
- serving:
```

**Comment by zhangtbj** [comment]
Interesting, I tried to create the image and docker run version, also get empty info:
```
jordanzt@zhangtaodembp:~/Works/workspaces/gopath/src/github.com/knative/client$ docker run --rm -it us.icr.io/knative_jordan/github.com/knative/client/cmd/kn:latest version
Version:
Build Date:
Git Revision:
Dependencies:
- serving:
```

But I checked `ko` command, it doesn't support `ldflags` flag. should use a `ldflags` similar way to add the info when `ko` creating the image? Or....

**Comment by rhuss** [comment]
Yes, these flags are required during build to propagate the version information as golang variables. If `ko` doesn't support arbitrary `go build` options, then we could switch to a plain Docker build easily on our own

**Comment by zhangtbj** [comment]
Hi @rhuss , 

I found there is a Configuration file`.ko.yaml` to config `ldflags` for buildOverrides, like this:
```
buildOverrides:
  github.com/my-org/my-repo/path/to/binary:
    flags:
    - name: ldflags
      value: "-X main.Version=foo"
```

Link: https://github.com/google/ko/issues/54

But it doesn't work.... I asked in `ko` slack channel:
https://knative.slack.com/archives/CAVRMBUMA/p1563264859136500

Hope it works. if not, we can use docker to build with `ldflags` in Dockerfile. But how we publish the image to docker registry without ko? I think we need more logic to do that.

**Comment by navidshaikh** [comment]
/reopen
/remove-lifecycle stale

still an issue with kn v0.19.0 release
```
docker run -t gcr.io/knative-releases/knative.dev/client/cmd/kn@sha256:8a05c75916cf0c68469a7724e17ff9ff4697f38a59197dbd2435e811c44d8d87 version
Version:      
Build Date:   
Git Revision: 
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.19.0)
* Eventing
  - sources.knative.dev/v1alpha2 (knative-eventing v0.19.0)
  - eventing.knative.dev/v1beta1 (knative-eventing v0.19.0)
```

**Comment by rhuss** [comment]
Still an issue with v0.24.0

/remove-lifecycle stale

**Comment by dsimansk** [comment]
With latest nightly image.
```
➜  ~ podman run --rm -it gcr.io/knative-nightly/knative.dev/client/cmd/kn version
Version:      v20220502-local-bcd18d39
Build Date:   2022-05-02 09:12:15
Git Revision: bcd18d39
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.31.1-0.20220427153405-71842357ab0d)
* Eventing
  - sources.knative.dev/v1 (knative-eventing v0.31.1-0.20220427174252-2219e1485934)
  - eventing.knative.dev/v1 (knative-eventing v0.31.1-0.20220427174252-2219e1485934)
```
