### ISSUE TITLE
What other kn config options makes sense to load and save?

### ISSUE THREAD

**Issue by maximilien** [knative/client#259]
## In what area(s)?

Configuration / startup.

Classifications:

/kind usage

## Ask your question here:

With #249 we will have one option in the kn config `pluginDir` that allows the end user to load and save their chosen directory for plugins.

Since we added config to support this, the question is, are there other config options we should be saving and loading. For instance:

* quiet
* namespace
* ?

Or maybe nothing. Just want to start a discussion on the topic since that might dictate how #249 loads and saves the config (in terms of when and how eager).

**Comment by sixolet** [comment]
* Do you want to client-side generate revision names?
* Do you want to protect yourself from unexpected code changes by locking images to digest in non-image updates?

**Comment by maximilien** [comment]
We should probably start suggesting names and defaults too. I am changing how I save config and only do so when command succeeds. So the following in [`pkg/cmd/kn/main.go`](https://github.com/knative/client/blob/master/cmd/kn/main.go) instead of current.

```go
[...]

func init() {
	core.InitializeConfig()
}

func main() {
	err := core.NewDefaultKnCommand().Execute()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	cleanup()
}

func cleanup() {
	viper.WriteConfig()
}
```

Will be in #249. So intermediary config won't be saved until success. Let me know if that's OK with your thinking of future usages.

**Comment by maximilien** [comment]
Closing this as I think config is all done and setup now
