### ISSUE TITLE
move `kn completion` to be an option instead of a noun

### ISSUE THREAD

**Issue by duglin** [knative/client#261]
Classifications:
/kind good-first-issue
/kind proposal

## Describe the feature:

Right now the `kn` help text shows `completion` as the first, and longest, noun/command available to people:
```
$ kn help
Manage your Knative building blocks:

Serving: Manage your services and release new software to them.
Build: Create builds and keep track of their results.
Eventing: Manage event subscriptions and channels. Connect up event sources.

Usage:
  kn [command]

Available Commands:
  completion  Output shell completion code (default Bash)
  help        Help about any command
  revision    Revision command group
  service     Service command group
  version     Prints the client version

Flags:
  -h, --help                help for kn
      --kubeconfig string   kubectl config file (default is $HOME/.kube/config)

Use "kn [command] --help" for more information about a command.
```

I have some concerns about this:
- showing up first in the list of nouns make it pretty prominent and will get people's attention. This command is probably one that most people will either never run or run only once *ever*. Yet it's the first thing a newbie will see.
- it's output is daunting to someone who has no idea what it's for - like a newbie. So it's exposing a pretty geeky aspect of bash/zsh that (sort of) goes against the idea of simplifying the UX

Some ideas for ways to make this less in-your-face, and provide a nicer UX:
- make it an option instead. For example: `kn help --bash-completion` since providing this output is more like a helper function anyway
- rather than dumping a ton of text to the screen, which the person will then have to either redirect to a file or copy-n-paste to a file, just write it out to a file. Could be a local file they then copy or we could even try to write it directly to /etc/bash_completion.d for them. Either way, we can then also print some help text telling them what to do with the file or what the output is all about - something you can't do if stdout is reserved for the script itself.

**Comment by rhuss** [comment]
I agree that it shouldn't be shown that prominent, and we should handcraft the help screen anyway.

Making it a pure option would break our general structure to require a <command>. The same for help, I wonder why there is a "help" command and "-h" and "--help" option.

Also, having a the auto-generated completion only is not really a good benefit. I'm not sure whether we already allow completion on revision/service *names* and how far the completion support.

There are examples I've seen where commands are grouped in the help message. E.g we could start to group acccording to the knative component.

E.g.

```
Knative serving:
  service - ....
  revision - ...
  ...

Knative eventing:
  importer - ...
  broker - ....
  ...

Misc:
  completion - ...
  help - ... 
```

Would this be a good compromise ?

**Comment by duglin** [comment]
> "I wonder why there is a "help" command and "-h" and "--help" option.

I kind of agree. Typically: `cmd` and `cmd -h` and `cmd --help` and `cmd -?` should be enough, w/o the need for a dedicated `help` noun.  I've seen some cmds support a `help` noun w/o listing it in their help text too - that's always an option.  I think docker and kubectl do that too - fwiw.

re: grouping - I think that will make sense when we have more nouns. But right now the list isn't too bad.

> Making it a pure option would break our general structure to require a . 

Did you miss a word before the `.` ?

If putting it as an option is a concern, what about under some kind of `config` noun? What ever happened to the idea of that noun?  So something like:
```
kn config completion
```
type of thing.  I think that could make a lot of sense since this really is a configuration type of thing anyway.

**Comment by rhuss** [comment]
> > Making it a pure option would break our general structure to require a .
> 
> Did you miss a word before the `.` ?

yeah, sorry. I meant require kind of a 'default' command (i.e. using kn without any command). I'm not a fan to add --completion to help, a no-op command otherwise.

wrt/ moving to `config`: If we settle on using verbs after `config` (like set/get/view) then `completion` doesn't make much sense. Not really sure where to put it as I don't think it doesn't fit in any other existing command.

If you follow the discussion around eventing, there will be probably many more nouns coming up (importer/broker/channel/connection/event/...) so that grouping even at this point might make sense. Maybe more sense as to think right now where "completion" will end up (still happy to have it as a top-level, "misc" like command, like "help" and "version")
