### ISSUE TITLE
Kn plugins should support plugins with group (or sub commands) named with dash, e.g., `foo-bar`

### ISSUE THREAD

**Issue by maximilien** [knative/client#272]
## In what area(s)?

Kn plugins

Classifications:
/kind feature
/kind proposal

## Describe the feature:

In current Kn plugins #92 #249 the convention limits what a plugin can be named. This is inherited from `kubectl` plugins implementation and convention.

Specifically, plugins name cannot have `-` in their name since the dash would be seen as sub commands. For examples: 

```bash
➜  client git:(kn-plugins4) cat /usr/local/bin/kn-foo-bar
#!/bin/bash

echo "My first command-line argument was '$1'"
➜  client git:(kn-plugins4) cat /usr/local/bin/kn-foo_bar2
#!/bin/bash

echo "My plugin got command-line argument was '$1'"
➜  client git:(kn-plugins4) ./kn plugin list
The following compatible plugins are available:

/usr/local/bin/kn-foo-bar
/usr/local/bin/kn-foo_bar2
➜  client git:(kn-plugins4) ./kn foo bar lol
My first command-line argument was 'lol'
➜  client git:(kn-plugins4) ./kn foo_bar2 lol
My plugin got command-line argument was 'lol'
```

In order to have commands with `-` in the name, e.g., `kn foo-bar` where `foo-bar` is the name of the command, a simple solution could be to use `--`. 

So the plugin with file `kn-foo--bar` would be a plugin named `foo-bar` and as before `kn-foo-bar` is a plugin with command group `foo` and sub command `bar`, i.e., `kn foo bar`. 

And by extension, use `--` also for sub commands that would need a dash in name. So: `kn-foo--bar-blah--lol` is a command with group `foo-bar` and sub command `blah-lol`, i.e., `kn foo-bar blah-lol`

[Comment](https://github.com/knative/client/pull/249#discussion_r304632660) that initiated this from @rhuss

**Comment by rhuss** [comment]
I really would love to stay with the way how kubectl does it:

* If a subcommand contains a dash, use an underscore in the filename. E.g. a kn command `kn service list-types` would translate into a filename `kn-service-list_types`
* Given a plugin with an underscore in its name like `kn-service-list_types` you can call it in two ways:
  - `kn service list-types`
  - `kn service list_types`

See https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#names-with-dashes-and-underscores for the full details.

There is no need to invent our own convention.

**Comment by maximilien** [comment]
Agree @rhuss that's how it's implemented now. As I have been saying all along. Let's be compatible with `kubectl` plugins. So I will close this issue.

If you see a discrepancy then open a bug. Thx.
