### ISSUE TITLE
Add option to allow enviornment variables using file

### ISSUE THREAD

**Issue by kameshsampath** [knative/client#278]
/kind feature

## Describe the feature:

Currently the `kn` command allows specifying the `environment` variables using `--env KEY=VALUE` pattern, it will be nice to have an option to specify the value via environment file.

e.g. 

env-file
--------
foo=bar
com.example.data=one

And the command can then have option like `--env-file=foo.env`  while doing create/update etc.,

**Comment by boaz0** [comment]
@rhuss can you assign this to me? seems like a useful feature for me to work on.

**Comment by rhuss** [comment]
@boaz0 sure, no problem. Sorry for the delay, I was on PTO the last two weeks.
