### ISSUE TITLE
`kn service update` should print an error message when invalid or no option is passed

### ISSUE THREAD

**Issue by toVersus** [knative/client#286]
## In what area(s)?

/kind good-first-issue
/kind feature

## Describe the feature:

When users run `kn service update` command with invalid options, nothing is changed. But in current implementation, kn prints the following output:

```
$ ./kn service update hello --max-scale -100
Waiting for service 'hello' to become ready ... OK
Service 'hello' updated in namespace 'default'.
```

IMO, this is a little confusing behavior. Kn should print `unchanged` when it changed nothing as kubectl does. I think we can implement this feature by comparing the generation before and after [updating the service resource](https://github.com/knative/client/blob/75a41def4e2753fac76d113c331f036499228a95/pkg/serving/v1alpha1/client.go#L177) and returning changed/unchanged state (boolean).

```
$ ./kn service update hello --max-scale -100
Service 'hello' unchanged in namespace 'default'.
```

Can I take this, if you can accept this proposal?

**Comment by rhuss** [comment]
Shouldn't we just print an error in this case ? like "-100 is an invalid value for max-scale".

Anything else would be surprising.

**Comment by rhuss** [comment]
And then the "unchanged" message is unnecessary (you perfectly can assume that the service is not changed if an error occurs)

**Comment by toVersus** [comment]
> Shouldn't we just print an error in this case ? 

Ah, maybe I mixed up things, so aren't there any strong opinions in current behavior, which silently keeps "unchanged" state if users input invalid values. Can we require to pass at least one option at anytime for avoiding the following case ?

```
$ ./kn service update hello
Waiting for service 'hello' to become ready ... OK
Service 'hello' updated in namespace 'default'.
```

**Comment by rhuss** [comment]
Good point. We should catch that and return an error for such a no-op.

Of course, when we update with a new value == old value, we should not worry about (and should also print the success message)

**Comment by zhanggbj** [comment]
Hi @toVersus @rhuss ,

If nobody's working on this, I would like to take it. Thanks!
From the above comments, I think two items need to fix.

- Add input validation for `kn service update` flags, for e.g., if `--max-scale -100` is specified, we should return an error.

- If no input for `kn service update`, we should return an error.

**Comment by rhuss** [comment]
@zhanggbj agreed on the action items.

/assign zhanggbj

**Comment by toVersus** [comment]
@zhanggbj Thanks for picking it up! I worked on the first item in #279. I would appreciate if you look into the PR before implementing the second action item.

**Comment by zhanggbj** [comment]
@toVersus Sure, no problem! I just noticed your PR, maybe you can refer this issue item in your PR comment so people can know you are working on it :)
