### ISSUE TITLE
Order the revisions in `kn revision list` output by configuration generation number

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#289]
## In what area(s)?
/kind feature
/kind proposal

## Describe the feature:

The present `kn revision list` output doesn't hint the order in which revisions are created, 
```
✗  kn revision list -s bluegreen 
NAME              SERVICE     AGE   CONDITIONS   READY   REASON
bluegreen-2lg4q   bluegreen   28s   4 OK / 4     True    
bluegreen-45sk7   bluegreen   12m   3 OK / 4     True    
bluegreen-s52lb   bluegreen   25s   4 OK / 4     True    
```
Although there is `AGE` column but we can ease the lookup by printing the numbers in descending order (and respective revision row), highest denoting the latest revision created for the service.

I think we'll need this because a user might want to copy over the revisionName, she last generated for a service to refer in other operations (for example traffic splitting).

For eg:
```
kn service create bluegreen --image gcr.io/ns/bluegreen
kn service update bluegreen --env COLOUR=blue
kn service update bluegreen --env COLOUR=green
```
now I can check the `kn revision list -s bluegreen` 
```
kn revision list -s bluegreen 
NAME              SERVICE     ORDER  AGE   CONDITIONS   READY   REASON
bluegreen-2lg4q   bluegreen   3      28s   4 OK / 4     True    
bluegreen-s52lb   bluegreen   2      25s   4 OK / 4     True    
bluegreen-45sk7   bluegreen   1      12m   3 OK / 4     True    

```
and know that revision names order by referring to column `ORDER`

**Comment by duglin** [comment]
I would prefer to just order them by age and put the newest one at the top of the list

**Comment by rhuss** [comment]
yes, label with name `serving.ConfigurationGenerationLabelKey` hold's the configuration's generation at creation time. This should be the sort column.
