### ISSUE TITLE
Traffic splitting design: Is an opinionated rollout part of the MVP?

### ISSUE THREAD

**Issue by sixolet** [knative/client#298]
One of several polls about how our traffic splitting and tagging should be set up. This one is about whether opinionated workflow goals like "rollout" or "rollback" should be part of the traffic splitting MVP.

**Comment by sixolet** [comment]
Yes, I want to be able to type something like `kn service rollback foo foo-asdf` and have that work.

Vote for this by giving this comment a 👍

**Comment by sixolet** [comment]
No, whatever surface that we use for generic traffic splitting is enough for MVP.

Vote for this by giving this comment a 👍

**Comment by sixolet** [comment]
... Further discussion below.

**Comment by toVersus** [comment]
I definitely want this rollout/rollback commands in kn for the usage in CD jobs, but in terms of MVP I think it should reside on the official plugins.

**Comment by zhanggbj** [comment]
I think users can benefits a lot from an opinionated and separate rollout with simpler syntax, and I think this should be part of `post-MVP`,  for `MVP`, we can use generic traffic splitting.

**Comment by navidshaikh** [comment]
Settling on MVP design of UX for CLI should simplify how to represent these workflows conveniently on CLI, this should go post-MVP.

**Comment by maximilien** [comment]
I could go either way. I agree with @toVersus that it could be added as a plugin and then merged in later.

**Comment by navidshaikh** [comment]
MVP is in, closing this and other poll issues.
