### ISSUE TITLE
Gitops mode

### ISSUE THREAD

**Issue by sixolet** [knative/client#30]
Let's have a mode where you can provide a directory instead of a server to connect to. Instead of modifying objects on the server, `kn` will modify yaml files in the directory instead, for the `kubectl apply -f` pleasure of your friendly local CI/CD system.

**Comment by sixolet** [comment]
Considerations:
* Downloading the right objects from etcd to a directory for the first time may another gitops usecase.
* Anything that reads status and uses that information becomes harder or impossible (ex, locking revisions to a container digest)
* Keeping only the "interesting" fields might make the directory easier to use.

**Comment by cppforlife** [comment]
> Let's have a mode where you can provide a directory instead of a server to connect to

im somewhat skeptical that this would be that useful if users are using gitops workflow (== more familiar with yamls). what commands do you think will benefit from this?

**Comment by nimakaviani** [comment]
throwing this here since it was discussed during today's call:

knative yaml generator
https://github.com/julz/knightrider

**Comment by itsmurugappan** [comment]
@rhuss @navidshaikh i think this is the issue we discussed in the last wg. For implementing this am planning to take the below approach, please let me know if this is good

- Implement knclientinterface to work on local directory
- change this line in all commands to return the appropriate client based on cmd flags
```client, err := p.NewServingClient(namespace)```

**Comment by rhuss** [comment]
@itsmurugappan sorry for the late reply, but this sounds like a good strategy. I don't think you have to implement every method, only those that are needed for this functionality. Also the file name should then be part of that new implementation's struct. 

Also I learned this trick today (thanks to @markusthoemmes ):

> If you have a big interface to implement but only call a few functions, you can define the struct like this:
```
type mock struct {
  my.Interface
}
```
It'll implement all functions with nil-pointer function calls. Then you only have to implement the functions your test actually calls

**Comment by rhuss** [comment]
(sorry closed by accident)
