### ISSUE TITLE
Restructure E2E test suite

### ISSUE THREAD

**Issue by mgencur** [knative/client#301]
## In what area(s)?

Structure of the E2E test suite

## Ask your question here:

Should we use a different director/file/test structure for the E2E tests?
Let me propose some changes which we briefly discussed with Navid:
* create the following folders in test/e2e folder which would hold specific tests for these different kinds of objects/commands: service, revision, route.
* place service_options_test.go in the service folder
* move revision_workflow_test.go to the revision folder and rename it to something that doesn't include "workflow" in the name; IMO, there's nothing like a "revision" workflow. Workflows show be defined at a higher level and related to goals that the end user wants to achieve: basic, advanced, trafic_split, etc.
* keep basic_workflow_test.go in test/e2e folder or move it to a new subfolder called "workflow"? 
* pull out sub-tests which are not really basic ones from the basic workflow and place them in a more specific test file

Example:
```
test/e2e/basic_workflow_test.go
test/e2e/service/service_options_test.go
test/e2e/revision/revision_test.go
test/e2e/route/..
test/e2e/env.go
test/e2e/e2e_flags.go
test/e2e/...
```

Note: I think it is good to keep some workflows at the top level because they're nicely showing the basic usage of kn which includes invocations of different kn commands, not just specific to service or revision.

**Comment by navidshaikh** [comment]
@mgencur 

> move revision_workflow_test.go to the revision folder 

As you mentioned, just re-group the mentioned file's tests into specific tests under `revision` folder, and remove `revision_workflow_test.go` file altogether.

> keep basic_workflow_test.go in test/e2e folder or move it to a new subfolder called "workflow" ? 

+1 for moving the workflows under `workflow` directory, we could then add more there as we develop.
