### ISSUE TITLE
kn and Cloud Run fully managed

### ISSUE THREAD

**Issue by steren** [knative/client#303]
Classifications:
/kind feature
/kind proposal

Cloud Run (https://cloud.run) is an implementation of the knative/serving API specification and runtime container contract on top of Google Cloud's serverless stack.

I could not find in the `kn` docs how to configure `kn` to manipulate Cloud Run resources. I propose that we ensure `kn` works with Cloud Run and with other potential future implementations of the knative/serving spec.

The Cloud Run control plane:

* currently implements portions of the Knative/serving  API spec (accepting both `v1alpha1` and `v1beta1` shapes, but returning `v1beta1` shape under a `v1alpha1` endpoint at the moment),
* is using the same [authentication mechanism as other Google APIs](https://developers.google.com/identity/protocols/OAuth2),
* does not expose any underlying Kubernetes resources,
* does not support write operations on KRoute and KConfigurations.
* supports `GET`, `POST` and `PUT`, but does not support `PATCH` as far as I know.
* is documented [here](https://cloud.google.com/run/docs/reference/rest/)

For example, to manipulate services in the region `us-central1` in GCP project `my-project`, the following URI should be used: `https://us-central1-run.googleapis.com/apis/serving.knative.dev/v1alpha1/namespaces/my-project/services`

I am the Product Manager for Cloud Run. I hope to find time to contribute, but my experience is limited to a single digit number of Go programming hours (maybe one day I'll work on a JS client :)

**Comment by duglin** [comment]
What kind of stuff are you looking for? Once you have your CLI environment (ala `kubectl`/KUBECONFIG) setup to point to your cluster, `kn` should just work.

**Comment by rhuss** [comment]
>     * only support write operations on KServices (KRevisions, KRoute and KConfigurations are read-only)

I understand that Configuration and Routes are fully managed within a Service, but how can you clean up Revisions in Google Cloud Run ? (i.e. delete a revision). This is something that kn supports via `kn revision delete`.

**Comment by rhuss** [comment]
kn use the go API of knative-serving as entry point (which also can be considered as part of the API contract or an implementation of that). The entry point is https://github.com/knative/serving/blob/03b04365f0c9f552298436012a911ce3a32cc3bf/pkg/client/clientset/versioned/typed/serving/v1beta1/serving_client.go#L58 which takes a [rest.Config](https://github.com/kubernetes/client-go/blob/579ad46bdcb9f824edd6ecc0af919cc3aa7acd83/rest/config.go#L52-L130) as argument. This configuration contains all connection parameters (including authentication). So if the Cloud Run authentication can be mapped to this struct, then it should be no issue to connect kn to Cloud Run.

We then just have to specify during startup whether to pick up the configuration from `~/.kube/config` or from some other space.

@steren Do you think the google authentication can be mapped to this rest config ?

**Comment by steren** [comment]
> What kind of stuff are you looking for? Once you have your CLI environment (ala kubectl/KUBECONFIG) setup to point to your cluster, kn should just work.

This file is a `kubectl` construct that is Kubernertes specific. As I mention, Cloud Run does not rely on any Kubernetes cluster and expects the authentication to be based on OAuth 2 on a given URL endpoint. In my opinion, well behave Knative clients should not force users to use `kubectl/KUBECONFIG` as this is not in the Knative spec.

> but how can you clean up Revisions in Google Cloud Run

My bad, we allow DELETE on Revisions (but it's not a common use case).

> Do you think the google authentication can be mapped to this rest config ?

Yes, I would think so. Now it's only a matter of picking up the right credentials from the environment.
Most Google Client libraries or SDKs look for the presence of a `GOOGLE_APPLICATION_CREDENTIAL` env var that points to a json keyfile (see [instructions to set it up](https://cloud.google.com/docs/authentication/getting-started)). Adding support for this env var to `kn` would solve authentication for Cloud Run users

**Comment by duglin** [comment]
> In my opinion, well behave Knative clients should not force users to use kubectl/KUBECONFIG as this is not in the Knative spec.

Yes and no. The "K" in Knative does mean "something" :-)  and the APIs of Knative are from Kube - even if the resource model is Knative specific.  But, having said that, one of the things we've talked about in the past is that a Knative user, when they do have to switch between `kn` and `kubectl`, don't have to deal with the pain of doing a configuration twice when switching cluster - just as an example.

So, to me that means that we could add some Kn-specific config data in Kn's config that tells it where to find the server, but if that info is not there then it should default to what `kubectl` looks for.  IOW, allow for a non-Kube endpoint but default to Kube when nothing special is configured.

**Comment by rhuss** [comment]
@duglin agreed, but I would be also totally ok, that when an env var `GOOGLE_APPLICATION_CREDENTIAL` is set, that we take that as a switch to google run (as well as for any other implementation of Knative, as far there will be any more ;-).

Typically what we can do in such a situation is to build up a chain of RestConfigHandlers which have an `isActive()` method which probes for certain environment variables and filesystem-specific spots. As soon as the first one kicks in, it takes over to create the connection configuration (e.g. via `getRestConfig()`. Fallback will be always `~/.kube/config`.

**Comment by rhuss** [comment]
Said that, of course, a pluggable extension mechanism for the authentication stuff would be even better. It also depends on what ceremony needs to be done to get to the tokens.

**Comment by pmorie** [comment]
What does google auth in kube use? I was under the impression that the kubeconfig configured an exec hook to run `gcloud auth login` or something like that.

**Comment by mattmoor** [comment]
I think I agree with much of the sentiment in this thread.  Cloud Run shouldn't need anything special here (vs. say GKE), it should support the same `kubeconfig`-style authentication as basically all other K8s clients (including `kn`), which is a fairly flexible credential helper hook.

I believe GKE sends oauth2 access tokens, so Cloud Run shouldn't be that different there.  One notable way GKE is odd is that it needs:
```
	// Uncomment the following line to load the gcp plugin (only required to authenticate against GKE clusters).
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```
IMO this is probably a better integration point than `kn` for establishing broad tooling compatibility.


Documenting the use of `kn` with Cloud Run belongs in product documentation, not in OSS documentation.

My $0.02

**Comment by duglin** [comment]
I didn't notice we have stuff like that:  https://github.com/knative/client/blob/59b2855d04c95cd747ed733136b6f6343db44cfe/pkg/kn/core/root.go#L35

I really question why we have this. Seems pretty inappropriate for an OSS project.

**Comment by rhuss** [comment]
> I really question why we have this. Seems pretty inappropriate for an OSS project.

That is part of client-go, which itself is under the Kubernetes / CNCF umbrella. These auth packages add support for multiple authentication mechanisms, not only GCP but also [Open ID connect](https://github.com/knative/client/blob/59b2855d04c95cd747ed733136b6f6343db44cfe/pkg/kn/core/root.go#L36). Not sure why this should be inappropriate. kn does not import anything from GCP directly. This was the case in a former version but has been removed.

**Comment by duglin** [comment]
I just prefer a mechanism that didn't hardcode one company's auth mechanism into the code. I would prefer a pluggable architecture that allowed for them to be added via an extension, plugin, something... otherwise each time a new one comes along it requires a change to the codebase and approval from the maintainers. Moving it out of the code puts everyone on an even footing.

**Comment by rgregg** [comment]
Adding my $0.02, `kn` should be vendor neutral implementation, with enough configuration options that vendor-specific things (like authentication) could be configured to make `kn` useful in those vendor-specific scenarios. The exact form that takes seems like a decision we should make on a case-by-case basis, but if the extensions end up looking vendor-specific, that's also bad.

I would not expect that `kn` would "know" about Cloud Run or Cloud Run on GKE. Documentation can provide details about how to configure `kn` to work with their service. Unlike the documentation for how to install Knative in a variety of vendor platforms, I would not expect that Kn documentation tells you how to configure it to work with vendor-specific Knative implementations, but in the product-specific documentation (e.g. 'Using kn with Cloud Run' should be in the Cloud Run docs, 'Using kn with OpenShift' should be in the OpenShift docs)

**Comment by steren** [comment]
The ["Connecting to your cluster" section](https://github.com/knative/client/blob/master/docs/README.md#connecting-to-your-cluster) of the kn Getting started already links to many vendor-specific instructions.
Assuming that the Cloud Run official docs will have a page for "Using Cloud Run with `kn`", why not link to it the same way?

**Comment by rgregg** [comment]
Linking to those docs from here isn't a concern from my perspective, I just don't think the Knative community should be responsible for maintaining those docs.

**Comment by sixolet** [comment]
Regarding Doug's concerns: 
* Usefulness trumps purity here.
* I'm happy to include the plugin to authenticate to anything that's in k8s.io/client-go
* It'd be very nice to have a pluggable architecture and the ability to manage and easily download auth plugins and get them installed without very much likelihood of user error, but I don't think we live in that world. We live in the world where you can build a "sanitized" version of `kn` by commenting out any auth plugin lines though.

**Comment by sixolet** [comment]
To make `kn` connect to Cloud Run Fully Managed right now, open up your kubeconfig in an editor. You'll be adding to each of `clusters`, `users`, and `contexts`.

## Clusters

Add an entry to `clusters` per region you want to connect to:
```yaml
clusters:
  - name: cloud-run-managed-us-central1
    cluster:
      server: https://us-central1-run.googleapis.com
```

## Users
```yaml
users:
  - name: gcloud-token-access
    user:
      auth-provider:
        config:
          access-token: ya29.==
          cmd-args: config config-helper --format=json
          cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
          expiry: "2015-01-01 12:00:00"
          expiry-key: '{.credential.token_expiry}'
          token-key: '{.credential.access_token}'
        name: gcp
```
Note that this is modeled on the entry `gcloud` can generate to connect to GKE. Make sure to replace the path to `gcloud` with your correct path to `gcloud`. Yes, you'll need `gcloud` installed, at least for now.

## Contexts
```yaml
contexts:
  - name: cloud-run-myproject-us-central1
    context:
      cluster: cloud-run-managed-us-central1
      user: gcloud-token-access
      namespace: myproject
```
Adjust to make sure you replace `myproject` with your actual project name, and make sure you point to the right regions. Make a context per region/project you'll want to connect to.

##Putting it all together
Edit the `current-context` field in your kubeconfig to be one of the contexts you just created. 

Try `kn service list`.

**Comment by sixolet** [comment]
And, since the `GOOGLE_APPLICATION_CREDENTIALS` path just does a jwt oauth2 flow with the json file it finds, I see no problem with allowing a `--oauth-jwt-config` option (note: not specific to Google) alongside kubectl to connect. I'll look at drafting up a PR.
