### ISSUE TITLE
Kn plugins integration test

### ISSUE THREAD

**Issue by maximilien** [knative/client#308]
## In what area(s)?

Kn plugins

Classifications:

/kind feature

## Describe the feature:

Now that #249 is merged we need to have a separate integration test (IT) for that feature. There is a lot to test. As a start, let's add this:

1. simple plugin execution of a BASH and executable plugin in
  a. `--plugins-dir`
  b.  $PATH
2. finding plugin in both `--plugins-dir` and $PATH
3. verifying plugin overshadowing
4. verifying plugin cannot override a core command

---
There will be more to add to these ITs as plugins matures and more features are added.

**Comment by maximilien** [comment]
I’ll push this once #313 is merged since I need to change some of the output tests.

**Comment by navidshaikh** [comment]
@maximilien +1

**Comment by maximilien** [comment]
Need some integration tests. Latest issues found in #411 showed this is needed. Making this my top priority with #414 and then #320

/cc @rhuss

**Comment by maximilien** [comment]
Finally, getting back to this after our long unforseen delays. Fix one issue #468 which was blocking my WIP on this.

**Comment by maximilien** [comment]
Now that #468 is merged (yeah). Getting back to this to submit it soon. Finally.
