### ISSUE TITLE
Consider supporting multiple NAMEs on some commands

### ISSUE THREAD

**Issue by duglin** [knative/client#317]
## In what area(s)?

Classifications:
/kind feature
/kind proposal

## Describe the feature:

It would be nice if some commands supported multiple resource names to make life easier for people. For example, I was cleaning up my env and I tried this:
```
$ kn service delete echo helloworld foo
requires the service name.
```
and it died because it wasn't expecting more than one service name. It would be nice if we could support multiple NAMEs on certain commands where it makes sense.

It's also kind of an odd error message right now. I would have expected something more like `only one service name is allowed`, not a message implying I didn't specify any at all.

**Comment by navidshaikh** [comment]
This is needed, I have to clean my dev environment, it needed multiple `kn service delete` commands.

I think we should implement this for `kn service delete` as well as `kn revision delete`
along with say `--all` option to delete all the services or revisions in current namespace.

> It's also kind of an odd error message right now. I would have expected something more like only one service name is allowed, not a message implying I didn't specify any at all.

This is bug.

**Comment by wslyln** [comment]
@daisy-ycguo  just wanted to double check you're not working on multiple names on revision delete

I'd be up to work on it revision delete and trigger delete.

I checked the rest of the commands in kn and it doesn't seem like there are any others that multiple arguments really make sense. (I guess there might be a case of updating multiple services at a time, though it'd be pretty tricky)

**Comment by duglin** [comment]
/remove-lifecycle stale
@daisy-ycguo  @wslyln were one of you going to work on this?

**Comment by Kaustubh-pande** [comment]
I'd like to work on this issue.
/assign

**Comment by duglin** [comment]
#1217 doesn't actually address this (at least I don't think it does)

**Comment by duglin** [comment]
I missed that this was done before #1217 at least for delete
/close
