### ISSUE TITLE
Polling watcher option

### ISSUE THREAD

**Issue by sixolet** [knative/client#325]
Right now kn watches resources as they're getting `Ready` using a watch request. Watch is only SHOULD in the Knative API, so we should support a polling normal GET too, as an option. It should be settable both at the command line and in the kn config file.

**Comment by rhuss** [comment]
> Right now kn watches resources as they're getting `Ready` using a watch request. Watch is only SHOULD in the Knative API, so we should support a polling normal GET too, as an option. It should be settable both at the command line and in the kn config file.

Is there a way to probe whether watch is supported ?

**Comment by sixolet** [comment]
Hmm. I can imagine "try watch, fall back to polling if it doesn't work". I know what one implementation does is (correctly) 400, which we can catch.
