### ISSUE TITLE
Adding annotation 

### ISSUE THREAD

**Issue by VeerMuchandi** [knative/client#327]
## In what area(s)?
`kn` command line feature

Classifications:
> /kind feature

## Describe the feature:
Add `--annotation` option to `kn` CLI. This allows specific underlying implementations based on annotations to be supplied what they need using kn. Currently we are having to apply annotations by updating the service after it is created.

`kn service create myservice --annotation=sidecar.istio.io/inject="false"` is an example

**Comment by rhuss** [comment]
@VeerMuchandi Should this annotation be added to the Service itself, or the revision's template so that it ends up on the Pods created ? Or on both ?

**Comment by VeerMuchandi** [comment]
Adding it to the service will apply it to the pods. That is what I am doing
currently. Does `kn` not create a service by default or is it breaking up
and creating all the objects?

**Comment by rhuss** [comment]
`kn` just creates and manages the service, so this should be safe then.

**Comment by rhuss** [comment]
As said in https://github.com/knative/client/issues/328#issuecomment-519039799 the Service labels/annotations defined in the Service's metadata: are not propagated to the revision template used for creating pods. These are different pair of shoes.

**Comment by SugandhaAgrawal** [comment]
Jumping in here, the current implementation on Knative serving 0.7 and above allows to enable request and limit on memory and cpu for Queue proxy via annotations. - https://github.com/knative/serving/issues/4134
https://github.com/knative/serving/pull/4151 

Specific use case is in a multi-tenancy scenario where namespace based resource quota application is to be leveraged, there is no default set for Queue proxy on limits and hence the creation of service fails. 

Providing the capability to define annotation over the client would support the use case.

**Comment by VeerMuchandi** [comment]
I see that `--label` option has been added as of `Version:      v20190903-6790961`. Are there plans to add `--annotation`?

**Comment by rhuss** [comment]
Yes, sure. It makes much sense to have both implemented in a similar fashion. Not sure though whether it will make it to 0.8.0 but as @navidshaikh added it to the 0.8.0 milestone, its likely to happen anytime soon ;-)
