### ISSUE TITLE
Adding label

### ISSUE THREAD

**Issue by VeerMuchandi** [knative/client#328]
## In what area(s)?
`kn` command line option

Classifications:
> /kind feature

## Describe the feature:

Ability to add user defined labels to the service and its artifacts. Certain implementation specific features depend on labels. Being able to add a label with `kn` will avoid additional overhead of unnecessarily updating the service (and avoiding a new revision) just for adding a label.

Example
`kn service create myservice --label=app.kubernetes.io/part-of=mygroup`

**Comment by rhuss** [comment]
Same question as for #327: Where to add the labels ? Service, Pod or both ?

Regardless what the behaviour must be consistent regarding to labels and annotations.

**Comment by VeerMuchandi** [comment]
Applying to knative service will trickle down to the pods as well.
Here is an example of labels and annotations applied to the service.

https://raw.githubusercontent.com/VeerMuchandi/catalystdemo/master/serverless/todo-serverless.yaml

**Comment by markusthoemmes** [comment]
@VeerMuchandi I don't think that's accurate. Your example has the labels in the revisionTemplate, not as part of the Service's ObjectMeta itself. I don't think labels in ObjectMeta propagate down.

**Comment by VeerMuchandi** [comment]
Thanks Markus

I understood the question differently. I thought configuration, revision
and route were being created separately based on the question.

I meant it was part of the service's yaml and yes it is part of the
spec.template.metadata and this applies both to labels and annotations.
