### ISSUE TITLE
Integration test flake "service-account default not found"

### ISSUE THREAD

**Issue by rhuss** [knative/client#329]
There is currently an integration test flaking popping up from time to time with an error:

```
Running 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests2'...
Failed to successfully execute 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests3': Execution error: stderr: 'RevisionFailed: Revision "hello-qj4nm" failed with message: Unable to fetch image "gcr.io/knative-samples/helloworld-go": serviceaccounts "default" not found.
' error: 'exit status 1'FAIL	github.com/knative/client/test/e2e	1.024s
```

See e.g. https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_client/312/pull-knative-client-integration-tests/1157313391212105729/build-log.txt

It smells like an issue in the cluster setup but not so much like a race as it happens after some successful image pulls in those tests.

@adrcunha do you have any idea what the cause could be ?

**Comment by adrcunha** [comment]
This doesn't sound like a cluster setup to me. A few tests passed before the one failing, and the service account was (correctly) set before the tests. Since this is a flake, my guess is that one of the tests is doing some sort of teardown and thus causing  `TestRevision/create_hello_service_and_return_no_error` to fail.

```
=== RUN   TestRoute/create_hello_service_and_return_no_error
Running 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests4'...
=== RUN   TestServiceOptions/create_and_validate_service_with_concurrency_options
Running 'kn service create svc1 --image gcr.io/knative-samples/helloworld-go --concurrency-limit 250 --concurrency-target 300 -n kne2etests1'...
=== RUN   TestBasicWorkflow/returns_no_service_before_running_tests
Running 'kn service list -n kne2etests0'...
=== RUN   TestService/create_hello_service_duplicate_and_get_service_already_exists_error
Running 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests3'...
=== RUN   TestBasicWorkflow/create_hello_service_and_return_no_error
Running 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests0'...
=== RUN   TestRevision/create_hello_service_and_return_no_error
Running 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests2'...
Failed to successfully execute 'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests3': Execution error: stderr: 'RevisionFailed: Revision "hello-qj4nm" failed with message: Unable to fetch image "gcr.io/knative-samples/helloworld-go": serviceaccounts "default" not found.
' error: 'exit status 1'FAIL	github.com/knative/client/test/e2e	1.024s
```

**Comment by rhuss** [comment]
Yes, it looks like as every of those test setup a test namespace and tear it down after the test.

After its the first test of `TestRevision`, its the first test right after the namespace is setup. I guess this is just a race between the first test running and the namespace not fully setup. Let me add some seconds wait to this setup and see how it goes.
