### ISSUE TITLE
Add a command to install Knative

### ISSUE THREAD

**Issue by bbrowning** [knative/client#33]
It would be awesome if `kn` provided an easy way to install Knative. Even more awesome if it could work with a real Kubernetes cluster or let me choose to spin up Knative locally with minikube.

**Comment by cdrage** [comment]
@bbrowning 

`knctl` already has this and it work's well: https://github.com/cppforlife/knctl/blob/master/docs/basic-workflow.md

However.. wouldn't this be a difficult part of the knative client to maintain? Few points:

- Every cluster is different, and even from experience I've had issues configuring Istio / Knative cloud vs bare metal
- If we allow installation of `knative` is it implied that Istio is already installed? Or do we *also* install Istio?
- Service accounts, each cluster has diffferent permissions / what they allow to be modified. Would we install RBAC permissions ourselves?

**Comment by kameshsampath** [comment]
@cdrage  - can we not atleast do it for minikube ?

**Comment by bbrowning** [comment]
I would agree that targeting only minikube initially would simplify a lot of the variables. We can setup a new minikube profile, start a fresh minikube VM, install Istio, install Knative, and do a bit of tuning out of the box to ensure things fit in a reasonably sized minikube instance.

**Comment by cdrage** [comment]
@kameshsampath Istio is **massive** and requires A LOT of RAM to function. I've had to upgrade my homelab from 8GB to 32GB to even use it and when it does, it takes about 12GB.

Integrating it into Minikube / Minishift would be an option... but obviously we'll have to indicate to the user that you need a beefy machine to use it... enable it as an addon maybe?

**Comment by kameshsampath** [comment]
@cdrage if you install Istio from maistra then there are lot of components which our Knative OLM operators scales down after install. @bbrowning  correct me if am wrong. I do my every day dev evangelism stuff with 8 GB minikubes.

**Comment by sixolet** [comment]
Installing Knative is not part of the Knative API, and won't be. This is going to be an operator concern, not a developer concern. I'm closing this in the Client repo, we can make another similar bug in any operator repo as it develops.

**Comment by bbrowning** [comment]
@sixolet I understand your position. I created this issue based on feedback that there should be a very simple way to get Knative up and running on minikube, and minikube is not an operator in the same sense as cloud providers.

But, I'd concede that the most appropriate thing to do is to just simplify the `kubectl`-based install as much as possible for minikube.
