### ISSUE TITLE
Add "kn source" create & update typed builtin

### ISSUE THREAD

**Issue by rhuss** [knative/client#334]
## In what area(s)?

Eventing

## Describe the feature:

As [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) we suggest implementing all use cases for kn source command as this is the smallest required action for connecting a given Knative service to an event producer. It does not require any other parts of Knative eventing but only Knative sources installed.

The MVP should contain built-in support for 

* CronJobSource
* ApiServerSource
* ContainerSource

For the suggested command line syntax, please refer to [Sources](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit#heading=h.8yhces3mysbr) in the proposed spec.

### CronJobSource

```
kn sources cron create mycron --schedule "* * * * 5/*" --data "ping" --sink myservice

kn sources cron update mycron --schedule "* * * * 5/*"
kn sources cron update mycron --remove-sink

kn sources cron delete mycron

kn sources cron list mycron
```

### ApiServerSource

```
kn sources api-server create myapiserver --resource pod --resource deployment --mode ref

....
```

### ContainerSource

```
kn sources container create myimporter --image gcr/test-importer --arg firstArg --arg secondArg --env var1=value1 --env var2=value2

....
```

* [Overview slides](https://docs.google.com/presentation/d/1rSoclSuzV_QAyyvD6jIpbOfN-OrFvUyC7yWI54SfnE0/edit?usp=sharing)
* ~~[Knative eventing support in Kn - V3](https://docs.google.com/document/d/19MO8JBPU5JrBthwI5jYs_V0zzgMtTmiOHou6w_T04XI/edit?usp=sharing)~~ replaced ny [Knative eventing support in Kn - Source & Trigger - V4](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit?usp=sharing)

**Comment by rhuss** [comment]
If we want to go this route, we should open three different issues, one for each importer.

**Comment by rhuss** [comment]
The idea behind this proposal for an MVP is to get quick feedback on the eventing direction based on something which can be already implemented. 

This for sure does not rule out the other use cases in https://docs.google.com/document/d/19MO8JBPU5JrBthwI5jYs_V0zzgMtTmiOHou6w_T04XI/edit?usp=sharing , including the auto-creation of importers by a lookup to the importer registry as suggested in https://github.com/knative/eventing/issues/1550 (and with implementation issues in https://github.com/knative/eventing/issues/1554 and https://github.com/knative/eventing/issues/1555). 

It's just a start which can be implemented now and which is very likely to survive Knative eventing changes until eventing becomes GA.

**Comment by daisy-ycguo** [comment]
@rhuss how about this :
```
kn importer create mycron --type cronjobsource --schedule "* * * * 5/*" --data "ping" --sink myservice
kn importer create myapiserver --type apiserversource --resource pod --resource deployment --mode ref
kn importer create myimporter --type containersource --image gcr/test-importer --arg firstArg --arg secondArg --env var1=value1 --env var2=value2
```

Just want to make the command line simple. 

Or even simpler:
- if the parameter contains --image, it will create a containersource importer.
- if the parameter contains --schedule, it will create a cronjobsource importer.

**Comment by rhuss** [comment]
Yes, that was the original thought to use a `--type`. 

However, for playing nicely with our current plugin implementation, it would be very beneficial if the type could be a regular argument.

For example, let's assume we want to introduce a `GoogleCalendarSource` which picks up events from Google's calendar as they come in. This is a totally custom source, so we need to add a client plugin (note, this is not needed when using the importer registry, but that access is connected to another command anyway)

Plugins are weaved into the command hierarchy based on their name. E.g. when we introduce a `kn-importer-gcal` plugin, then this will be called for every call to `kn importer gcal`. This plugin then can have custom options specific for the google calendar source (like tokens, and calendar names, ..). Also,  this plugin needs to support the CRUD commands (create, update, delete, ...).

So it's more a technical reason, but I think it also fits nicely in the UX. The alternative would be to introduce special 'importer plugins' (with a different naming scheme or storage location), which then the importer command would call-out based on the `--type` option. But this makes plugin management more complex, so I think having a second argument specifying the importer type is better.

For the builtin-importers this implies that they are all subcommands from the "importer" command and live in their own packages. This results also in a nice modularization within the client (I'd expect quite some importers included that way).

Another reason to make the type more prominent is, that only the combination "type" + "name" is unique. E.g. you can have importers of the same name but different type as they translate to different CRDs. Therefore both should be part of the command (not only create, but also update & delete, to uniquely identify an importer)

Plugins are needed for importers that we do not directly support. This _open world_ is also the reason why we should not put semantics into the options.

@daisy-ycguo does this make sense ?

**Comment by rhuss** [comment]
I added an example in #336 where I think the typed plugin-based approach is superior to a generic importer instantiation over an importer registry.

**Comment by daisy-ycguo** [comment]
> @daisy-ycguo does this make sense ?

Yes, if it's easy for implementation, I support.

One more concern, if only reading from the command line itself, e.g. `kn importer cron`, it doesn't hint any relationship with `Eventing`. Can we do:
```
kn event-importer cron-job create ...
kn event-importer container create ...
kn event-importer api-server create ...
```
?

**Comment by rhuss** [comment]
@daisy-ycguo Tbh, I think the less to type the better and also I think 'importer' is distinct enough. We could still use 'source' (instead of 'importer') as there seems still to be some discussion in the eventing group whether this is the proper abstraction for users who do not really care about the distinction between "importer" and "event producer", just want a source for events. But I wouldn't go for "event-importer" as its too much to type and doesn't provide any value add.

For similar UX reasons I would opt still for simple names, e.g. "cron" over "cron-job" as I don't think there needs to be a direct relationship between the CRD kind and the name used in the CLI. But I don't have strong opinions here, so would be ok for a "cron-job" type as well.

**Comment by daisy-ycguo** [comment]
I'm working on the prototype of apiserver importer: https://github.com/daisy-ycguo/client/tree/apisource . It depends on PR https://github.com/knative/client/pull/357. 
@rhuss Let me know when it is ready to create a PR for apiserver importer.

**Comment by n3wscott** [comment]
fyi, https://github.com/knative/eventing/issues/1857 reverts back to calling these things `sources`.

**Comment by rhuss** [comment]
Let's close this issue in favour of more specific issues around sources, reflecting the [specification](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit#bookmark=id.2et92p0)
