### ISSUE TITLE
List revision tags from service traffic block

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#335]
Classifications:
> /kind feature

## Describe the feature:

A user might need to know the traffic target tags assigned to revisions to perform traffic splitting related operations.

For example: I want to update my traffic target tags for revisions of a service and I want to list out the current state. Present `kn revision list` command doesn't show the tags associated with revisions. This could be an option `kn revision describe` (but it would list only for one revision and user will have to invoke multiple `kn revision describe`)  OR `kn service describe`.
However, do we want to print the `TAGS` column in `kn revision list` which will enlist the comma separated tags assigned for this revision in service traffic block?

**Comment by rhuss** [comment]
I think its a good idea, if there is a 1:1 mapping. This would be very helpful, maybe put that column close to the service name column

**Comment by navidshaikh** [comment]
>  if there is a 1:1 mapping

I think its not, case where a revision has multiple tags in traffic, we'll just print the available tags comma separated. (Its just that it would shift the other columns right and make the TAGS column wider for rest of revisions listing)

> maybe put that column close to the service name column

Yup, I thought same. +1

**Comment by navidshaikh** [comment]
The output in `list` command fits better if there is 1:1 mapping, cases where multiple values can be printed should be shifted to `describe` commands.
/close
