### ISSUE TITLE
Multipurpose Camel source plugin

### ISSUE THREAD

**Issue by rhuss** [knative/client#336]
## In what area(s)?

Eventing

## Describe the feature:

This proposal is based and depends on #334 where kn plugins are used for providing support for custom sources with custom options.

The architecture described in #334 is especially well suited for multipurpose sources like the [Camel source](https://github.com/knative/eventing-contrib/tree/master/camel/source). 

The Camel source supports hundreds of different endpoint to connect to with many many different options. Using this kitchen-sink operator with a source registry like described in https://github.com/knative/eventing/issues/1550 is very challenging, not only because of the sheer amount of options but also because they can be arbitrarily complex like e.g. this [sample connector](https://github.com/knative/eventing-contrib/blob/master/camel/source/samples/source_timer_flow.yaml). For me its not clear how the translation from flat key-value properties from the CLI can translate automatically to deeply nested source CR (not only for this case, btw).

With the approach laid out in #334 (and the associated proposal), a single camel client plugin can provide a smooth and typed interface for creating camel based operators.

The idea is to have a single `kn-source-camel` plugin with symlinks to this binary for every supported camel connector. E.g.

```
kn-source-telegram -> kn-source-camel
kn-source-twitter -> kn-source-camel
kn-source-timer -> kn-source-camel
.....
```

(a command `kn-source-camel install` could help in a fan-out of these symlinks).

Then when a user calls

```
kn source telegram create --token 13abcsdcdscw
```

the following will happen:

* `kn` detects this a plugin and looks up and calls `kn-source-telegram`
* `kn-source-telegram` when checks its name and extracts the type "telegram"
* It looks up in its internal handler list the handler for "telegram" and use the supported options to parse the remaining command-line (e.g. the `--token` is specific for the "telegram" handler, a `--period` options would be specific to the "timer" handler"
* The handler then creates a custom resource like in this [sample](https://github.com/knative/eventing-contrib/blob/master/camel/source/samples/source_telegram.yaml) and sends it to the server.

That way the user gets a smooth and seamless user experience (e.g. `kn source list --types` would should all supported importer types, a `kn source telegram create --help` would show all options allowed for this type).

This can not be achieved with a more generic approach where the CR is automatically created based on a schema mapping (at least not for such complex importers like the camel one).

@nicolaferraro would this make sense in the context of `kn` client support for the camel-k source ?

[UPDATE: Replaced all references to *importer* with *source* as this is now the canonical name for the event adapters)

**Comment by richterdavid** [comment]
#334 was closed "in favour of more specific issues around sources", but it's unclear what dependencies this issue has on those (unspecified) more specific issues.

Would you please clarify this? Thanks!

**Comment by rhuss** [comment]
We are implementing source support in `kn` on multiple levels:

* Builtin sources that come with Knative eventing itself: PingSource, ApiServerSource, SinkBinding and ContainerSource. Except for ConainerSource this is implemented ('builtin source')
* Source functionality by Plugins. The first source plugin will be a [KafkaSource](https://github.com/knative/client-contrib/issues/9) that is developed in knative/client-contrib. This plugin will also help us to tune the 'contract' between `kn` and the plugins ('plugin source')
* General purpose support by examing CR definitions and providing a CLI user interface for this (we call it 'untyped source' support).

The Camel Source described here is meant to be realised as a 'plugin source' and ideally can be implemented after we have fleshed out the first sample plugin.

hope this helps.

**Comment by rhuss** [comment]
FYI, we are focussing first on support for so-called [Kamelets](https://github.com/apache/camel-kamelets) which should already cover a decent amount of possible sources. 

cc: @christophd as reference for how we wanted to approach Camel-K support before Kamelets were introduced

**Comment by rhuss** [comment]
As Camel Source are now deprecated, let's close this issue and focus on Kamelet support.
