### ISSUE TITLE
Add docs about the ~/.kn/config config file

### ISSUE THREAD

**Issue by duglin** [knative/client#338]
## In what area(s)?
/kind good-first-issue
/kind doc

https://github.com/knative/client/blob/master/docs/README.md mentions the `kn.yaml`
config file but there are no docs about it. We should document:
- where it needs to live
- it's format (yaml obviously)
- what are the available config flags people can set

**Comment by maximilien** [comment]
I can take this as most of the initial configs comes from plugins and I need to refer to it in the plugins docs #395 I am finishing writing now.

/assign @maximilien

**Comment by maximilien** [comment]
Hi, all, working on this issue now to submit PR in next day or so. Any comments appreciated in terms of configuration values and style. Otherwise, I will make it up based on the two config values I know we have for the plugin work. More soon. Best,
