### ISSUE TITLE
Add some sample / example plugins 

### ISSUE THREAD

**Issue by maximilien** [knative/client#349]
## In what area(s)?

Kn plugins

> /kind feature

## Describe the feature:

Now that Kn supports plugins, it would be good to have some sample / example plugins in the Kn repo. They should be small but useful and ideally in a few different languages and of different features to show what can be done with plugins.

Eventually, as / if we decide to create plugin-specific repositories or collection thereof, then these can be moved there.

**Comment by maximilien** [comment]
Hi, I have a few simple, useful, and fun plugins in BASH and Golang that I can push. I'll also do one in Python to show different languages.

Unless I hear otherwise, I will push these early next week. So please comment if you don't like the idea of sample / example plugins here. Thinking of putting something like:

```bash
plugins\samples\bash\...
               \golang\...
               \python\...
               \ruby\...
```

/assign @maximilien

**Comment by navidshaikh** [comment]
@maximilien : IMO, One sample plugin (say bash one) is fine to keep with client repo. If we are to create sample plugin per language then IMO its better to create a sample-plugin-repository elsewhere (say under your namespace) and linking it from docs.

**Comment by maximilien** [comment]
@navidshaikh OK. I am also looking to add structure and the sample plugin to the upcoming `client-contrib` where other "real" plugins contributed will also reside.

cc: 
@sixolet (for `client-contrib`) 
@zhanggbj (for `kn-admin`) and 
@zhangtbj (for `kn-migration` and `kn-build`)
