### ISSUE TITLE
Minimum golang version for kn

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#353]
I am running Fedora 29 and golang versions as below
```
13:37 ➜  client git:(fix-docs)  cat /etc/redhat-release 
Fedora release 29 (Twenty Nine)
13:38 ➜  client git:(fix-docs)  rpm -q golang
golang-1.11.11-1.fc29.x86_64
```

latest master fails to build for me as it requires golang 1.12 for strings.ReplaceAll,
```
13:39 ➜  client git:(master)  ./hack/build.sh 
🕸️ Update
🧽 Format
⚖️ License
📖 Docs
# github.com/knative/client/pkg/kn/commands/plugin
pkg/kn/commands/plugin/plugin_verifier.go:280:12: undefined: strings.ReplaceAll
```

Our docs point 1.11.4 or later, that should be replaced with 1.12.7 or latest (the latest one available https://golang.org/dl/)

**Comment by rhuss** [comment]
fwiw, we could also replace the `strings.ReplaceAll` easily. The question, however, remains, how would we check for 1.11 conformity when all CI is running on 1.12

I wouldn't mind bumping to 1.12 as the minimal requirement so that its aligned with CI.

**Comment by navidshaikh** [comment]
Right.

Thinking from CLI perspective, we should aim at covering most of the users and their platforms,
while the users should be running the latest bits of software, I am not sure asking them to upgrade is a good idea.
