### ISSUE TITLE
Refactor service unit tests to use KnClient mock framework

### ISSUE THREAD

**Issue by rhuss** [knative/client#358]
## Describe the feature:

In order to simplify the maintenance of our tests, existing tests in services should be refactored to use the `MockKnClient` support class. An example of such a test can be found in [`service_create_mock_test.go`](https://github.com/knative/client/blob/master/pkg/kn/commands/service/service_create_mock_test.go)

Ideally all the test classes

* service_create_test.go
* service_list_test.go
* service_describe_test.go
* service_update_test.go

should be rewritten (and the mock sample integrated into service_create_test)

Maybe also add as service_delete_test.go which seems to be missing.

**Comment by itsmurugappan** [comment]
can I help with this ?

**Comment by rhuss** [comment]
@itsmurugappan yes, sure ! Any help is appreciated. Just pick an existing test and create a test in parallel (with a `_mock` in the filename, like in `servuce_update_mock_test`) and port the existing tests over. We will happily review the PR and if approved, we can remove the original test in an additional pull request.

Thanks !

**Comment by itsmurugappan** [comment]
Sure. I will start with it. Thank you!
