### ISSUE TITLE
Discovery and installation of community Kn plugins

### ISSUE THREAD

**Issue by maximilien** [knative/client#397]
## In what area(s)?

Kn plugins

Classifications:

> /kind feature

## Describe the feature:

Kn plugins allow various interesting extensions to the `kn` CLI. They are easy to build and locally manage. However, how is a Kn user able to discover, install, and manage community Kn plugins? 

Ideally the `kn` CLI should have a means to allow some discovery of community plugins as well as a means to install and manage discovered plugins. Perhaps these features are themselves Kn plugins to allow easily addition or removal from a Kn user's machine.

The  Kubernetes `kubectl` community has explored these problems and have created the tool [`krew`](https://github.com/kubernetes-sigs/krew) which is similar to the common MacOS X package manager [brew](https://brew.sh/) which allows easy client-side discovery, installation, and management of packages. In the case of `krew` the packages are `kubectl` plugins.

I propose we explore whether `krew` could be extended to support `kn` and / or we should also create a similar tool for Kn plugins. We should also take this opportunity to explore what other alternatives exist and their level of adoption to make a recommendation to the working group on how best to move forward.

**Comment by sixolet** [comment]
I think the cluster should suggest plugins to install, as I've said before. That way the plugins suggested can be situation-dependent, appropriately.

**Comment by maximilien** [comment]
Yup @sixolet we can have both, no? Server-suggested and repository of plugins that users can discover.

**Comment by maximilien** [comment]
This is still something interesting to pursue so leaving it open as new plugins are being setup in `knative-sandbox` org.

**Comment by maximilien** [comment]
What about using `brew` for that purpose? We could use this issue as a way to discuss. For instance, should there be one `brew` repo for all the plugins or one per plugin?

Cc: @zhanggbj @navidshaikh @rhuss

**Comment by rhuss** [comment]
I would think that all plugins that are part of the _release train_ (i.e. that are released together with `kn`) should share the same brew repository. I suggest creating a repository `knative-sandbox/homebrew-kn-plugins` that host all formulas for the support plugins. Then a user can e.g. install the plugin with

```
brew install knative-sandbox/kn-plugins/admin
brew install knative-sandbox/kn-plugins/source-kafka
```

when then corresponding files are created.

**Comment by maximilien** [comment]
Sounds good to me. Unless someone else is on this already, let me work with @zhanggbj and @zhangtbj to get this done.

Cc: @navidshaikh @itsmurugappan @dsimansk

**Comment by rhuss** [comment]
+1, go ahead. I think the first step is to kick off the process to create that repo.

**Comment by maximilien** [comment]
@rhuss see https://github.com/maximilien/homebrew-kn-plugins 

Not done. Got to fix a bug and move binary to plugin directory but should have a version today.

We also need to create a new sandbox repo or move it to the `homebrew-client` repo.

Anyhow, let’s discuss briefly at WG meeting today.

**Comment by maximilien** [comment]
@rhuss and @navidshaikh can you give https://github.com/maximilien/homebrew-kn-plugins a quick spin? Should be OK to install the `admin` and `source-kafka` plugins v0.21 version.

It should be working but missing the code to create symlink to user's `~/.config/kn/plugins` but otherwise should work. Once the new `homebrew-kn-plugins` repo is ready, I'll move the code there.

cc: @zhanggbj

**Comment by navidshaikh** [comment]
>  can you give https://github.com/maximilien/homebrew-kn-plugins a quick spin? 

lgtm
```
➜  homebrew-kn-plugins git:(master) which kn-admin kn-source-kafka
/usr/local/bin/kn-admin
/usr/local/bin/kn-source-kafka
```

> It should be working but missing the code to create symlink to user's ~/.config/kn/plugins

+1

**Comment by maximilien** [comment]
Can we close this now that we have: https://github.com/knative-sandbox/homebrew-kn-plugins ?

**Comment by rhuss** [comment]
+1 for closing it
