### ISSUE TITLE
`kn version` : Display supported API and version 

### ISSUE THREAD

**Issue by rhuss** [knative/client#404]
## Describe the feature:

Currently the display of `kn version` is a bit misleading:

```
Version:      v20190910-local-a607b16
Build Date:   2019-09-10 09:41:55
Git Revision: a607b16
Support:
- Serving: v0.8.0  v0.7.1
- API(s):  v1alpha1
```

* Which is the API group ?
* Is v1alpha1 supported for both, v0.8.0 and v0.7.1
* What if we add eventing ? There will be differing API versios supported
* Also eventing as several API groups which might have also different versions.
* Does this mean that we can't run `kn` against a (yet) unknown 0.9.0 serving version which uses the same API group ?

My suggestion is to list the group and versions supported by kn (for serving and eventing) and only use the product version for alpha version as this are supposedly the only API which can change within the same version (e.g. v1alpha1 for serving 0.6 is different than v1alpha1 for serving 0.7). This is not the case for beta or full versions (if those change then also the version number has to be changed for every change in the API model), e.g. v1beta1, v1beta2, ...

My proposal for the version display would be

```
Version:      v20190910-local-a607b16
Build Date:   2019-09-10 09:41:55
Git Revision: a607b16
Supported APIs:
- serving.knative.dev/v1
- serving.knative.dev/v1beta1
- serving.knative.dev/v1alpha1 (knative-serving v0.8.0)
- eventing.knative.dev/v1alpha1 (knative-eventing v0.7.1)
- messaging.knative.dev/v1beta1
```

This would also imply if a new version of knative-serving which still supports `serving.knative.dev/v1beta1` this older client would also support this new knative serving version.

**Comment by navidshaikh** [comment]
I liked this precise version of above 
```
Serving: v0.8.0(v1beta1, v1alpha1)  v0.7.1(v1alpha1)
``` 
as you suggested on slack. The `serving.knative.dev` part is common and not so useful ?

**Comment by rhuss** [comment]
Actually I think it should be vice versa, as the API group/version is the important part, especially when we leave alpha. In the same API version is supposed to stay stable across Knative serving versions, so having the actual supporter Knative serving version is of no meaning (i.e. if we have 0.8.0, and 0.9.0 also support v1beta1 then kn will work with v0.9.0, too. However the use might be confused that with v0.8.0(v1beta1) only v0.8.0 is supported which is not true). 

We should free ourselves more from the actual release version and focus on the API version as this is the important part (and people put a lot of efforts to give those API versions a meaning).

Of course this command should _also_ return the API group/version which is supported by the server. That's easy to achieve. To find out, which Knative serving version (0.7.0 or 0.8.0) is not so easy to find out.

`seving.knative.dev` is common for knative serving, but eventing has many different groups (eventing, messaging, ...), which should all be listed along with their supported versions.

**Comment by aslom** [comment]
What happens if versions supported by CLI are incompatible with serving (or eventing)?

**Comment by rhuss** [comment]
@aslom This is something we should be negotiated, based on the API version returned by the cluster. This really should be on the API version level, not kn/serving version. E.g. a `kn v0.8.0` is supposed to work with `knative-serving 0.8.0` (as kn was compiled against) but also with a future release `kn-serving-0.9.0` which is not known during `kn` release time, but has support for the same API version (e.g. v1beta1). v1alpha1 is the only version level which is supposed to be possibly incompatible within itself (e.g. a serving 0.6.0 v1alpha1  might not be the same as a 0.7.0 v1alpha1, maybe even not compatible). That's the reason why the release version number should be shown for alpha versions (as known to kn when releasing). See my suggestions above.

Otherwise I wouldn't mind to handle it like kubectl: Work if possible and fail if a specific operation can't be performed  on that very operation.
