### ISSUE TITLE
Confusing error message when passing --force flag with space

### ISSUE THREAD

**Issue by ImJasonH** [knative/client#408]
Can you spot the bug?

```
$ kn service create hello --image gcr.io/knative-samples/helloworld-go --force false
'service create' requires the service name given as single argument
```

It's the `--force false`. If you pass `--force=false` it works fine.

The error message seems to indicate that `kn` is trying to interpret `--force` as `true`, then the string `false` as a second service name, which is invalid.

Originally uncovered in https://github.com/tektoncd/catalog/issues/73

cc @navidshaikh

**Comment by duglin** [comment]
I thought we dropped the =true, =false, <space>true, <space>false stuff in favor of just --flag and --no-flag for boolean.  Didn't we?

**Comment by ImJasonH** [comment]
Maybe that's the case, yeah. In that case, I have an idea what the error message should say when I pass `--force false`. 😄

**Comment by duglin** [comment]
but I would think that `--force=true` should produce an error since we don't support `=...` on bools.

**Comment by ImJasonH** [comment]
Ah, I see. That seems to work fine:

```
$ kn service create hello --image=gcr.io/knative-samples/helloworld-go --force=true
no Knative serving API found on the backend. Please verify the installation.
```

(I don't actually have a Knative installation back there, but at least it made it past flag parsing)

**Comment by ImJasonH** [comment]
https://github.com/sixolet/client/blob/master/pkg/kn/flags/bool.go seems to indicate that both are supported. 🤷‍♂

**Comment by duglin** [comment]
using master, `--no-force` isn't supported

**Comment by navidshaikh** [comment]
That needs to be reconciled for `--force` flag, currently its done only for `--log-http`.
https://github.com/knative/client/pull/346/files#diff-24912061c7dd4fd4566a96730228474cR121

**Comment by duglin** [comment]
ah that would explain it, thank @navidshaikh

**Comment by navidshaikh** [comment]
I wonder though passing `--force` or `--no-force` to tekton task makes it a bit complex to process based on user input in taskrun ? Like the flag needs to *exists* if user mentions it's value and vice-versa in taskrun definition. Still exploring the options..
