### ISSUE TITLE
Kn plugins seems broken on Linux

### ISSUE THREAD

**Issue by maximilien** [knative/client#417]
## In what area(s)?

Kn plugins

Classifications:

> /kind bug

## What version of Knative Client?

> Paste output of 'kn version'

```bash
maximilien@maxmini:$ ./kn version
Using kn config file: /home/maximilien/.kn/config.yaml
Version:      v20190920-local-94bb1cf-dirty
Build Date:   2019-09-20 20:38:29
Git Revision: 94bb1cf
Support:
- Serving: v0.8.0  v0.7.1
- API(s):  v1alpha1
```

## What version of Knative Serving running on your cluster?

> 0.8.x

## Expected Behavior

`kn hello` should execute the `kn-hello` plugin. 

## Actual Behavior

Prints the help and that “hello is not valid command”

However, the `kn-hello` is listed when I do `kn plugin list`. So it simply not being executed.

## Steps to Reproduce the Problem

Seems to be only on my Linux system. Doubtful it has to do with the fact that my system is running Ubuntu. Cannot repro this on a Mac OS X.

**Comment by rhuss** [comment]
Have you checked the permission of your `kn-hello` command and also, if it a shell script, that the shebang is pointing to a valid shell ?

**Comment by maximilien** [comment]
You are very right sir. Thank you @rhuss. Closing and :happy:
