### ISSUE TITLE
Fill in docs for TODOs in docs/operations

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#424]
## In what area(s)?

Classifications:
/kind good-first-issue
/kind doc

## Describe the feature:
Followup of https://github.com/knative/client/issues/381
We'll need docs for

1. docs/operations/others.md
2. docs/operations/labeling.md
3. docs/operations/resources.md

which are currently marked as TODO.

**Comment by itsmurugappan** [comment]
I can help with this.

**Comment by navidshaikh** [comment]
@itsmurugappan : Thanks for the response! The docs work is being tracked more actively in https://github.com/knative/client/issues/510. There are more references in the mentioned issue about how we'd like to have docs structured. PTAL.

**Comment by itsmurugappan** [comment]
@navidshaikh thanks. Looks like there is a team already working on it. looking for a good first issue .

**Comment by wslyln** [comment]
Hi just double checking is anyone working on this issue? or on the other issue #510?

**Comment by rhuss** [comment]
I'm currently on the top-level client README and cleaning up some other parts, but otherwise, most of the other documentation ideas mentioned in #510 are probably to implementation on the main documentation site. We are still late though ;-( // @abrennan89 

Anything you are interested in particular? If so, i can break down the task in more concrete working items.

**Comment by wslyln** [comment]
@rhuss Any of them would be fine. Though yes breaking down into more concrete items would be helpful :)

**Comment by rhuss** [comment]
@wslyln thanks ! Going to work on breaking down doc items on monday. Stay tuned ;-) ....

**Comment by rhuss** [comment]
I think we should remove that whole "operations" section and make it part of the #650  User Manual, which eventually should be hosted on knative.dev (to avoid duplication).

Also, the other sectiosn of this user documentation should be absorbed by the user manual.

**Comment by rhuss** [comment]
Lets keep the issue open (and dont move it over to the docs repo) as this is about cleaning up documentation within this repo.

However, I still believe that having that kind of information as part of the user manual (#650) makes a lot of sense.

**Comment by NEERAJAP2001** [comment]
@rhuss sir, how can I go ahead with solving the issue as docs are already there?

**Comment by navidshaikh** [comment]
/close
in favor of other docs rehaul issue
