### ISSUE TITLE
curl -L https://storage.cloud.google.com/knative-nightly/client/latest/kn-darwin-amd64 returns HTML instead of object

### ISSUE THREAD

**Issue by drnic** [knative/client#425]
From the docs I should be able to get `kn` via https://storage.cloud.google.com/knative-nightly/client/latest/kn-darwin-amd64, but when I `curl` it I get an HTML page:

```
curl -L https://storage.cloud.google.com/knative-nightly/client/latest/kn-darwin-amd64
```

Does something need fixing on the bucket; or is there some header I need to provide?

**Comment by navidshaikh** [comment]
Please try
```
curl -L https://storage.googleapis.com/knative-nightly/client/latest/kn-darwin-amd64 -o kn && chmod +x kn
```

will update the doc with correct link shortly
