### ISSUE TITLE
zsh completion gives errors

### ISSUE THREAD

**Issue by drnic** [knative/client#426]
```
$ uname -a
Darwin starkair.lan 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

$ brew list zsh
/usr/local/Cellar/zsh/5.7.1/bin/zsh
...

$ source <(kn completion --zsh)
_arguments:comparguments:319: can only be called from completion function
_arguments:comparguments:319: can only be called from completion function
```
/cc @maximilien from #132 - any pro tips?

**Comment by rhuss** [comment]
I can confirm the error. 

My suggestion would be to either remove `kn completion` as it does not yet add many benefits (e.g. no otpions are included neither context sensitive information like service names) or make a comittment to support it fully. At the moment it's less then half-baken.

**Comment by maximilien** [comment]
I am OK with removing. I was hoping that the completion story in Cobra would get better out of the box. They made it easy to integrate but seems not so useful... It still does not work for me either 😞

**Comment by maximilien** [comment]
Removed with #439 

We can easily add again once/if the generated code from Cobra gets updated and actually works.

**Comment by navidshaikh** [comment]
> We can easily add again once/if the generated code from Cobra gets updated and actually works.

Do we also have an issue filed against cobra for this ?
