### ISSUE TITLE
Use XDG_CONFIG_HOME for location of the `kn` config

### ISSUE THREAD

**Issue by dprotaso** [knative/client#429]
## In what area(s)?

/kind feature

## Describe the feature:
Rather than contribute to the config pollution of the `$HOME` dir on Unix based systems can we following the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)?

**Comment by maximilien** [comment]
Interesting request. No experience using `$XDG_CONFIG_HOME` so excuse my nube question.

Can you list some precedence in the k8s community making a similar choice?

Thanks.

**Comment by dprotaso** [comment]
> Can you list some precedence in the k8s community making a similar choice?

I see `kustomize` use it [here](https://github.com/kubernetes-sigs/kustomize/blob/fa1af6f51e33c024d1f55f8f01049de9514d6ff4/docs/plugins/README.md#placement)

It's not a K8s specific thing - there are a few popular CLI apps that check for configs in `$XDG_CONFIG_HOME` and default to `$HOME/.config` are

See a list here: https://wiki.archlinux.org/index.php/XDG_Base_Directory#Supported

**Comment by maximilien** [comment]
Let me tag @rhuss and @navidshaikh who are likely more expert than I am on this topic and see if they have any opinion.

This is my first time encountering or hearing about `$XDG_CONFIG_HOME`.

**Comment by rhuss** [comment]
Maybe some background for the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

XDG stands for "X Desktop Group" as is the predecessor of freedesktop.org, a project that was founded in 2000 (but "XDG" survived as an acronym in their specs). freedesktop.org might join the [X.Org Foundation](https://www.phoronix.com/scan.php?page=news_item&px=FreeDesktop-org-Xorg-Forces) soon. The base directory specification was originally introduced in [2003](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.xml) and has been picked up by many popular linux distributions as a recommended standard, like:

* [Debian](https://wiki.debian.org/XDGBaseDirectorySpecification): "Debian does not require that packages conform to the XDGBDS but strongly encourages upstreams to do so. Debian packages should not be patched for conformance to avoid unnecessary deviation from upstream and other distributions"
* [Archwiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory) promotes the usages of XDGBDS. This site has also a comprehensive list of tools and where they store their configuration files.

Also according to [Wikipedia](https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory) there seems to be a common agreement to move to `~/.config` for configuration files:

> Many applications, from bash to desktop environments such as GNOME now store their per-user configuration this way, but the Unix/Linux freedesktop.org XDG Base Directory Specification aims to migrate user config files from individual dotfiles in $HOME to non-hidden files in the hidden directory $HOME/.config

-----

I'm positive to introduce XDGHOME to be a 'good' citizen in the Unix (Linux/macOS) world. However, for Windows we should adopt to the Windows standard. That is, AFAIK `%APPDATA%` but I'm really no Windows expert. See this [SO question](https://stackoverflow.com/questions/43853548/xdg-basedir-directories-for-windows) for a suggested mapping of XDG base directories to Windows.

My suggestion would be now:

* Use `$XDG_CONFIG_HOME` as based for the `kn` config directory, and if not set, use `~/.config`
* For Windows use, `%APPDATA%/kn` as configuration directory

**Comment by maximilien** [comment]
Thanks for the comment @rhuss. From your comment and references I would be incline not to change anything sine `~/.kn/...` is more in line with current k8s config location.

However, I tend not to have strong opinions on defaults since they should be by definition what the majority wants and that changes over time. I'll let others chime in.

**Comment by jchesterpivotal** [comment]
I'm in favour of respecting `XDG_CONFIG_HOME`. It plays nicer with other software. I don't see kubectl as a decisive influence against adopting it.

**Comment by maximilien** [comment]
Sorry but I don't see much more interest in this issue. I think staying in line with `kubectl` is a better route than adding this IMO and more importantly `~/.kn` location is simple and easy to remember as is `~/.kube`

Perhaps this can be suggested in next version or in `kubectl` WG as with this one. That way we can move in sync.

Unless I hear otherwise in next two days I will close this issue.

**Comment by rhuss** [comment]
Well, Helm moved to _XDG Base Directory Specification_, too, so I think its actually the right way to go. But I agree that it is not of high priority (although I believe implementing it is trivial).
