### ISSUE TITLE
Integration Test Flake

### ISSUE THREAD

**Issue by rhuss** [knative/client#434]
## In what area(s)?
E2E Testing

In this [E2E Test run](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/432/pull-knative-client-integration-tests/1181485419032743939) an error occurred which is unrelated to the change in the PR:

```
--- PASS: TestServiceOptions/create,_update_and_validate_service_with_annotations (12.40s)
--- FAIL: TestTrafficSplit (364.94s)
    --- PASS: TestTrafficSplit/tag_two_revisions_as_v1_and_v2_and_give_50-50%_share (39.85s)
    --- FAIL: TestTrafficSplit/ramp/up_down_a_revision_to_20%_adjusting_other_traffic_to_accommodate (18.39s)
        traffic_split_test.go:367: assertion failed: error is not nil: expecting to receive parts of length 2, got 1 string: ,echo1-qkwgb-3,100,true seprator: |
    --- PASS: TestTrafficSplit/tag_a_revision_as_candidate,_without_otherwise_changing_any_traffic_split (12.07s)
    --- PASS: TestTrafficSplit/tag_a_revision_as_candidate,_set_2%_traffic_adjusting_other_traffic_to_accommodate (13.04s) 
```

**Comment by maximilien** [comment]
I have not seen this running locally. But I have seen another. lf it appears again will add to this issue.

**Comment by navidshaikh** [comment]
This is not reproducible easily, appears rarely may be due to same race condition. 
Updated the error message to state explicitly about mismatch in expected/actual traffic targets length and print the actual targets.
