### ISSUE TITLE
Rename --async to --no-wait

### ISSUE THREAD

**Issue by rhuss** [knative/client#438]
For operations for that we support sync/async, we default to wait, and offer an option `--async` for background operations.

I suggest renaming this to `--no-wait` as it seems that `--wait` is the common way to specify this behaviour when it is not the default. We can also introduce a `--wait` that would be a no-op now but help users to express their intent better and save them from changing of default values.

Other projects where I see `--wait` as options are:

* Riff
* Helm
* TriggerMesh CLI

and probably some more.

**Comment by navidshaikh** [comment]
+1 for both wait and no-wait flags.

**Comment by duglin** [comment]
+1 I think --async is a bit too geeky/low-level-ish

**Comment by rhuss** [comment]
ok, I will pick this up then and go for `--no-wait`.

**Comment by dsimansk** [comment]
@rhuss would you like to have `--async` for a while with a deprecation warning? Or rename it in one go?

**Comment by rhuss** [comment]
Let's deprecate it and remove it in a future version, and if it's only to exercise the deprecation process (which we do not thave yet ;-)
