### ISSUE TITLE
How to use this package as Knative SDK?

### ISSUE THREAD

**Issue by sirius1024** [knative/client#440]
## In what area(s)?
> /kind usage

## Ask your question here:
Hey guys, I want to import this client as knative SDK, not sure to use github.com or knative.dev
![image](https://user-images.githubusercontent.com/6395714/66636618-24275700-ec44-11e9-9602-bf94f5276579.png)

I check pkg/kn/commands/types.go then saw:
```go
serving_kn_v1alpha1 "knative.dev/client/pkg/serving/v1alpha1"
```
**go version go1.13.1 darwin/amd64**
Anything that I missed?

**Comment by rhuss** [comment]
Which version of kn are you using ? I'm asking beause on `master` currently the module name is declare as 

https://github.com/knative/client/blob/a2d1ef7d83f197dfc9d416197fadf0890ad4445a/go.mod#L1

which is the canonical name. Any reference to `github.com/knative/client` is wrong. 

Ah, I see that you refer to `v0.2.0` which still use the old location. You do have to update your go.mod dependency to a later version (either with timestamp or from master).

Try

```
go get github.com/knative.dev/client@master
```

This you upate your go.mod accordingly.

**Comment by sirius1024** [comment]
I think go get should be 
```shell
go get knative.dev/client@master
```
Then go.mod changed and it worked. Thank you!
```go
knative.dev/client v0.2.1-0.20191010130606-a2d1ef7d83f1
```
Another part of this question is I checked the code of the master branch, in my mind to use the SDK should create a client first:
```go
v1alpha1.KnServingClient.NewKnServingClient()
```
Then call its CRUD method right?

**Comment by rhuss** [comment]
> I think go get should be
> 
> ```shell
> go get knative.dev/client@master
> ```

Ah, sure. Sorry, fat fingers ;-)



> Another part of this question is I checked the code of the master branch, in my mind to use the SDK should create a client first:
> 
> ```go
> v1alpha1.NewKnServingClient()
> ```
> 
> Then call its CRUD method right?

Yes, that it's how it to supposed to work (you do need to provide the namespace to operate in as argument and an instance of `ServingV1alpha1Interface`, though). See e..g https://github.com/knative/client/blob/a2d1ef7d83f197dfc9d416197fadf0890ad4445a/pkg/kn/commands/types.go#L70 for how to get the `ServingV1Alpha1Interface`.

You can then use any of these methods:

https://github.com/knative/client/blob/a2d1ef7d83f197dfc9d416197fadf0890ad4445a/pkg/serving/v1alpha1/client.go#L41-L86

But please note that this interface definition is still in flux and might change anytime without notice. If you are looking for something more stable you might consider to use the knative-serving interface (`ServingV1Alpha1Interface`) directly.

**Comment by rhuss** [comment]
The benefit of this client interface is that it has additional, client-specific methods, like waiting for a service to become ready (also the signature is a bit simplified). Otherwise it provides the same functionality as the knative-serving API.

**Comment by sirius1024** [comment]
Really cool! For now I'm also in the research phase. Will you accept pull request if I can do bug-fix/feature-develop...? I learned a lot about Golang from your code ;-)

**Comment by rhuss** [comment]
Yes, sure ! Any help is highly appreciated. You might want also look out for issue marked with [good first issue](https://github.com/knative/client/labels/kind%2Fgood-first-issue). If you are interested in working on one of them, just mention in the issue and we can see how to ramp you up (and whether the issue is still relevant ;-)

**Comment by sixolet** [comment]
Also note that the client interface may change before 1.0

**Comment by sirius1024** [comment]
I just finished the CRUD validations of knative services with this SDK.
As @sixolet said I think the interfaces are really good for a command-line tool but maybe not good enough for an SDK. Like when I try to create a knative service I don't know where to pass the Image string just like its namespace, and constructService function (**./pkg/kn/commands/service/create.go**) declared as private., so I've to copy-paste-change the method source code :-D...

I will follow the good-first-issue and improve my coding skills to working on the client, thanks! @rhuss @sixolet
