### ISSUE TITLE
Enable/Disable secure https access to Services

### ISSUE THREAD

**Issue by zhanggbj** [knative/client#447]
## In what area(s)?
Knative Serving

## Describe the feature:
By default, Knative Service will be deployed and accessed by `http`. However, in production, users usually need to access them by secure `https`. Fow now, Knative support to enable https connection but with some manual steps (https://knative.dev/development/serving/using-a-tls-cert). I'm thinking if we can add a subcommand for kn client to enable/disable https connection. Thanks!

```
kn service enable-feature-flag https-connection --key cert.pk --cert cert.pem-> to enable a https-connection
kn service disable-feature-flag https-connection -> to disable a feature
kn service feature-flags -> to list all features and enablement
```

I tried it manually in my env
```
[zhanggong@zhanggongdeMacBook-Pro ~ ]$ kn service list -n tenant3
NAME                    URL                                                GENERATION   AGE     CONDITIONS   READY   REASON
helloworld-httpdomain   http://helloworld-httpdomain.tenant3.test.com   1            5h47m   3 OK / 3     True

curl -vvv https://helloworld-httpdomain.tenant3.test.com
* Rebuilt URL to: https://helloworld-httpdomain.tenant3.test.com/
*   Trying 169.48.224.194...
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.tenant3.test.com
*  start date: Oct 14 05:27:41 2019 GMT
*  expire date: Jan 12 05:27:41 2020 GMT
*  subjectAltName: host "helloworld-httpdomain.tenant3.test.com" matched cert's "*.tenant3.test.com"
< HTTP/2 200
< content-length: 13
< content-type: text/plain; charset=utf-8
< date: Mon, 14 Oct 2019 13:14:49 GMT
< x-envoy-upstream-service-time: 15
< server: istio-envoy
<
Hello world!
```

**Comment by rhuss** [comment]
I think this is a very valid use case. However, I'm afraid we can't deliver this feature from the `kn` client which can only talk over Knative APIs. Sophisticated PKI management and installing certs e.g. by creating secrets and updating internal Knative components is out of scope of this developer-oriented, client tool. It's more that the Knative itself has to provide TLS support from its installation. 

For example, a kn user is a typical _developer_ which does not (and should not) have the _administrator_ permissions to perform all the manipulations to enable SSL certificates. 

If Knative offers this kind of option to switch on/off TLS for a user-provided certificate (e.g. as part of the `Service` definition) we could use that in the Kn client (and maybe even offer Letsencrypt support to create the cert, too). But until then, I'm afraid we can't do anything from the client-side.

**Comment by maximilien** [comment]
@zhanggbj have you considered proposing TLS support in the `serving` WG?

**Comment by zhanggbj** [comment]
@rhuss @maximilien 
I agree with that and raised an issue in the Serving community, let's see if they have some plan to provide it. Thanks!
https://github.com/knative/serving/issues/5930

**Comment by duglin** [comment]
Some platforms,such as IKS, enable TLS by default for all services - so if we do something in this space we need to take into account what the platform might already be doing.

**Comment by zhanggbj** [comment]
@duglin Sure, the platform may have enable TLS for the default domain, for IKS, it's the ingress domain. I'm thinking that in some cases the customer may wants to bring their own domain and certificate, then it would be better we can provide a simple way to do it instead of letting them modify different Resources.
