### ISSUE TITLE
Change "Address" field name on service descibe

### ISSUE THREAD

**Issue by duglin** [knative/client#459]
```
$ kn service describe echo1 

Name:       echo1
Namespace:  default
URL:        http://echo1.default.kndev.us-south.containers.appdomain.cloud
Address:    http://echo1.default.svc.cluster.local
...
```

I think the use of the terms "Address" and "URL" are going to be confusing to people because those words mean just about the same thing. I would like to suggest that we use something like "Internal URL" instead of "Address" because 1) I believe it really is for internal cluster usage, and 2) it would make it consistent with "URL" by reusing the word "URL" from the previous field.

**Comment by rhuss** [comment]
Good point, but I would opt for `Cluster URL` as this reflects the Kubernetes naming (e.g. `ClusterIP` used for a k8s service, that what it is actually, an URL reachable within the cluster). Should we then renam `URL` to e.g. `Route URL` to make it more symmetric ?

```
Name:        echo1
Namespace:   default
Route URL:   http://echo1.default.kndev.us-south.containers.appdomain.cloud
Cluster URL: http://echo1.default.svc.cluster.local
```

**Comment by duglin** [comment]
ok with me
