### ISSUE TITLE
The Public Docker Image is Outdated

### ISSUE THREAD

**Issue by jamesward** [knative/client#465]
It seems that the latest release of the public docker image:
gcr.io/knative-releases/github.com/knative/client/cmd/kn

Is out of date (0.2.0).  It'd be great to have a new release.

**Comment by navidshaikh** [comment]
The correct kn released image URL is `gcr.io/knative-releases/knative.dev/client/cmd/kn` with `latest` and `v0.9.0` tags.
Updated kn task with correct URL https://github.com/tektoncd/catalog/pull/114.

**Comment by jamesward** [comment]
Awesome!  Thank you.  That is just what I needed.
