### ISSUE TITLE
Create integration tests for kn task in tektoncd catalog

### ISSUE THREAD

**Issue by mgencur** [knative/client#471]
## In what area(s)?
* test suite

## Describe the feature:

Create integration tests for the kn task in https://github.com/tektoncd/catalog/tree/master/kn
This would require installing tektoncd as part of CI but this repo looks like a good place for the tests for a few reasons:
* it already installs Knative and Istio for E2E tests
* the kn client's code is in this repo so we could test with a snapshot of the kn client and see compatibility with tektoncd
* also the https://github.com/tektoncd/pipeline repo doesn't have tests for individual tasks from the catalog and the tests are not in the catalog repo either

Is this the right repo for the tests? Any suggestions welcome.

**Comment by mgencur** [comment]
I can work on this if we agree where to place the tests.

**Comment by maximilien** [comment]
Hi, @mgencur, first off, thanks for your contribution. At first glance it seems that this should be in the tekton repo instead. However, let me tag @zhangtbj who's been working on bringing these two projects closer and might have opinions.

**Comment by mgencur** [comment]
Hi @maximilien , for a few reasons that I listed in the issue description, I think this repo is a better place. Should it be in the tektoncd/pipeline or tektoncd/catalog repo, that repo would have to include the setup for every platform that all the other tasks integrate with. The CI would then have to install all the platforms and integrations so as to be able to test all tasks. And that would take immense amount of time and resources. On the other hand, having it in this repo only requires installing tektoncd, the rest is already installed: Istio, Knative. And as a plus we can run this integration test for every PR that changes the `kn` client (should the test be in the other repo, it would have to take a nightly build of kn, I guess?)

**Comment by navidshaikh** [comment]
We have 2 artifacts for kn tasks at tekton catalog
 1 - kn nightly image
 2 - kn released-image
 (https://github.com/tektoncd/catalog/tree/master/kn#parameters)

The kn-tekton tests need a built kn image to run testst. AFAIK, we build kn image in nightly and release-time cadence (and not per PR). Per PR testing for tekton specific tests would not make sense as its artifacts do not end up directly as input to kn task.

We can start with setting up kn-tekton specific tests for nightly CI and next iteration could be to also batch this in release-automation CI.

**Comment by navidshaikh** [comment]
> You could have a periodic flow (once a day, for example) that runs tests against the latest nightly/release kn images. Would that work?

Yes, preferably after nightly CI and rebuilt kn nightly image. Can we configure some alerting if the tekton-specific tests fail? 

> If I understand what you're suggesting, such tests would have to happen after the images are published. This is the opposite (build, then test) of what the jobs to currently do (test, then build).

**Comment by navidshaikh** [comment]
> If I understand what you're suggesting, such tests would have to happen after the images are published. This is the opposite (build, then test) of what the jobs to currently do (test, then build).

I am not sure if current test-infra could support this setup, but if we can have kn image pushed to interim repo (for eg: different tag) and use it for tekton-tests, then finally push to nightly location (`gcr.io/knative-nightly/knative.dev/client/cmd/kn:latest`).

**Comment by adrcunha** [comment]
> > You could have a periodic flow (once a day, for example) that runs tests against the latest nightly/release kn images. Would that work?
> 
> Yes, preferably after nightly CI and rebuilt kn nightly image. Can we configure some alerting if the tekton-specific tests fail?

The nightly job runs daily at 1:40AM PST, so you could have the custom CI run, say, at 6AM. Run only the tekton tests in such CI flow so you eliminate noise. Currently we don't have custom alerts in the framework, you would have to keep an eye on TestGrid. https://github.com/knative/test-infra/issues/821 is implemented could take care of that, but unfortunately that's not a current priority.

**Comment by adrcunha** [comment]
> I am not sure if current test-infra could support this setup, but if we can have kn image pushed to interim repo (for eg: different tag) and use it for tekton-tests, then finally push to nightly location (`gcr.io/knative-nightly/knative.dev/client/cmd/kn:latest`).

No, it currently doesn't support such flow. While you could easily make the nightly job push to some other gcr, you'll need some kind of trigger to start the (new) gcr copy job.

**Comment by mgencur** [comment]
Is it fair if I implement those tests and create e.g. `tekton-tests.sh` script in the test/ folder which will execute them? Someone else could then create the nightly job (or give me instructions how to do that).

**Comment by navidshaikh** [comment]
@mgencur : Sure! 
Looks like we can have a custom CI run after the nightly job as @adrcunha suggested above.

**Comment by mgencur** [comment]
PR is here: https://github.com/knative/client/pull/528
