### ISSUE TITLE
client dependencies to k8s.io/client-go

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/client#473]
## Ask your question here:

In client/go.mod, it is said:
```
	k8s.io/api v0.0.0-20190226173710-145d52631d00
	k8s.io/apimachinery v0.0.0-20190221084156-01f179d85dbc
	k8s.io/cli-runtime v0.0.0-20190325194458-f2b4781c3ae1
	k8s.io/client-go v0.0.0-20190226174127-78295b709ec6
	k8s.io/kube-openapi v0.0.0-20190722073852-5e22f3d471e6 // indirect
```

Yet, Client has dependencies to knative.dev/pkg. The dependencies in `knative.dev/pkg` are defined as
```
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.15.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.15.3"
```

The version of `k8s.io/client-go` used by client is older than `knative.dev/pkg`. It will cause problem when adding eventing dependencies. Do we need to manually change the dependency to k8s.io/client-go from  `v0.0.0-20190226174127-78295b709ec6` to `kubernetes-1.15.3` ?

**Comment by rhuss** [comment]
Yes, its an issue if transitive dependencies mismatch. The best solution is to update/downgrade the original dependencies so that there common transistive dependency align.

In this case I suggest to update manually `k8s.io/client-go v0.0.0-20190226174127-78295b709ec6` to `k8s.io/client-go kubernetes-1.15.3` manually (the timestamp will be inserted during compile run). We should align with `knative.dev/pkg`'s kubernetes dependency anyway.

**Comment by daisy-ycguo** [comment]
Thanks Roland.

After testing for several times, I find the best appropriate versions for those dependencies:

```
       k8s.io/api v0.0.0-20190528110122-9ad12a4af326 // v1.12.9, required by Serving 0.9 and Eventing 0.9
	k8s.io/cli-runtime v0.0.0-20190528110732-ad79ea2fbc0f // v1.12.9, required by Serving 0.9 and Eventing 0.9
	k8s.io/client-go v0.0.0-20190528110200-4f3abb12cae2 // v1.12.9, required by Serving 0.9 and Eventing 0.9
	knative.dev/eventing v0.9.0 // v0.10.0 cannot work with knative.dev/pkg release-0.9
	knative.dev/pkg v0.0.0-20190913154335-74659889c421 // release-0.9, required by Serving 0.9 and Eventing 0.9
	knative.dev/serving v0.9.0
```

I made these changes in my PR https://github.com/knative/client/pull/470

**Comment by daisy-ycguo** [comment]
I have to keep the current k8s libraries version because a wired issue caused by Doc generation.
We will wait for a next big upgrade to k8s v1.15 directly then.
I closed this issue.
