### ISSUE TITLE
kn source list - list all source instances (built-in, plugin, untyped)

### ISSUE THREAD

**Issue by sixolet** [knative/client#480]
kn source list should list sources of all source CRDs, unlike the normal list which only lists one type. It should have an option to list only one type, too.

See the [spec](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit#bookmark=id.y3zojnunoufp) for details:

For listing all sources, kn queries all instances of source CRDs. So it first picks up all CRDs that are describing Sources and then queries each CRD type in turn to look up its COs and also checks whether this CO is supported by a typed source handler (built-in/plugin).

```
# List all created sources
$ kn source list

NAME            TYPE     RESOURCE                                 SINK    
twitter-knative twitter  twittersource.sources.k8spatterns.io     myservice 
mystorage       storage  storages.storages.events.cloud.run       broker:default
```

This list can be filtered by type (--type) or on the resource name (--source-name). 

The general algorithm described above in pseudo-code:

```
var pluginTypes map[string]string
// sourcePlugins: All kn plugins prefixed with "kn-source-"
for _, plugin := range sourcePlugins {
    // Actually execute a command on the plugin ("manifest") 
    // and parse the output. See Source Plugins for details.
    for _, crd := range plugin.CRDs() {
        pluginTypes[crd] = plugin.Name
    }
}
var crds map[string]string
// Reach out to the cluster and query for all CRDs with a certain label
for _, crd := range listK8sCRDsWithSourceLabel() {
    crds[crd.Name] = "generic"
    if plugin, ok := pluginTypes[crd.Name]; ok {
        crds[crd.Name] = plugin
    }
}
for crd, plugin := range crds {
    printCustomObjectsUsingPluginIfNotGeneric(plugin, crd, namespace)
}
```

**Comment by rhuss** [comment]
Updated description with the content of the [spec](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit#) (which remains the authorative document)

**Comment by navidshaikh** [comment]
We have leaf `list` verb for supported sources to cover for now, would be good if we can bring `kn source list`.

@maximilien are you on it?
