### ISSUE TITLE
Support for requesting GPU resources

### ISSUE THREAD

**Issue by rhuss** [knative/client#490]
## Describe the feature:

According to https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/ it is possible for a service to specify a request for one or more GPUS.

It is suggested to add a command-line option `--limits-gpu` to specify a integer number of GPUs requested (there's no need for a `--requests-gpu` accorinding to https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/)

**Comment by sixolet** [comment]
Is that part of knative or just kube?

**Comment by rhuss** [comment]
Good question ;-) 'will have to ask on Knative serving.

**Comment by evankanderson** [comment]
`requests` and `limits` are part of the [ResourceRequirements](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#resourcerequirements-v1-core) of a container. Each is defined to be an `object` in JSON and the docs link to https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container mentions a number of additional resource types beyond CPU and Memory, include `hugepages-<size>` and `ephemeral-storage` (beta in 1.16). In addition, Kubernetes supports [Extended Resources](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#extended-resources) which are user-defined.

As such, we might want this flag to be a repeated `--additional-limits` which can specify a `string=string` limit.

**Comment by maximilien** [comment]
I initially added the `--limits/requests-cpu` and `--limits/requests-memory` so happy to add this with `--additional-limits/requests`, unless I hear otherwise...

**Comment by rhuss** [comment]
Sound legit to me, except that I would change the order like in `--requests-extra` and `--limits-extra` to fit the general scheme and have limits and requests grouped together on the help page (as this is alphabetically ordered).

Said that, I probably even do prefer a general `--limits` and `--requests` options with two predefined keys `memory` and `cpu` which has a specific meaning (and specific validation on the value) + free form additional keys like `hugepages-size` or `nvidia.com/gpu` etc. these extra keys would not have any client-side value validation.

This would also have the benefit to reduce the number of options, too (2 instead of 6 + a consistent behaviour).

We could deprecate `--limits-cpu` and `--limits-memory` for the next version and remove it for the over-next version (or according to any other deprecation rule we might want to establish).

**Comment by rhuss** [comment]
E.g.

```
kn service create mysvc --image myimg  \
     --limits cpu=1000m --limits memory=1024Mi --limits nvidia.com/gpu=1 \
     --requests ephemeral-storage=4Gi
```

**Comment by rhuss** [comment]
What our take on this feature ? I think it would be nice to restrict ourselves to `--limit` and `--request` for all sort of limits, which is more flexible and even reduces the UX surface.

**Comment by navidshaikh** [comment]
+1 for `--limits` and `--requests` with two predefined keys for `cpu` and `memory` (and may be we can validate restrictions for specifying requests for GPU as well?)
