### ISSUE TITLE
Misleading message about version change

### ISSUE THREAD

**Issue by duglin** [knative/client#512]
Today I noticed this:
```
$ kn service update echo --revision-name echo-v1 --concurrency-limit=0
Updating Service 'echo' in namespace 'default':

  0.243s Ready to serve.

Service 'echo' updated with latest revision 'echo-gnxbs-2' (unchanged) and URL:
http://echo-default.kn.us-south.containers.appdomain.cloud
```
The mention of `echo-gnxbs-2` and `unchanged` is very confusing to me because the latest version *did* change (the concurrency limit changed) and the latest version is not "echo-gnxbs-2", it's "echo-v1".

I'm not sure what that message is trying to convey but I'm not sure I see the value in showing me the old revision name or telling me whether its changed or not when I should already know it because of what I put on the cmd line. Also, do we need to show the URL again since it's unchanged?

**Comment by navidshaikh** [comment]
@duglin : Are you using the serving nightly build ?

**Comment by navidshaikh** [comment]
If it's against serving nightly build, it's because latestReadyRevision reported by service status is same as the one before service update and kn is comparing this field before and after the update to print whether its `unchanged` or not. See https://github.com/knative/serving/issues/6060

**Comment by duglin** [comment]
@navidshaikh thanks - I was testing with 'master', using v0.10 I don't see the issue.

Do people think we really need to echo the service URL again on an update? I don't think anything the user can do will change the value so I don't see the point in adding even more verbosity. In fact, the one thing I can think of that might justify some kind of message would be the use of the `--tag` since that will create a new endpoint, but we still return the default URL in those cases right now.

yes I'm going to keep complaining about how chatty we are by default :-)
