### ISSUE TITLE
Support machine-readable output for "kn version"

### ISSUE THREAD

**Issue by rhuss** [knative/client#513]
## Describe the feature:

In order to interoperate nicely with tooling that calls kn and in the spirit of our other commands we should support _machine-readable_ output in addition to _human-readable_ output for `kn version`.

I.e. I think having a `kn version -o json` return something like

```json
{
  "version": "v0.10.0",
  "date": "2019-11-21 21:06:36",
  "commit": "e07b5a9",
  "apis": {
     "serving": [
        "serving.knative.dev/v1alpha1"
     ],
     "eventing": [
        "sources.eventing.knative.dev/v1alpha1"
     ]
  } 
}
```

In the future there might be server version (i.e. which APIs are supported), included here as well.

**Comment by navidshaikh** [comment]
@zhanggbj are you working on this?
