### ISSUE TITLE
kn source <plugin> - manage typed plugins

### ISSUE THREAD

**Issue by rhuss** [knative/client#519]
Implement the management of sources backed by plugins as described in the spec for [Typed Plugin Sources](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit#bookmark=id.4uhbt122ju3g). The plugin contract is specified in [Plugin Sources](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit#bookmark=id.haqakmi5287a)

-----------------

- [ ] `kn source <plugin> create`
- [ ] `kn source <plugin> update`
- [ ] `kn source <plugin> describe`
- [ ] `kn source <plugin> delete`

**Comment by maximilien** [comment]
OK, finally working on this. Should have a PR next week

**Comment by maximilien** [comment]
We’ve moved to a different approach to creating the source plugins. So I suggest closing this and let’s track them on knative-sandbox

**Comment by rhuss** [comment]
Yeah, I think we can indeed close this and open more specific issues in case e.g. when we want to extend the plugin contract.
