### ISSUE TITLE
Implements scripts to cut a release

### ISSUE THREAD

**Issue by csantanapr** [knative/client#52]

**Comment by rhuss** [comment]
An idea for setting the release number properly during build and release, together with the PR in #69 which introduces a `kn version` command:

* Using a file e.g "NEXT_VERSION" with a single entry (e.g. "0.1.0").
* A `build.sh` which uses 


```
go build -ldflags "-X commands.Version=$(cat NEXT_VERSION)-$(git rev-parse --short HEAD) ....
````

for setting a snapshot version (according to [semver.org](https://semver.org/#spec-item-9) 1.0.0-eed913e is _before_ 1.0.0)
* A `release.sh` which uses 

```
go build -ldflags "-X commands.Version=$(cat NEXT_VERSION) ..."
```

and then increases the number in `NEXT_VERSION` to the next milestone version.

**Comment by maximilien** [comment]
Parts of this done in #69

**Comment by maximilien** [comment]
@rhuss let me know if the scheme in #69 is good enough. Best.

**Comment by rhuss** [comment]
Looks good, I think its good enough for now. Thanks !
