### ISSUE TITLE
Enable project support for knative/client repo

### ISSUE THREAD

**Issue by rhuss** [knative/client#521]
I suggest enabling GitHub Projects support for this repository (`"Settings" -> "Options" -> [ ]  Projects`) so that we can easier track sub-projects like the Eventing MVP.

@adrcunha is this something you could enable? (sorry to ping you directly, I don't know anybody else to bug :) and unfortunately, I don't have enough Karma to do it on my own)

We can always switch if off again if the community votes against using GitHub projects.

**Comment by adrcunha** [comment]
(sorry, I missed this issue) I'm not an admin, so I can't enable it. I believe @sixolet can? Otherwise, you can ask an admin on Slack.

**Comment by rhuss** [comment]
Looks like that it already had been enabled, thanks anyway !
