### ISSUE TITLE
Publish artifacts CLI binary for Mac and Linux for nightly and v0.1.0 

### ISSUE THREAD

**Issue by csantanapr** [knative/client#53]

**Comment by navidshaikh** [comment]
@sixolet : I think we'd need a separate CI job for this, we have script in place to build binaries, IMO we should start building it nightly. WDYT ?

**Comment by adrcunha** [comment]
Yes, a separate job is required. Currently all Knative modules use the nightly release infrastructure from test-infra. For example:

https://github.com/knative/build/blob/master/hack/release.sh

However, since we're not talking about docker images here, the infra might need some changes to handle that.

**Comment by navidshaikh** [comment]
@adrcunha :  Thanks for the input. 

> However, since we're not talking about docker images here, the infra might need some changes to handle that.

Right, instead we'll have 3 `kn` binaries each per platform.
This is needed for nightly and v0.1 release (due today).

**Comment by adrcunha** [comment]
This is done, see https://github.com/knative/test-infra/issues/745.

**Comment by csantanapr** [comment]
What’s the next step? Create a release branch 0.1.0 ?

**Comment by adrcunha** [comment]
Yes. I told sixolet the details, happy to elaborate on that offline.

**Comment by csantanapr** [comment]
Cool thanks @adrcunha 👍🏻

**Comment by adrcunha** [comment]
Forgot.to mention that you can also talk to @nbarthwal who's documenting the auto-release process.

**Comment by csantanapr** [comment]
Excellent I was going to ask if we could doc some instructions so we can have others help cut releases
