### ISSUE TITLE
kn source container - manage ContainerSource

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/client#530]
/kind feature

## Describe the feature:

It's a separate item of Eventing MVP ["kn source" create & update typed builtin](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit#bookmark=id.d382ob8kwx0f), for easily management.

Add commands to create, delete and list ContainerSource. See below as an example:

```
kn sources container create myimporter --image gcr/test-importer --arg firstArg --arg secondArg --env var1=value1 --env var2=value2
kn source container delete myimporter
kn source container list
```

------------------------

- [ ] `kn source container create`
- [ ] `kn source container update`
- [ ] `kn source container describe`
- [ ] `kn source container delete`
- [ ] `kn source container list`

**Comment by rhuss** [comment]
This issue is on hold as the container source as it is know right now will be obsolete soonish

**Comment by rhuss** [comment]
There won't be any `ContainerSource` in the future (`SinkBinding` or how it will be eventually called is the successor)

**Comment by rhuss** [comment]
`ContainerSource` is back in the game via https://github.com/knative/eventing/pull/2824 so let's reopen this issue and work on it.

**Comment by rhuss** [comment]
@daisy-ycguo if you have interest you could pick this up again.
