### ISSUE TITLE
webhook errors are lost

### ISSUE THREAD

**Issue by duglin** [knative/client#534]
```
$ kubectl apply -f s.yaml 
Error from server (InternalError): error when creating "s.yaml": Internal error occurred: failed calling webhook "webhook.serving.knative.dev": Post https://webhook.knative-serving.svc:443/?timeout=30s: stream error: stream ID 217; INTERNAL_ERROR

$ cat s.yaml 
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echo
spec:
  template:
    spec:
      containers:
      - image: duglin/echo

$ kn service create echo --image duglin/echo
Creating service 'echo' in namespace 'default':

  0.244s The Route is still working to reflect the latest desired specification.
  0.336s Configuration "echo" is waiting for a Revision to become ready.
  4.337s ...
  4.596s Ingress has not yet been reconciled.
  5.985s Ready to serve.

Service 'echo' created with latest revision 'echo-bhdpj-1' and URL:
http://echo.default.example.com
```

Notice `kn` doesn't tell me about the error that's generated by the webhook, it just keeps on going.  Granted you need a webhook that dies  :-)

**Comment by rhuss** [comment]
Actually `kn service create` does nothing else as you did in the step before, talking with the K8s API server and creating a Service resource. So I really have no idea why this should be different (remember, the webhook is not called by `kn` but by the K8s API server internally).

So could it be that this was a temporary or flaky issue ? Have you try to create via `s.yaml` again after youwas successful with `kn` ? Could you use the `Service` created by `kn` and us that as your input for `s.yaml` ?

**Comment by duglin** [comment]
The issue was with the webhook - there was a bug in there causing it to crash. So, the issue here is that kubectl showed me the error message which allowed me to know that something weird happened on the server side (despite the fact that the service was created - just incorrectly due to the webhook not running properly), but `kn` didn't. So when using `kn` I was led to believe that everything was fine and I was left wondering why my ksvc didn't look right and was missing some data that the webhook was supposed to have added.  In essence, kn hid stuff that kubectl showed me, so it would be nice if kn did too.

**Comment by rhuss** [comment]
Sorry, for my ignorance, but what kind of webhook are you referring to ? An admission webhook, mutating or validating? And is this not a pure server-side error reported back to kubectl when it applies the yaml ? And if so, what shoud kn do differently ? It does exactly the same thing as kubectl apply.

Of course, if an error occurs when kn send a POST for creating the resource (like when a webbhook fails), this will be reported back to the user immediately, as here https://github.com/knative/client/blob/60567a9e37500307cbe40cd86e8d54af0d5af035/pkg/kn/commands/service/create.go#L122-L125 So in your second case there is no error reported by the server. In this case kubectl apply wouldn't return an error either. Or there is some extra, client-side validation that I'm not aware of, that causes the error you describe.

**Comment by duglin** [comment]
I believe it was a mutating webhook - it's the knserving one that adds some default values.
