### ISSUE TITLE
Add Hugo frontmatter to generated docs

### ISSUE THREAD

**Issue by rhuss** [knative/client#539]
## In what area(s)?

Documentation

## Describe the feature:

When creating the documentation for commands during the build process, the generated documentation should at least contains the front matter which is used by the knative.dev documentation generation is required.

For a first implementation, it's about the overall mechanism, to include the front-matter section which includes also the title as shown in the navigation.

There are two possible ways of how this could be implemented:

* Extend the build generation directly in go-code to add the required header
* Add a postprocessing step which takes the generated markdown and adds the required metadata.

Also, it needs to be discussed whether only 1 single set of reference documentation should be created or two sets, one for direct usage in the Github repo (as it is now) and one for inclusion in the website documentation.

Doing it in a postprocessing step would have the benefit that this script could run during site-generation, and hence would nicely decouple the responsibilities. Also, if it's only about adding a header file, then it's should be also technically easy to achieve.

### References:

* Client Code generation: https://github.com/knative/client/blob/master/hack/generate-docs.go
* Sample frontmatter as used by knative.dev: https://raw.githubusercontent.com/knative/docs/master/docs/serving/accessing-metrics.md

**Comment by rhuss** [comment]
Will be implemented as part of #510 .

**Comment by navidshaikh** [comment]
/close

fixed by #680
