### ISSUE TITLE
e2e flake: service create - referenced revision not found 

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#544]
```
Failed to successfully execute 
'kn service create hello --image gcr.io/knative-samples/helloworld-go -n kne2etests5': 
Execution error: stderr: 'RevisionMissing: Revision "hello-bzbty-1" 
referenced in traffic not found.
```
ref
- [logs1](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/542/pull-knative-client-integration-tests/1204319054475563009#1:build-log.txt%3A881)
- [logs2 (Dec 17)](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/560/pull-knative-client-integration-tests-latest-release/1206979735146467330#1:build-log.txt%3A491)

**Comment by maximilien** [comment]
I've seen this (or very similar) with `kn revision update ...`. I'll track it down and see if the resulting message is same or different and open an issue or report here appropriately.

**Comment by navidshaikh** [comment]
Every now and this error comes up, latest one against serving v0.12.0 release [here](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/622/pull-knative-client-integration-tests-latest-release/1219938598371987459#1:build-log.txt%3A949)

**Comment by navidshaikh** [comment]
++ 
[logs](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/617/pull-knative-client-integration-tests-latest-release/1219943506416504835#1:build-log.txt%3A548)

**Comment by navidshaikh** [comment]
++
[logs](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/634/pull-knative-client-integration-tests-latest-release/1224602067885101056#1:build-log.txt%3A557)
