### ISSUE TITLE
Support for yaml deployments

### ISSUE THREAD

**Issue by ahmetb** [knative/client#550]
Is it a non-goal to support declarative deployments like `gcloud alpha run services replace` command with `kn`. Honestly, kubectl works fine but `kn` has a nice "wait for readiness" feature.

As a user, I observe that  I'm not entirely convinced that `kn service create` has options for pretty much everything I need, but the resulting command looks, well, not so declarative or easy to store in a codebase:

```
kn service create hello --force \
--image gcr.io/google-samples/hello-app:1.0  \
--annotation "networking.knative.dev/ingress.class=kourier.ingress.networking.knative.dev" \
--limits-cpu 100m \
--limits-memory=256Mi \
--requests-cpu 50m \
--requests-memory=128Mi \
--env-from cm:mysql-options
```

Instead of checking in a script to this to my codebase,  I might as well opt in for the YAML+kubectl route  (and get consistency with the rest of my Kubernetes deployments), at the risk of losing "readiness check" capabilities of `kn`.

Also Knative currently only supports a single container in `RevisionSpec.containers[]` field but there are open proposals for sidecar containers, and I'm not sure how would that look like in the fully imperative CLI.

I'm curious:

- if many of Knative users would still prefer to have access to YAML via `kn`?
- can `kn` possibly offer readiness check for latest deployed revision as a separate feature?

**Comment by rhuss** [comment]
As already mentioned on [Twitter](https://twitter.com/ro14nd/status/1202996647761985550?s=20), I'm not sure why *imperatively* applying a yaml file is more declarative than creating that very same yaml on the fly when using kn. For the server, both look the same. It's true that YAML can be better handled in CM system with all its advantages for CI and that command line options can be quite lengthy. However, for this automated use case, you have already other tools like `kubectl` (except for hosted Cloud Run, but I guess there are similar tools for AppEngine backed Knative, too) or Ansible task who would do that. You can perfectly export YAML with `kn` (`kn service describe mysc -o yaml`) and use that as a base for your automation. So a nice way to prototype. 

I wouldn't mind much to add this feature (despite it also against the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) o"Make each program do one thing well."), but I wouldn't put it high on the priority list.
