### ISSUE TITLE
Usability issues around create+update

### ISSUE THREAD

**Issue by ahmetb** [knative/client#551]
I'm fairly new to this tool and repo but for quickly trying it out something jumped to me.

I'm supposed to use this tool in CI/CD deployments, as it's the de facto CLI for Knative. However, it seems like `kn service create` needs to be run before `kn service update` can be called. 

This is not good for automation in scripts. Assume I'm creating a new namespace, and if I were to hardcode `kn service update` in my script, it would fail because `kn service create` should be done first.

I have noticed I can do `kn service create --force` but I'm not sure what it does (it says it "replaces"). Is this a delete+create, or just in-place replacement (e.g. would it drop cause disruption).

Also keep in mind that **--force** has connotations (like in `kubectl replace --force`) which explicitly DELETES then re-creates. So it's not a wise choice of word here.

Maybe I'm coming from a declarative world (kubernetes mindset) as you can see in #550, but I find it sort of odd that there are separate commands for `update` and `create`. Is the `update` supposed to be partial (like `kubectl patch`) and `create` (with **--force**) is supposed to be `kubectl replace`?

**Comment by rhuss** [comment]
Thanks a lot for your feedback!

> I have noticed I can do `kn service create --force` but I'm not sure what it does (it says it "replaces"). Is this a delete+create, or just in-place replacement (e.g. would it drop cause disruption).

It's a in-place replacemenent by [keeping  the resource version](https://github.com/knative/client/blob/5deba393cb9e1bc7eb42ed414cc9c22477cb9bc6/pkg/kn/commands/service/create.go#L176)

We had discussed the wording, but I'm totally open for renaming it, as I agree that `--force` doesn't not reflect well the typical use case ('create-or-update') for an idempotent automation. 
Any suggestions ?

Maybe we should also head for a `kn service apply --image ....`, and if only to get away from the impression that `kn` does anything more than creating resource declarations (although "apply" is an imperative action as well. Every CLI interaction is imperative, also every kubectl command)

**Comment by rhuss** [comment]
Maybe just as simple as replacing `--force` with `--replace` ? Or more drastically by replacing `kn service create` and `kn service update` with `kn service apply`?

Re-reading https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/ again I understand better now what you mean with _declarative configuration_ defined the kubectl. For me, it's still an imperative action to apply a declaration, but that's of course, nit-picking. If I understand `kubectl apply` correctly it's a fancy create-or-update with a sophisticated field merge algorithm (to not overwrite changes made outside of the apply cycle) and the possibility to delete elements.

We could do better here with kn wrt/ merging if we assume that there are other clients than kn. If we take the POV that kn is the only client for managing a particular Knative instance, then maybe a simple create-or-update like `kn service create --force` do is good enough? (except for the naming)

**Comment by ahmetb** [comment]
I think the assumption here is people will create and update applications step by step. Start with image, add cpu/memory limits, then add annotations etc. That's good for beginners.

But in reality, any serious large scale user will do exactly the opposite. They will almost never type `kn service create` or `update`, they will script their way around it.

Any changes they made by calling `update` which they can't save back to their code repo (and that lives in live configuration on the system) is a recipe for disaster and a time bomb. That's why `kubectl apply` with features like prune/replace is so appealing to a lot of Kubernetes users.

This issue is closely related to #550. For kn to gain any serious usage in significant environments, it probably needs to support declarative configuration. For that to work, users would today need `create --force` in `kn`, and maybe that's ok.

**Comment by rhuss** [comment]
fyi, there is no a `kn service apply`
