### ISSUE TITLE
Is --[no-]lock-to-digest for tag resolution

### ISSUE THREAD

**Issue by ahmetb** [knative/client#553]
From the flag description, I'm having trouble inferring if this flag is meant to [disable Tag Resolution](https://github.com/knative/docs/blob/master/docs/serving/tag-resolution.md) during the deployment.

```
      --lock-to-digest           keep the running image for the service constant when not explicitly specifying the image. (--no-lock-to-digest
                                 pulls the image tag afresh with each new revision) (default true)
```

It doesn't seem to be doing that from my hands-on experimentation, but the above description makes me think it's related to this.

**Comment by rhuss** [comment]
> From the flag description, I'm having trouble inferring if this flag is meant to [disable Tag Resolution](https://github.com/knative/docs/blob/master/docs/serving/tag-resolution.md) during the deployment.

I don't think it's about server-side tag resolution but about pinning an image to its digest in the `Configuration` via the client.

@sixolet could you please give a brief overview of the pinning concept in `kn` and how to use it (e.g. how to support different use case) ? I'm also not 100% clear about how it works (and a bit lazy to look up ;) and I think it would be also cool to have it written down as input for the docs we just have started (cc: @abrennan89 )

**Comment by sixolet** [comment]
--lock-to-digest replaces the image field with the image by digest when you do not supply --image and do create a new revision, avoiding the case where you accidentally have your service run a newer version of the same image tag. It marks the revisions with an annotation containing the original tag. 

--no-lock-to-digest does no such business, the image field remains by tag, and a new revision might pull the tag again even if you only meant to change an environment variable. 

By default kn will use the lock to digest behaviour if the annotation is present, no lock without it.

**Comment by ahmetb** [comment]
> a new revision might pull the tag again even if you only meant to change an environment variable. 

I am more confused now. Assume you don’t use Kn CLI. 
When Knative serving controller sees a new revision, it will resolve the tag to digest.
As far as I can tell there’s no way to disable this per-Service or per-Revision. 
So how does Kn CLI prevent the controller from doing the resolution of image field again?

**Comment by sixolet** [comment]
Copies the digest the server resolved.

**Comment by ahmetb** [comment]
Ahha, makes sense.
I wonder if the wording can be any better to point this out, I don't have a particular proposal.

**Comment by rhuss** [comment]
What's about `--pin-image` (and `--no-pin-image`) ? (as `digest` is more about how this pinning is implemented)

**Comment by ahmetb** [comment]
Yeah those names are more descriptive. Though, the behavior I expect would be:

> if I specify `--no-pin-image` and I specify `--image nginx:latest`, I don't want Knative to ever do digest resolution on this. As a result, scaled-up pods of ra revision may get a _different image_.

Usually people might need "disable digest resolution" (per-Service) because they're trying to circumvent a bug in controller, or an issue with image pull secrets. (I don't think Knative makes this possible per-Service.)

FWIW I wasn't trying to request a feature, was just trying to understand what this option does. I suspect others will run into this, too.

**Comment by navidshaikh** [comment]
Added doc label to document the behavior.
