### ISSUE TITLE
Misleading error message when verb is bad

### ISSUE THREAD

**Issue by duglin** [knative/client#557]
```
$ kn service udpate test --min-scale=0
unknown flag: --min-scale
```

Notice that I misspelled "update". I've also done this by using "edit" instead of "update" by mistake. So, yes there was a user error, however, the error message really should have said something like "unknown action `udpate`" or "unknown action `edit`". Instead it complains about `--min-scale`, which is technically correct the command I **thought** I was trying to do. So a user could spend quite a long time scratching their heads wondering why we're complaining about an option when the real error is that they asked for an invalid action.

Net: we should check the validity of the "verb" before we complain about the validity of the options.

**Comment by itsmurugappan** [comment]
@rhuss @duglin This is what I found out , please correct me if I am wrong.

The cobra command [find method](https://github.com/knative/client/blob/b640219140f55d037187b485747dfb8c091511f3/vendor/github.com/spf13/cobra/command.go#L599) validates the primary command if its present it ignore the sub commands wrong spelling. 

This is the fix I am suggesting, please let me know your thoughts.

While [validating](https://github.com/knative/client/blob/b640219140f55d037187b485747dfb8c091511f3/pkg/kn/core/root.go#L82) the command path pieces, if the found command is a group, shall we validate the sub command.

```
		if foundCmd, _, err := rootCmd.Find(cmdPathPieces); err != nil {
			err := plugin.HandlePluginCommand(pluginHandler, cmdPathPieces)
			if err != nil {
				rootCmd.Help()
				fmt.Fprintf(rootCmd.OutOrStderr(), "Unknown command or plugin '%s'.\n", args[1])
				os.Exit(1)
			}
		} else if strings.Contains(foundCmd.Short, "group") {
			if _, _, err := rootCmd.Find(argsMinusFirstX(cmdPathPieces)); err != nil {
				err := plugin.HandlePluginCommand(pluginHandler, argsMinusFirstX(cmdPathPieces))
				if err != nil {
					rootCmd.Help()
					fmt.Fprintf(rootCmd.OutOrStderr(), "Unknown command or plugin '%s'.\n", args[2])
					os.Exit(1)
				}
			}			
		}
```
