### ISSUE TITLE
Improve sink/subscriber support

### ISSUE THREAD

**Issue by rhuss** [knative/client#563]
## In what area(s)?

Eventing

## Describe the feature:

The following features are needed for proper sink/subscriber handling:

- [x] * Add more sink types like define in the spec
- [x] * Allow an URL to be provided
- [ ] * Allow specifying the namespace for the sink (currently: Always default)

**Comment by navidshaikh** [comment]
Broker, knative service and URL can be specified, more types can be configured via sink prefixes in the config.

Currently sink is looked up in the namespace kn is operating in, updated issue description with unchecked item for specifying namespace of the sink.

**Comment by lionelvillard** [comment]
Since sources natively support sending events to plain k8s services, it'd be nice to provide a shortcut, e.g. `svc:my-svc`.

**Comment by rhuss** [comment]
> Since sources natively support sending events to plain k8s services, it'd be nice to provide a shortcut, e.g. `svc:my-svc`.

We discussed this, but we felt that referring to vanilla Kubernetes objects is outside the 'Knative contract'. (e.g. will it also work on CloudRun ?). 

See https://github.com/knative/client/issues/898 for a more in deep discussion on this topic.

**Comment by rhuss** [comment]
Although this issue has been closed, I think we should still think about how to allow the specification of a different namespace for a cross-namespace eventing mesh. 

I create a new issue for this: https://github.com/knative/client/issues/1143
