### ISSUE TITLE
source apiserver update --resource should follow the common update semantics for list like structures

### ISSUE THREAD

**Issue by rhuss** [knative/client#565]
I.e. the same as for `kn service update --env` or `kn trigger update --filter`. I.e. add new resources, overwrite existing, and remove when suffixed with `-`.

**Comment by rhuss** [comment]
While fixing this, this handling should be put into a shared method so to guarantee the list-like options are handled the same.

**Comment by daisy-ycguo** [comment]
/assign daisy-ycguo
I would like to take this issue.
