### ISSUE TITLE
Harmonize list headers for "trigger list", "cronjob list" and "apiserver list"

### ISSUE THREAD

**Issue by rhuss** [knative/client#567]
Actually the columns wrt to Sink / Subscription are different:

* CronJon and Apiserver source display the sink shortcut ('svc:myservice')
* Trigger shows the resolved URL ("SUBSCRIBER_URL")

Also, the condition and reason columns should be the same as for services. 
Should we add AGE, too ?

**Comment by daisy-ycguo** [comment]
Current status:

```
$ ./kn trigger list
NAME       BROKER    SUBSCRIBER_URI                                   READY   REASON
trigger1   default   http://event-display.default.svc.cluster.local   True

$ ./kn source cronjob list
NAME              SCHEDULE      SINK                CONDITIONS   READY   REASON
my-cron-trigger   * * * * */1   svc:event-display   7 OK / 7     True

$ ./kn source apiserver list
NAME        RESOURCES        SINK                CONDITIONS   READY   REASON
k8sevents   Event:v1:false   svc:event-display   6 OK / 6     True

$ ./kn service list
NAME            URL                                                                                                                   LATEST                  AGE    CONDITIONS   READY   REASON
event-display   http://event-display-default.myclusterguoyc-5290c8c8e5797924dc1ad5d1b85b37c0-0000.au-syd.containers.appdomain.cloud   event-display-jvqmp-1   142m   3 OK / 3     True
```

Proposed changes:

1. Change `SUBSCRIBER_URI` in trigger list to `SINK` as cronjob list and apiserver list
2. Add `AGE` as service list

@rhuss what do you mean by `Also, the condition and reason columns should be the same as for services.`? I think `CONDITIONS`, `READY` and `REASON` are already same as service list.

**Comment by rhuss** [comment]
I'm now not 100% sure anymore whether we should move from `SUBSCRIBER_URI` to `SINK`, but maybe rename `SUBSCRIBER_URI` to `SUBSCRIBER`, as in the underlying CR there are named `subscriber` and `sink`, so we should not invent our own naming for the subscriber as this very likely confuses people more than it helps.

wrt/ the conditions, ready and reason columns I'm not sure anymore what I meant. So happy to leave it as it is now (note to myself: be more precise when creating issues ;-)

Agreed to adding the age column to sources and triggers.

**Comment by daisy-ycguo** [comment]
> I'm now not 100% sure anymore whether we should move from `SUBSCRIBER_URI` to `SINK`, but maybe rename `SUBSCRIBER_URI` to `SUBSCRIBER`, as in the underlying CR there are named `subscriber` and `sink`, so we should not invent our own naming for the subscriber as this very likely confuses people more than it helps.
> 

Do you want to keep the uri as `subscriber` or the same patter `svc:event-display` as cronjob and apiserver sources ?

> wrt/ the conditions, ready and reason columns I'm not sure anymore what I meant. So happy to leave it as it is now (note to myself: be more precise when creating issues ;-)
> 
> Agreed to adding the age column to sources and triggers.

**Comment by rhuss** [comment]
> Do you want to keep the uri as `subscriber` or the pattern `svc:event-display` as subscriber, same as sources ?

yes please
