### ISSUE TITLE
Error when multiple filter with the same name are given for kn trigger

### ISSUE THREAD

**Issue by rhuss** [knative/client#569]
In `kn trigger --filter type=bla --filter type=blub`, "blub" will silently win. As this is very likely not the user's intent, an error should be thrown instead.

Same btw for "kn service create --env". The check could be part of a unified list-option handling.

**Comment by duglin** [comment]
to be clear, you mean that while `--filter` and `--env` are additive, multiple occurrences of the flag builds up a list, if the values within the list contain repeats of the "key" (e.g. filter type or env name) then we should consider alerting the user, right?

**Comment by rhuss** [comment]
Exactly, if you put the same key on the same CLI call like in `kn trigger create bla --filter type=foo --filter type=bar`. Currently `type=foo` is just ignored as its overwritten by `type=bar`. IMO an error should be given instead, as this very likely not what the users wants (and provided both options by accident).

**Comment by MIBc** [comment]
I'd like to try.
