### ISSUE TITLE
Introduce common utility method for handling map like options

### ISSUE THREAD

**Issue by rhuss** [knative/client#577]
As we have now multiple options which are of map type we should use a common codebase to guarantee that they are all handled the same

The options I have in mind are (but maybe more):

* --env, --annotations and --label for services
* --filter for triggers
* ~~--traffic for services~~ (see comments below why `--traffic` is special)

The behaviour should be (using `--env` as an example):

* `--env a1=b1 --env a2=b2` should add both env variables
* `--env a1` should set a1 to empty string
* `--env a1-` should remove the environment variable for update and an error for create
* `--env a1=b1 --env a1=b2` should be an error as the same key can not be specified on the same command line

I could imagine to have a function signature like

```golang
parseMapOptions(key string, options []string) (map[string]string, error)
```

and a usage

```golang
filters, err := parseMapOptions("filter", f.Filters)
```

**Comment by navidshaikh** [comment]
The difference here with `--traffic` flag is, its explicit; whats given on CLI gets into the spec, no union of existing+given traffic targets. Flag `--traffic` doesn't support removal sign `-` too.

**Comment by rhuss** [comment]
@navidshaikh  ok, I see, so let's remove `--traffic` from the list.

However, there are still enough other use cases which justify a common approach (hopefully ;)

**Comment by MIBc** [comment]
The env, label and annotations option use a common method `mapFromArray` to deal with string list.
Is it ok to judge same key in it ?

**Comment by daisy-ycguo** [comment]
I think this one is related with [issue 565](https://github.com/knative/client/issues/565) . 

I propose to add a new flag type under `pkg/kn/commands/flags`, named "ArrayList" to support all array flags, and then we can add a method `parseMapOptions(key string, options []string) (map[string]string, error)` to type `ArrayList`.

**Comment by rhuss** [comment]
> The env, label and annotations option use a common method `mapFromArray` to deal with string list.
> Is it ok to check same key in `mapFromArray`?

Wdym with "check same key" ? Actually this method does similar the same but does not handle removal of keys with minus suffix. So maybe this method can replaced or extended by the algorithm described above.

**Comment by rhuss** [comment]
> I think this one is related with [issue 565](https://github.com/knative/client/issues/565) .

Yes

> I propose to add a new flag type under `pkg/kn/commands/flags`, named "ArrayList" to support all array flags, and then we can add a method `parseMapOptions(key string, options []string) (map[string]string, error)` to type `ArrayList`.

Sorry, I don't get why adding of new type would make things easier than a simple function. Would be cool if you give an example.

**Comment by daisy-ycguo** [comment]
> Sorry, I don't get why adding of new type would make things easier than a simple function. Would be cool if you give an example.

My mistake. no need to add a new type.

**Comment by MIBc** [comment]
Can filter set like `--fliter f1=` ?  @rhuss

**Comment by navidshaikh** [comment]
> Does that mean filter type value can be empty?

Yes, empty value indicate all strings match.

```
// TriggerFilterAttributes is a map of context attribute names to values for
// filtering by equality. Only exact matches will pass the filter. You can use the value ''
// to indicate all strings match.
type TriggerFilterAttributes map[string]string
```
[source](https://github.com/knative/eventing/blob/release-0.11/pkg/apis/eventing/v1alpha1/trigger_types.go#L113-L116)

**Comment by navidshaikh** [comment]
For the case to error out if an env is asked to remove while creating service:
I think, asking to remove a preset env in the image during container creation, could be a valid use case?

**Comment by navidshaikh** [comment]
This was tagged for v0.12.0, there is only one case we'd need to discuss and fix; whether to support removing env var while creating service? (we can create a separate issue and tag to an open milestone) @rhuss 

Closing this since most of the cases are addressed.

/close

**Comment by rhuss** [comment]
> I think, asking to remove a preset env in the image during container creation, could be a valid use case?

I don't think that K8s / Knative offers a way to remove an env var coming from a container image.

However, I wouldn't mind to let it be a no-op. But maybe one should adopt the create-message to remove the removal syntax.

But I agree to close this and move it any remaining work to a new issue.
