### ISSUE TITLE
Support a flag to set ImagePullPolicy

### ISSUE THREAD

**Issue by duglin** [knative/client#578]
## In what area(s)?

Classifications:
/kind good-first-issue
/kind feature
/kind proposal
/kind doc

## Describe the feature:

As I'm making changes to my app and redeploying it (over and over), I usually do ` kn service delete...` followed by `kn service create...`. However, as I rebuild my container image each time there is no guarantee that the new image will be picked up if it's already in the cache. As a result I find that I need to drop down to yaml to do the `create` so that I can specify `imagePullPolicy: Always`. It would be nice if there was some `kn` flag I could specify to give me the same net result.

**Comment by MIBc** [comment]
I also think `imagePullPolicy` is needed. Because I have download image, it is unnecessary to pull image again.

**Comment by MIBc** [comment]
I'd like to slove it .

**Comment by rhuss** [comment]
> also think `imagePullPolicy` is needed. Because I have downloaded image, it is unnecessary to pull image again. Especially the image tag is latest.

I agree that this is a needed and good feature, but mostly for the other way around: To pull an image anyway if its already cached.

However, I wonder whether we should ignore that flag if a pinned image is used (i.e. an image which uses a digest instead of tag), because refetching an image by hash wont change anything.

**Comment by duglin** [comment]
Wouldn't that already be handled by the server? meaning, I'm not sure we need to do anything about it. If the server does nothing, then it does nothing. If it ends up doing something then it would be bad if we blocked it. I'd only bother to do something about it if it was an error case that and we wanted to block the creation of the KnService as a result... but again, the server should do that via an admission controller so it can catch the yaml case too.

**Comment by rhuss** [comment]
yes, you are correct, that's a server concern. So fine to not include it on the client-side.

**Comment by sixolet** [comment]
Won't fix.

**Comment by duglin** [comment]
Why was this closed? It’s a valid option isn’t the yaml

**Comment by rhuss** [comment]
It's not part of the Knative serving spec and should be completely ignored according to https://github.com/knative/client/pull/583#issuecomment-568509784 

There are other parts in `ContainerSpec` which are valid for the  K8s schema but not for Knative serving (like multiple ports and other fields). Afaiu they should be just ignored or an error thrown when provided in a Knative context. As for `imagePullPolicy`, which should be either ignored or an error should be raised when given. 

So it doesn't make sense to allow for kn to be able to specify this field if it is not part of the Knative contract.

**Comment by duglin** [comment]
that field is not nullified, it is passed thru to the pod created. You can see it in the list of "allowed fields" here: https://github.com/knative/serving/blob/7e47c0e27b03a3b921280a5e09b058424cbdda7b/pkg/apis/serving/fieldmask.go#L201

**Comment by duglin** [comment]
Also, the property is in:  https://github.com/knative/docs/blob/master/docs/serving/spec/knative-api-specification-1.0.md#container

**Comment by rhuss** [comment]
> that field is not nullified, it is passed thru to the pod created. You can see it in the list of "allowed fields" here: https://github.com/knative/serving/blob/7e47c0e27b03a3b921280a5e09b058424cbdda7b/pkg/apis/serving/fieldmask.go#L201

It seems that there is a strong opinion that this is considered to be a bug. I can't really judge on whether it's part of the Knative API (and the code is correct) or it's not part of the Knative API and it's a bug that `imagePullPolicy` is not erased. @sixolet @mattmoor Any comments on this ? If its a bug we should indeed open an issue at knative-serving.

**Comment by duglin** [comment]
I think the "bug" is in reference to it not pulling the latest, not the presence/use of the pullPolicy flag

**Comment by xunfeng1980** [comment]
Won't fix ?

**Comment by rhuss** [comment]
@xunfeng1980 as discussed above, it is considered to be a server-side issue. Feel free to open an issue on knative/serving , referencing this one.

**Comment by duglin** [comment]
See https://github.com/knative/specs/blob/main/specs/serving/knative-api-specification-1.0.md it is formally part of the spec. We should support it in the CLI.

**Comment by rhuss** [comment]
> See https://github.com/knative/specs/blob/main/specs/serving/knative-api-specification-1.0.md it is formally part of the spec. We should support it in the CLI.

According to https://github.com/knative/specs/blob/main/specs/serving/knative-api-specification-1.0.md#container:

> However, Knative resolves the image to a digest. The pull policy will be applied against the digest of the resolved image and not the image tag.

@duglin what is the use case to refetch a resolved image again from the registry with pull policy `Always` ? I see potentially a use case for `Never` or `IfNotPresent` (the default), but that won't solve your original use case to update a changed image with the same tag.

**Comment by duglin** [comment]
One need for “always” is to force a check of the permissions on the image. Today Kube won’t check the user has permission to use the cached image if it doesn’t go back to the registry.  This is a security hole if someone manages to determine the sha of someone else’s cached image that happens to be on that node.

**Comment by rhuss** [comment]
Fair point. Let's add it to the backlog.

I just want to make sure that `Always` will *not* solve the original use case  as put in the initial description (which also does not work by modifying the yaml directly): 

> However, as I rebuild my container image each time there is no guarantee that the new image will be picked up if it's already in the cache'. As a result I find that I need to drop down to yaml to do the create so that I can specify imagePullPolicy: Always

**Comment by csantanapr** [comment]
I would like to see this  implemented soon

I'm trying to come up with a workflow using minikube, building the image local to minikube (no need to push to a registry) and then create kn service using the image dev.local/foo  it currently doesn't work because I need to set imagePullPolicy: Never and this force me to work with a yaml file and not use the CLI. (using dev.local helps skipp disgest resolution.

For example:
kn quickstart minikube
eval $(minikube -p knative docker-env)
docker build . -t dev.local/foo
kn service create foo --image dev.local/foo
It doesn't work pull image error.
Make sense to add a flag?
kn service create foo --image dev.local/foo --pull-policy never
