### ISSUE TITLE
DEVELOPMENT.md should describe how to update dependency versions

### ISSUE THREAD

**Issue by bbrowning** [knative/client#58]
Something like https://github.com/knative/serving/blob/1034bf9b3fc304a944cfccb078198bb26c36ce31/DEVELOPMENT.md#iterating

Especially since we're different from other Knative repos - I was able to figure out, with some internet searching, that to update test-infra in my particular case I needed:

```shell
GO111MODULE=on go get -u github.com/knative/test-infra
```

**Comment by bbrowning** [comment]
And, as it turns out, test-infra is the only thing that is also vendored so I didn't end up updating it properly anyway. I also had to:

```shell
GO111MODULE=on go mod vendor
```

The .gitignore is setup so that anything added to `vendor/` other than test-infra stuff gets ignored.

**Comment by rhuss** [comment]
👍 this explanation should become definitely part of the developer handbook as described in #652 that should be part of this repository. I will update the parent issue with this task and close this one for now.
