### ISSUE TITLE
Consider using `--concurrency` instead of `--concurrency-limit`

### ISSUE THREAD

**Issue by duglin** [knative/client#584]
## In what area(s)?

Classifications:
/kind good-first-issue
/kind proposal

## Describe the feature:

Consider using `--concurrency` instead of `--concurrency-limit` to more closely align with the yaml that uses `containerConcurrency`. The use of the word `limit`, while technically accurate, is a bit of a deviation from what people would expect if they bounce between the yaml and `kn`.  Plus, it's less typing  :-) 

This issue isn't too technical, but more of a UX concern.

**Comment by cppforlife** [comment]
might as well go with `--container-concurrency`

**Comment by duglin** [comment]
While it's a bit long, I would prefer that to what we have today since at least it's a direct (word for word) match and doesn't require thinking :-)

**Comment by rhuss** [comment]
@duglin what would you do then with the `--concurrency-target` option ? Up to now both are on the same level in the options, which is not so bad IMO. We could think about a `--concurrency` which then set botj, target and limit to the same value.

wdyt ?

**Comment by duglin** [comment]
The annotations in question are:
```
- autoscaling.knative.dev/target
- autoscaling.knative.dev/containerConcurrency
```
And today these map to `kn` options as:
```
--concurrency-target
--concurrency-limit
```
Based on a slack chat with @vagababov, `target` is only meaningful when CC is zero, so setting them both to the same value doesn't seem right, except in the zero case.

w.r.t. naming... it's hard. It would be easier if the annotations were more consistent. E.g. if it was `containerTarget`. "Target" is just such a generic term that using that as-is on the cmd line doesn't seem friendly enough, so prefixing it with `concurrency` (while inconsistent) is probably the right thing to do.

I think I'm leaning towards:
```
--concurrency-target
--concurrency
```
because even though `concurrency` isn't 100% aligned with the yaml, this does present some consistency between these two options. Going with `--container-concurrency`, while aligned with the yaml, I think is harder for people to mentally align with `--concurrency-target`.

**Comment by rhuss** [comment]
> - autoscaling.knative.dev/target
> - autoscaling.knative.dev/containerConcurrency

To be precise, for the `--concurrency-target` you are right, however for `--concurrency-limit` we are using the CRD field `.spec.containerConcurrency`, not an annotation.

I don't like to be inconsistent with respect to the concurrency option naming. So I still like the current, symmetric version of `--concurrency-limit` and `--concurrency-target`.

**Comment by rhuss** [comment]
But maybe I don't understand those options not properly. My mental picture is of that of a soft (target) and hard (limit) limit. But I might be wrong here, and need to catch up.

**Comment by duglin** [comment]
Yup I’ve about soft vs hard limits AFAIK. But the soft limit only applies when cc is zero

Thanks,
-Doug

**Comment by maximilien** [comment]
Agree with @rhuss with the beauty and simplicity of `concurrency-target` and `concurrency-limit`.

Closing this unless others can chime with better arguments.
