### ISSUE TITLE
Reconsider how we lock an image digest

### ISSUE THREAD

**Issue by duglin** [knative/client#585]
if I do this:
```
$ kn service create echo --image=duglin/echo
$ kn service update echo --env foo=bar
```
then the KnService will look something like this:
```
$ kubectl get ksvc/echo -o yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: "2019-12-20T21:26:18Z"
  generation: 2
  name: echo
  namespace: default
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: duglin/echo
      name: echo-pbvrg-2
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: foo
          value: nar
        image: index.docker.io/duglin/echo@sha256:1dfe8aeec2bb1cbf31d780d29205044a29437bda1f7dec3a3e603da4129de96d
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  ...
```

Notice the image name in the `spec` is `index.docker.io/duglin/echo@sha256:1dfe8aeec2bb1cbf31d780d29205044a29437bda1f7dec3a3e603da4129de96d`.  I understand why `kn` is doing this, however, this isn't side-effect free.

I was playing with something that basically watched KnServices and would periodically take some action that uses the `spec.image` name. However, I don't want the resolved digest, I want the actual value specified by the user, which is usually what the `spec` is for.  If I wanted the digest I would grab what's in the `status` section. Today all secondary processors that might be watching KnServices/Revisions will now need to look for the `client.knative.dev/user-image` annotation and use that instead of `spec.image`, but only when `kn` was used to manage the KnService. 

My question... is this really what we want? Should other processors (watchers) be aware of Knative clients (even `kn`) that might change the user's `spec` on them and react accordingly? Or should users of `kn` really be required to know when there are "watchers" and turn off the `kn` feature?

**Comment by rhuss** [comment]
The issue is, that an image tag is not a version and can be moved anytime. A user would be suprised though, that when she changes e.g. a resource limit, that a new image is fetched as a side effect, too because someone updated the image tag in the registry. That's a real problem for `latest` images, but also for other tags (e.g. often a tag is also kind of a moving tag, which moves along (e.g. like a `1.6` is moved along `1.6.0`, `1.6.1`, ...). Kind of like a symbolic link).

Said that, you can use the `kn` option `--no-lock-to-digest` to avoid this locking behaviour (but locking is the default).

I hope I summarized the motivation behind this design correctly, but @sixolet please correct me if I missed something.

BTW, there are many other examples where a controller changes the spec of a Kubernetes resource, too (e.g. like adding a loadBalancerIP for Services). So changing a spec is not something which should be really surprising to a k8s user.

**Comment by duglin** [comment]
I understand why kn does this. What I'm questioning is whether it's the correct choice.

re: changing the user's `spec`. In my time in Kube I've heard very different opinions on this - from very senior (and opinionated :-) ) people. Most seem to think it's bad form to do so since the input data should be under the user's control. Adding things (like the LB-IP you mentioned) is 'adding' not changing, but I'm sure there are cases where we probably do modify the user's data. Having said that, I personally have no issue with changing the spec when it makes sense and it's what the user would expect.

In this case though, I'm not sure it's what the user would expect since this behavior will vary depending on which CLI they use. For example, if they use `kn` their image name will change. If they use `kubectl` it will not. And I can easily image cases where two different devs work on the same KnService and one uses kn and the other uses kubectl+yaml. Or even the same user uses `kn` to create it but then some UI (that uses the REST API) to modify it later on. That's going to present an inconsistency that will be hard to explain to people.

I would be less concerned about this particular changing of `spec` if it were done on the server side so regardless of which CLI was used all users would get the same behavior.   And now when I bring into the picture some 3rd party controller that wants to work on the data that the user actually provided, things get a bit messy.

Even w/o a controller, imagine a UI displaying the image name and it changing from what the user specified in a previous window. The UI, if they wanted to keep things pretty and consistent, will now need to know about the `kn` annotation that's being used to store the original name.

I also wonder if there's a bug though... take this case:
- create the KnService via kn
- user sees the image name as they specified it
- user edits the KnService via kn
- issue 1: now the image name changed. Why now? Why wasn't it changed upon create? This seems inconsistent.
- user edits the KnService's image via kubectl (or some other tool which uses the API and not `kn`), which some UI's will do
- issue 2: the image name will now NOT be the digest. However, the `kn` annotation is still there. So even if some tooling does know about kn's annotation, they won't know whether the info there is accurate or not. In this case it's not, it's old.

This particular feature of `kn` seems to have been done with the assumption that it is the only CLI/code that will ever modify the KnService resource so it can make assumptions and decisions that only `kn` needs to know about it.  Unfortunately, this isn't the case.

**Comment by rhuss** [comment]
I also would highly prefer a server mechanism for locking down an image to its digest. I'm not sure why this is not possible, but I can vaguely remember that @sixolet mentioned that this is a complex issue and a client-side locking was the best what could be done.

> * issue 1: now the image name changed. Why now? Why wasn't it changed upon create? This seems inconsistent.

Because you know the digest only after the image has been pulled, which is not the case during creation. Of course, for the sync case, we could automatically do an update of the image field as soon as the service is up and running. For the `--no-wait` case, we can't do this (but the server could do), so it's probably better to stay consistent within the client (i.e `--wait` and `--no-wait` behave the same when it comes to image digest resolution).

**Comment by duglin** [comment]
Well, what's interesting is that if people are ok with the client modifying the spec's image field, then they should be ok with the server side doing it and do it even on the initial create.  This would provide the consistency that seems to be missing.  I think in the past having the server modifying the spec wasn't considered and the focus was more on trying to do a diff of some kind to know when the image field changed during an update. But perhaps I'm remembering in correctly.

**Comment by sixolet** [comment]
We did indeed talk about having a spec field for digest alongside the image field, in our first serving API decision about this particular usability issue, but for various reasons rejected that as the greater evil competed to client-side image setting. 

The current client side design does preserve the image to show the user.

**Comment by duglin** [comment]
> We did indeed talk about having a spec field for digest alongside the image field

I was thinking more about doing exactly what `kn` does, replace the `image` field's value instead of creating a side field, but on the server since it has the info.

> The current client side design does preserve the image to show the user.

yes the info is there but it can be stale (wrong) if the KnService is updated via a non-`kn` client.
It's the inconsistency that's being introduced that I'm worried about. While we can't know how often people will switch CLIs, I'm pretty sure it's safe to say that there will be times when someone might use `kn` and something else (`kubectl` or some UI) to manage a particular KnService and they're going to see this inconsistency/issue.

**Comment by duglin** [comment]
I still think this is an issue
/remove-lifecycle stale
