### ISSUE TITLE
Could e2e tests run faster?

### ISSUE THREAD

**Issue by maximilien** [knative/client#598]
## In what area(s)?

e2e

Classifications:
> /kind good-first-issue
> /kind tests

## Ask your question here:

Could the e2e tests be faster. There are places for possible easy optimizations.

For instance @navidshaikh has identified a `time.Sleep(20 * time.Second)` in line of [commons.go](https://github.com/knative/client/blob/e0877da3d66e0c93a51eac0a3c39577bbe3c31d3/test/e2e/common.go#L65) which perhaps could be reduced or even removed all together?

**Comment by MIBc** [comment]
Why does it sleep 20s?

**Comment by maximilien** [comment]
Originally added to ensure that the namespace is created since subsequent tests need the namespace to perform their work. Of course, optimally it should just check that the namespace is created vs waiting.

Let me see if I can add this.
