### ISSUE TITLE
Move client conventions from serving repo

### ISSUE THREAD

**Issue by sixolet** [knative/client#6]
As we do that, we should conform it to the commands we plan to build in the reference CLI.

**Comment by navidshaikh** [comment]
@sixolet How should the resolution of this issue look like?

Move the [Client convention doc](https://github.com/knative/serving/blob/master/docs/client-conventions.md) in client repo and 

> we should conform it to the commands we plan to build in the reference CLI.

means, we reference the issue numbers pointing to individual implementation(s) of the command(s) ?

**Comment by maximilien** [comment]
Not sure I understand this. Can you elaborate a bit when you have a second. Thx.

**Comment by rhuss** [comment]
I guess its about moving [this document](https://github.com/knative/serving/blob/master/docs/client-conventions.md) to this repository.

**Comment by maximilien** [comment]
OK cool

**Comment by scottilee** [comment]
Looks like this has been completed but any opposition to moving https://github.com/knative/client/tree/master/conventions inside https://github.com/knative/client/tree/master/docs?

**Comment by sixolet** [comment]
I put it outside docs because it's not strictly "how to use the client or client libs" it's "how to develop on"
