### ISSUE TITLE
[e2e-tekton] Failed to pull image from gcr registry while creating service

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#601]
e2e tests for tekton pipelines runs nightly. The pipeline in these e2e tests, builds and pushes a helloworld container to gcr registry, a knative service is created from the image from gcr registry.
The nightly job is failing ever since its setup https://testgrid.knative.dev/client#tekton

helloworld container is built and pushed fine, however service deployment is failing with `ErrImagePull`, detailed error message from [logs](https://00e9e64bacb00f4d8a80959745d90b5789929082165b615117-apidata.googleusercontent.com/download/storage/v1/b/knative-prow/o/logs%2Fci-knative-client-tekton%2F1214169909014040576%2Fartifacts%2Fk8s.dump.txt?qk=AD5uMEtrj_1wnGxsX7fo_FLuFBwhGPeio5rKaylZ1DC9Z-TkI3tdwvF8MTfrvoPjM2n1pNQb_TNOqckNG7e5QNbzPBBgr7i3EATWGN5SYlzAaIZW3cd0QjIJYyKciqBzds68wZLLwHqrhY3JkewE-G6XtlzUUQ23w1-mtFwWTMSqYKWE0dEvXuixLVmYiWRgs1Gos2eA4ybYzAXOwgriN6_7KoWHwElC7o82gklRjAWy-QzIMHrojJ1s6NNr9omfys743F3FuaiJRVu3SpCM08gawxYjDMBxJNaxmNaJjadG-0y3EbXPmiECmil7TDCFcurhbvVy6iiE8NM2MMZoHszqlL9mpSTJWPJQ7Uf8lYoFjAElYG3Kkfnt8xcUEezwSmy_fF5JBnSrqr3_RLpOxVKjvXt0K48MY2dT9kn2gsKUvdioLTCBg_erWXAJ9P0E8UbS8ne5iCgXpZ0rI2qe9p38qvN3bg10WK4mljICoky9VOhmhOnzCuD2FCz3bw605flAiWfijg7bJ3JgnzwRf3iBI04i1U3xmMBEYCz2T-6eKvVVLFOmKIWY8Cpeij3hGoZtDuy_M-O_VrVPr7AXTFc_L12ODGYTURZsxdwQcgaQsI-tvc15X-dK8r3RebUgU98D-dnjPw9cshnAZsVp4llxpbw9x5DtB3KfyIeY0uXPFzmRc_vZjaqJibzeltnJMpzra8fpdfoqPOXinExGCgvWCmSsM-espw_eYBm9ZCMp3OaRSgsXBqrAKkazZnXUC83V35mnaFj3A7d2ymx7554SxcpNmInCcwldGPe8lUnvNTNoyIKIJErutKuKzl8NdcvGgUIG1brVkGinFoG2MuOatSzhkfxl77Qj8ku5Z3EakbFkCi4HD48C_Dh3r2qdyiKo81l7IU2Z) :
```
 Failed to pull image 
"gcr.io/knative-boskos-40/kclient-e2e-img/16616/helloworld@sha256:aaeb5f19c8beccfcf1e855c67591ccbc828c75f017bb8e2c866fc65333cc8488": 
rpc error: code = Unknown desc = Error response from daemon: mediaType in manifest should be 
'application/vnd.docker.distribution.manifest.v2+json' not ''
```

The image built by `buildah` has manifest type
```
        "ManifestType": "application/vnd.oci.image.manifest.v1+json",
```

when this image is pushed to gcr registry and pulled while creating the service daemon is reporting mediaType `''` and expecting `application/vnd.docker.distribution.manifest.v2+json`.

**Comment by navidshaikh** [comment]
Docs shows OCI as supported image-formats https://cloud.google.com/container-registry/docs/image-formats, however when pushed an OCI image via buildah to gcr, the manifest type reported while pulling the image by daemon is empty ' '.

If asked to build an image in `docker` format as `buildah bud --format=docker` it works (default is `oci` format).

How can I list the container runtime used in CI environment and check if it supports OCI format?
/cc @adrcunha @ImJasonH

**Comment by adrcunha** [comment]
Prow jobs use regular docker, like here:

https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_docs/2087/pull-knative-docs-integration-tests/1215026080310628353/build-log.txt

```
>> docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Does that help?

**Comment by adrcunha** [comment]
As Navid pointed out in the OP, the image is fine in GCR:

![image](https://user-images.githubusercontent.com/35786489/72114538-c1079800-32f8-11ea-99d3-c485fd38e5c2.png)

**Comment by navidshaikh** [comment]
Thanks for the logs and link!
Yes, the GCR registry stores and serves the OCI images fine.

Its the daemon prompt that reading the empty manifest `' '` while pulling image and expecting `'vnd.docker.distribution.manifest.v2+json'`.

The referenced docker version has OCI image support, tested pulling image from GCR registry. 

For now as a work around we're pushing the docker formatted image to gcr instead of OCI and it works.

Is there a way to hook into the CI cluster environment while a PR jobs are executing ?

**Comment by adrcunha** [comment]
Theoretically, yes, since it's matter of logging into a running pod. But it would involve some permission changes and retries. Before we go that route, if you run

`docker run -it --entrypoint /bin/bash gcr.io/knative-tests/test-infra/prow-tests:stable`

you'll be in the test job environment and you can investigate/play as much as you want. Would that help?

**Comment by navidshaikh** [comment]
I can pull and run `prow-tests:stable` image fine, but it doesnt give me the setup for test I'd like to run. The test I would like to run is,

```bash
kn service create svc --image gcr.io/knative-boskos-40/kclient-e2e-img/16616/helloworld@sha256:aaeb5f19c8beccfcf1e855c67591ccbc828c75f017bb8e2c866fc65333cc8488
```
and verify if service is created in the environment (similar to one deployed for CI test job environment).
Can you please give it a try?

**Comment by navidshaikh** [comment]
FYI - The nightly e2e tests went fine https://testgrid.knative.dev/client#tekton

**Comment by adrcunha** [comment]
The prow-tests image doesn't contain any SUT, only the tools. You'll need to build `kn`, and looks like you're gonna need to install Knative on a cluster as well to run the `kn` command, right? Yeah, that can get complicated to setup locally, although not impossible. Let me take a stab at that...
