### ISSUE TITLE
Add support for private KnServices

### ISSUE THREAD

**Issue by duglin** [knative/client#606]
## In what area(s)?

/kind good-first-issue
/kind feature
/kind proposal

## Describe the feature:

It would be nice if there was a way to specify that a knService should not have an external endpoint.  This means setting the label `serving.knative.dev/visibility: cluster-local`.

**Comment by rhuss** [comment]
Good point. I suggest introducing an option `--cluster-local` and `--no-cluster-local`.

**Comment by rhuss** [comment]
The handling could be similar like for `--concurrency-target`

**Comment by maximilien** [comment]
@duglin you OK with @rhuss suggested flags? Seems reasonable to me.

**Comment by maximilien** [comment]
Also, I am assuming this is both at `create` and `update` service.

**Comment by duglin** [comment]
yep sounds good on both questions
