### ISSUE TITLE
subcommand is required Message When Using kn Root Command

### ISSUE THREAD

**Issue by danielhelfand** [knative/client#612]
## In what area(s)?

/kind good-first-issue
/kind cleanup

## What version of Knative Client?

Master branch

Latest release at this time:

```
Version:      
Build Date:   
Git Revision: 
Supported APIs:
* Serving
  - serving.knative.dev/v1alpha1 (knative-serving v0.11.0)
* Eventing
  - sources.eventing.knative.dev/v1alpha1 (knative-eventing v0.11.0)
  - eventing.knative.dev/v1alpha1 (knative-eventing v0.11.0)
```

When running the root command `kn`, the message `subcommand is required` appears: 

```
Manage your Knative building blocks:

* Serving: Manage your services and release new software to them.
* Eventing: Manage event subscriptions and channels. Connect up event sources.

Usage:
  kn [command]

Available Commands:
  completion  Output shell completion code
  help        Help about any command
  plugin      Plugin command group
  revision    Revision command group
  route       Route command group
  service     Service command group
  source      Event source command group
  trigger     Trigger command group
  version     Prints the client version

Flags:
      --config string        kn config file (default is $HOME/.kn/config.yaml)
  -h, --help                 help for kn
      --kubeconfig string    kubectl config file (default is $HOME/.kube/config)
      --log-http             log http traffic
      --lookup-plugins       look for kn plugins in $PATH
      --plugins-dir string   kn plugins directory (default "~/.kn/plugins")

Use "kn [command] --help" for more information about a command.
subcommand is required
```

When running `kn -h`, the message does not appear. `-h` is not a subcommand, so it's somewhat of an awkward message to communicate to users that a subcommand is required since it's not.

It's a very common use case to run the root command to get a general overview of information about the CLI, so it probably makes sense to not display the message since it seems to imply that something is wrong.

`Use "kn [command] --help" for more information about a command.` should probably be sufficient to inform users about what this message is trying to communicate.

## Steps to Reproduce the Problem

Run `kn`

**Comment by danielhelfand** [comment]
Removing this [line](https://github.com/knative/client/blob/de7e3880d4cd8a6cf49397039de4cf8d84e7d7a3/cmd/kn/main.go#L38) here should resolve this.

**Comment by navidshaikh** [comment]
Thanks @danielhelfand! 

> Use "kn [command] --help" for more information about a command. should probably be sufficient to inform users about what this message is trying to communicate.

+1
