### ISSUE TITLE
generated negative flag `--no-xxx` description are not well capitalized

### ISSUE THREAD

**Issue by maximilien** [knative/client#636]
## In what area(s)?

utilities

Classifications:
> /kind good-first-issue
> /kind cleanup

## Describe the feature:

Found during PR #629. It's a _nitpick_ issue but one that should eventually be addressed nonetheless.

When autogenerating the negative of a `bool` flag, e.g., `--cluster-local` and `--no-cluster-local`, the description of the positive flag is used to create the description of the negative by adding: `do not ...` so in this case:

```text
do not Specify that the service be private. (--no-cluster-local will make the service publicly available (default true)
```

which is not correct... Same for other `--no-xxx` flags like `--no-lock-to-digest` whose positive description starts with lower case. Suggestion is to make the generated description smartly generate:

```text
Do not specify that the service be private. (--no-cluster-local will make the service publicly available (default true)
```

So add `Do not` and correctly capitalize the start of the positive description.

cc @navidshaikh

**Comment by rhuss** [comment]
Good point and no nitpicking at all.  We should definitely streamline the help messages. This is also true for shared create/update help message, where an operation like removing an env var by suffixing the name with - is not really useful for  a `create` (as there is guaranteed no such env var yet)
