### ISSUE TITLE
Dont generate and apply BYO revision name if Config fields are unchanged

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#646]
## In what area(s)?
serving

## What version of Knative Client?
nightly  / released

## What version of Knative Serving running on your cluster?
nightly

## Expected Behavior
No revision should be generated if Configuration fields are unchanged.

## Actual Behavior
New revisions are generated with only Configuration diff being (BYO) revision name.

#### Without BYO revision names:
1. Create a service `svc` (turn off BYO revision name with `--revision-name=""`)
```
➜  client git:(master) ./kn service create svc --image gcr.io/knative-samples/helloworld-go --env TARGET=BYO --revision-name=""
Creating service 'svc' in namespace 'default':

  0.171s The Route is still working to reflect the latest desired specification.
  0.266s Configuration "svc" is waiting for a Revision to become ready.
  0.382s ...
  3.817s ...
  3.888s Ingress has not yet been reconciled.
  4.577s Ready to serve.

Service 'svc' created to latest revision 'svc-t6274' is available at URL:
http://svc.default.example.com
```
2. Update service with same flags 
```
➜  client git:(master) ./kn service update svc --image gcr.io/knative-samples/helloworld-go --env TARGET=BYO --revision-name=""
Updating Service 'svc' in namespace 'default':

  0.005s Ready to serve.

Service 'svc' with latest revision 'svc-t6274' (unchanged) is available at URL:
http://svc.default.example.com
```

3. No new revision generated for update
```
➜  client git:(master) ./kn revision list
NAME        SERVICE   TRAFFIC   TAGS   GENERATION   AGE   CONDITIONS   READY   REASON
svc-t6274   svc       100%             1            69s   3 OK / 4     True    
```

#### With BYO revision names:
1. Create a service `foo`
```
➜  client git:(master) ./kn service create foo --image gcr.io/knative-samples/helloworld-go --env TARGET=BYO                   
Creating service 'foo' in namespace 'default':

  0.089s The Route is still working to reflect the latest desired specification.
  0.147s Configuration "foo" is waiting for a Revision to become ready.
  4.256s ...
  4.449s Ingress has not yet been reconciled.
  4.984s Ready to serve.

Service 'foo' created to latest revision 'foo-pylmd-1' is available at URL:
http://foo.default.example.com
```

2. Update service with same flags with BYO revision name (default behavior)
```
➜  client git:(master) ./kn service update foo --image gcr.io/knative-samples/helloworld-go --env TARGET=BYO
Updating Service 'foo' in namespace 'default':

  3.416s Traffic is not yet migrated to the latest revision.
  3.573s Ingress has not yet been reconciled.
  4.068s Ready to serve.

Service 'foo' updated to latest revision 'foo-bqwrt-2' is available at URL:
http://foo.default.example.com
```

3. List revisions and notice new a revision is generated
```
➜  client git:(master) ./kn revision list -s foo
NAME          SERVICE   TRAFFIC   TAGS   GENERATION   AGE   CONDITIONS   READY   REASON
foo-bqwrt-2   foo       100%             2            13s   4 OK / 4     True    
foo-pylmd-1   foo                        1            32s   4 OK / 4     True   
```

<hr>
There should be same behavior whether revision names are generated client or server side.

**Comment by rhuss** [comment]
Tbh, I'm not sure which behaviour is supposed to be the correct one, as the update operation specifies an image without a digest (but a 'latest' tag). Ideally a new revision should only be created if the the image's digest has been changed. I'm not sure if the client can detect this, when in the BYO case it has to decide whether to create a new revision name or not. In the non-BYO case, the server can decide that and in this case decides to *not* create a new revision. But the client decides to always create a new revision name when an `--image` tag is provided. That's my guess and I'm not sure how to resolve this issue. Tbh, I would be ok to make the update on the client-side if a user provides a non-digested image name as I suppose that the user knows what she does.

But another point: I'm still not 100% sure whether BYO should be the default case.

**Comment by navidshaikh** [comment]
Even if provided an image with digest, the behavior is same:

```
➜  client git:(master) kn service create foo --image gcr.io/knative-samples/helloworld-go@sha256:5ea96ba4b872685ff4ddb5cd8d1a97ec18c18fae79ee8df0d29f446c5efe5f50 --no-wait
Service 'foo' created in namespace 'default'.

➜  client git:(master) kn revision list
NAME          SERVICE   TRAFFIC   TAGS   GENERATION   AGE   CONDITIONS   READY   REASON
foo-qlbwh-1   foo       100%             1            13s   4 OK / 4     True    


➜  client git:(master) kn service update foo --image gcr.io/knative-samples/helloworld-go@sha256:5ea96ba4b872685ff4ddb5cd8d1a97ec18c18fae79ee8df0d29f446c5efe5f50 --no-wait
Service 'foo' updated in namespace 'default'.

➜  client git:(master) kn revision list
NAME          SERVICE   TRAFFIC   TAGS   GENERATION   AGE   CONDITIONS   READY   REASON
foo-lbqql-2   foo       100%             2            11s   4 OK / 4     True    
foo-qlbwh-1   foo                        1            36s   4 OK / 4     True    
```

For other flags like `--env`, repeating same value for an env in successive update also generates new revisions.

**Comment by MIBc** [comment]
If `revision-name` is not set and other args are not changed. It will ceate a new revision name which writed in service spec.  So the `update revision` create a new revision.

If the `revision-name` ="" and other args are not changed. The service spec which will be applied has no change. So it will not create a new revision.

**Comment by navidshaikh** [comment]
Correct, `Empty revision name will result in the server generating a name for the revision.`; server checks no change in configuration and does not generate the revision (as compared in the issue). 
This is to track and check if we want to consider Configuration diff client side during update; and accordingly generate revisions.

**Comment by rhuss** [comment]
It's ok to close this issue (because I don't think we have a good way on the client side to detect if an image has been changed).

Linking it to #1144 as this is another indication that we should switch to server generated names by default
