### ISSUE TITLE
Add "kn service import"

### ISSUE THREAD

**Issue by rhuss** [knative/client#654]
## Describe the feature:

Add a `kn service import` command to import a YAML/JSON description of a service. This is the equivalent of `kubectl create -f`  but can be used also via the Knative API contract. The idea is that `kn service export` (#653) and `kn service import` are complementary.

Possible options:

* `--apply` : Use an apply algorithm like with `kubectl apply` (i.e. add the applied resource as an annotation and perform a three-way diff when actually applying). This would allow also an idempotent application of exported resources, very useful in a CI context where `kn` is used as a last step for deployment/update).
* `--namespace` for specifying the target namespace

**Comment by duglin** [comment]
if nothing else we'd need this to be symmetrical with your `kn export` cmd  
People's OCD would kick in :-)

**Comment by rhuss** [comment]
Yes sure. Export / Import needs to be 'roundtripable'.
