### ISSUE TITLE
Allow an option whether to use retries on modified errors in update operations

### ISSUE THREAD

**Issue by rhuss** [knative/client#662]
## Describe the feature:

I wonder whether it would be a good feature to allow the user to choose whether she wants to have a retry mechanism when an optimistic lock error is returned by the server during an update operation. This happens if the object to be update changes between the initial "get" and "update" API calls:

* client: Get the object to update from API server
* client: Modify in memory
* Somebody else modifies the object, too (like the reconciler updating the status)
* client: Update the object on the server
* "modified object error"

At the moment, for a `kn service update` we do just a retry of the same operation (max. 3 times). This reduces the error rate on the expense that conflicting changes get overwritten by the client. Having this kind of the 'the later wins' behaviour over the default 'the first modification wins' is often better, as in ~ 90% this happens because the reconciler updates a field which is not managed by the user. It is very rare, that two users working parallel on the same object run into this issue, so I think the default behaviour is ok. However, for critical operations it might be preferred to immediately return with an error.

Two suggestions (alternatively or both):

* [A]: Add an option `--max-retries` to update operations (service/source/trigger) with a default of 3. If set to 0, then no retry is performed.
* [B]: Enhance the retry mechanism to check *what* has changed in the meantime (by keeping the old object and diffing the new object) and if only the status or some auto-generated meta-data fields have been changed, then retry. Otherwise return with an error has this change very likely happened on behalf of a user then. 

For the retry mechanism we offer a `KnServingClient` method in #660 

```golang
// UpdateServiceWithRetry updates service and retries if there is a version conflict.
// The updateFunc receives a deep copy of the existing service and can add update it in
// place.
UpdateServiceWithRetry(name string, updateFunc serviceUpdateFunc, nrRetries int) error
```

which can be used as a blueprint for other occasions (if the implementation becomes more involved we can also extract the common parts in a utility method as we did for the wait operation)

**Comment by duglin** [comment]
I think "A" might be the best approach. I didn't realize we'd retry today so exposing that to the user (as an advanced option) so that they can control if they want that at all would be good.

"B" is interesting but I'm not sure it's really worth all of the effort, plus I'd still want a way for the user to say "never retry even if just `status` was updated", which gets back to "A". Also, "B" might force a user to understand too much of the underling Kube system (spec vs status) and I think might be best to just abstract it away to just "the service was modified".

**Comment by rhuss** [comment]
I think, too, that we should start with [A].

BTW, this feature would be also another example for a value add over the usage of plain YAML descriptors (like the sync wait on route ready when creating a service)

**Comment by daisy-ycguo** [comment]
I think the current solution - with a 3 times retries - is good enough. Even the error is caused by users' reason. I don't quite get your point `However, for critical operations it might be preferred to immediately return with an error`.

**Comment by rhuss** [comment]
> I don't quite get your point `However, for critical operations it might be preferred to immediately return with an error`.

I mean, that as I suspect that 90% of the concurrent modification issues are caused by non-conflicting updates (e.g. user updates `spec`, controllers updates `status`) its ok to "override" again. With "critical" I refer to the remaining 10%, so it might be that we want to detect conflicts and then return with an error instead of just overwriting it. Not sure if I'm right here with my assessment, and maybe not so important. Just lets start with using a retry for everything (and see what issues might occur later).
