### ISSUE TITLE
Add `--wait` and `--no-wait` for all delete operation

### ISSUE THREAD

**Issue by rhuss** [knative/client#671]
## Describe the feature:

In order to avoid race conditions when on delete an object and immediately recreate it, by default we should also wait for the end of a delete operation, like we do for `service create` and `service update`.

Therefor a `--wait` and a `--no-wait` option should be added to all "delete" operation. This can reuse our general wait handling util libs.

**Comment by rhuss** [comment]
See https://github.com/knative/serving/issues/6876 for some example where this option is useful.

I think also that `--wait` should be the default.

**Comment by dsimansk** [comment]
PR #682 extends current wait functionality to allow waiting for various events.

To complete this issue synchronous `delete` op should be used for:
- [ ] service delete
- [ ] revision delete.

**Comment by dsimansk** [comment]
/reopen

To do: sync revision delete.
