### ISSUE TITLE
Add option for adding labels only to service and/or template

### ISSUE THREAD

**Issue by rhuss** [knative/client#675]
## Describe the feature:

At the moment, when using `kn service create --label` then the labe is put into two places: The service's metadata but also on the revisiontemplate. This is find in many cases, but sometimes one needs more fine grained control to where to put labels.

I suggest to use the following options:

* `--label` for setting a label on both, service & template
* `--label-service` for only setting on the service
* `--label-pod` for setting a label only on the revision spec (so could be also `--label-revision`)

I suggest to use `--label-service` over `--service-label` so that the options appear together when sorting alphabetically (like in `kn service create --help`). 

Same should be implemented for `update`

Also for annotations we have the same issue.

An alternative approach would be to use a prefix to the label key to indicate the location of the label

* `--label mylabel=value` to put on both spots
* `--label svc:mylabel=value` to put only on services (`:` is a char not allowed in a label key)
* `--label pod:mylabel=value` to put only on the temlate

This solution would have the advantage to not add to the ever growing option-space. As I expect that 90% of the cases use the pure `--label` form to set on both entitites, I tend to prefer this variant over the one with separate options.

The separator char (':') in this case needs to be checked, whether it can be also used for annotations (so would need to be an illegal char for an annotation key, too). Both, labels and annotations should use the same separator character.

This issue would also make the fix in #672 obsolete so part of this feature would be to cleanup #672, too.

**Comment by duglin** [comment]
re: The fix in #672... I do wonder if it still makes sense to not allow well-known labels on the Revision if we know it'll generate an error. So, after this feature is implemented people can still do `-label serving.knative.dev/visibility=cluster-local` if they wanted, so should we keep the logic from #672 anyway?  Just a thought.

**Comment by rhuss** [comment]
> So, after this feature is implemented people can still do `-label serving.knative.dev/visibility=cluster-local` if they wanted, so should we keep the logic from #672 anyway? Just a thought.

Yes, that would be the same if the would put two labels into a YAML file and so would get an error back from the server. However, with the possibility to set only the service labels, users can fine-tune it. I would not add too much "magic" and let the server decide what is allowed and what not.

**Comment by shashwathi** [comment]
@rhuss 

We have couple of clarifying questions
- In the case where user mentions `--label foo=bar --label-service foo=baz` , does `service-label` value take priority over `label` flag?
- In the case where user mentions `--label foo=bar --label-service bar=baz` , does service take both `label` and `label-service` flags?
- In the case where user mentions `--label foo=bar --label-service foo=baz` , does revision template value get label `foo=bar` and service label gets `foo=baz`?  (just to clarify this behaviour)
- In the case where user mentions `--label foo- --label-service foo=bar` 
       - does service add or delete the label? 
       - does revision template delete the label in this case? 
- In the case where user mentions `--label foo=bar --label-service foo-` , does service add or delete the label?
 
We think it makes sense to prioritize specific flags such as `label-service` and `label-revision` over `label`. Let us know your thoughts.

cc @andrew-su

**Comment by rhuss** [comment]
Thanks a lot for taking over this issue !

To your questions: 

> * In the case where user mentions `--label foo=bar --label-service foo=baz` , does `service-label` value take priority over `label` flag?

Yes, so you end up with `foo=bar` on the pod labels and `foo=baz` on the service label.

> * In the case where user mentions `--label foo=bar --label-service bar=baz` , does service take both `label` and `label-service` flags?

Yes, result should be: pod label: foo=bar, service labels: foo=bar, bar=baz

> * In the case where user mentions `--label foo=bar --label-service foo=baz` , does revision template value get label `foo=bar` and service label gets `foo=baz`?  (just to clarify this behaviour)

Yes (see above)

> * In the case where user mentions `--label foo- --label-service foo=bar`
>   - does service add or delete the label?

Add

>   - does revision template delete the label in this case?

Yes

> * In the case where user mentions `--label foo=bar --label-service foo-` , does service add or delete the label?

Delete.

-----

In general, the more-specific option overrides the general `--label` option for the specific part.
