### ISSUE TITLE
"kn service export" should also export service annotations

### ISSUE THREAD

**Issue by rhuss** [knative/client#724]
### Bug report

At the moment, `kn export` does not export annotations.

### Expected behavior

User provided annotations should be exported as well (like with `kn service create --annotation`). Maybe filter out some automatically added annotations (if known), but that might be difficult.

Adding an E2E test is a plus.

### Steps to reproduce the problem

* Create a service with annotation: `kn service create mysvc --annotation myanno=value someimage`
* Export its: `kn service export mysvc`
* Check whether the annotation is included.

**Comment by itsmurugappan** [comment]
@rhuss this was fixed by #819.
