### ISSUE TITLE
Discussion: Changing Client WG meeting schedule

### ISSUE THREAD

**Issue by rhuss** [knative/client#740]
The current timeslot for the Client WG meeting every Tuesday is not optimal for many contributors, even if its a bit better during the summer time:

* **10:30am** Pacific Day Time
* **6:30pm** Central European Time (7:30 pm with daylight saving)
* **11:00pm** Indian Summer Time
* **1:30am** China Standard Time

![image](https://user-images.githubusercontent.com/99080/76611585-0d4e9e80-651b-11ea-98ba-ba106619a692.png)

I'm totally aware that there is no perfect time which is suitable for all timezones, especially as we are really globally distributed. 

In order to find out where our center of gravity wrt/ to contributions over timezones I looked at the top active contributors with more than 5 commits in this client repo and calculated a weighted average of their timezones (weighted by number of contributions):

```
84 * (+5:30) [Navid, IST]
81 * (+2) [Roland, CEST]
34 * (-7) [Max, PDT]
33 * (-7) [Naomi, PDT]
24 * (+8) [Daisy, China Standard Time]
11 * (+2) [David, CEST]
8 * (-7) [Murugappan, PDT]
8 * (-7) [Doug, PDT ?]
6 * (+8) [Lv, China Standard Time]
6 * (-7) [Matt and his bot, PDT]

Sum: 263
Nr. Contrib: 295
```

This weighted average is **GMT + 0.89** (also, please correct me if I got a TZ wrong)

Yes, it's a very simplistic metrics but this metric clearly indicates that many contributors can't properly (or only at insane times) join the client WG calls.

I suggest to move to one of these options:

* Moving the WG call earlier on Tuesday. Eg the 9:00am PDT slot seems to be available. That would (at leas in summer) move the time to midnight for Chinese people. Of course 8:00am PDT would be even better.
* Having two calls a week, one for the west half of the world, the other for the east half (I could drive both, as I'm somewhat in the middle).
* Alternate WG calls every two weeks between an western friendly time and an eastern friendly time. E.g. Tuesday 10:30 am PDT as now and 9:00 am CET (== 1am PDT) the other week.

I suggest that we discuss discuss this in the next client WG meeting, but I open a poll here for the direction to proceed.

**Comment by rhuss** [comment]
**Keep the WG call at every Tuesday, 10:30 PDT**

**Comment by rhuss** [comment]
**Move the WG call to an earlier time** (e.g. 8 or 9am PDT)

**Comment by rhuss** [comment]
**Two calls per week, one at the current time slot + one much earlier** (maybe on the same time)

**Comment by rhuss** [comment]
**Alternate time of WG call every week, one week with the current timeslot, the other week earlier the day**

**Comment by daisy-ycguo** [comment]
Thank you @rhuss . I really appreciate that.

**Comment by maximilien** [comment]
When working with Asia-Euro, which I have been doing for years, the best thing I have found for PDT timezone is two calls per day. AM PDT (8-9a) for US-Euro and early PM PDT (4p or so) for US-Asia. This also gives flexibility for others who are traveling and does not end up being in crazy time for most.

**Comment by duglin** [comment]
Can we consider another day too?  Personally, I'm ok with an earlier time but just not on Tuesday

**Comment by rhuss** [comment]
As decided yesterday, I opened a Doodle to find the second timeslot (every two weeks) on Tuesday for now: https://doodle.com/poll/kwd5672ic2sdettt

@duglin I'm totally fine to move it also to another day if the group agrees, but for alternating meetings, I'd prefer to stick to the same day to not confuse people too much.

**Comment by rhuss** [comment]
Decision was made to try out a biweekly, alternating schedule so that contributors from the APAC region.

The date and times [we are settled on](https://docs.google.com/document/d/1Uh7jTWQruBBmic-WmTvtc9cMF95kQrKb5lsqWhNuikM/edit#heading=h.mrfej987c0uz) are:

* 10:30am Pacific Time (PDT in summer, PST in winter), starting on April 6t
* 3:30pm Central European Time (CEST in summer, CET in winter), starting on March 30

To make this happen we need some updates on the community docs and as well the community calendar:

- [ ] Open issue at https://github.com/knative/community for updating the calendar 
- [ ] Open PR at https://github.com/knative/docs for updating the knative.dev pages reflecting the new schedule
- [ ] Check that Google Hangout meeting could be started by all WG leads, so it doesn't have to be @sixolet . Naomi, any suggestions how I could start that Hangout session ? It would be very cool if we could use a stable hangout URL for both timeslots. Alternatively, we could move to e.g. Zoom like other working group did as well.

I think another good idea would be to update the slack channel's topic to reflect always the next WG call date & time so that it easy to look that up (without hunting for the calendar entries).

**Comment by rhuss** [comment]
PR for community repo added: https://github.com/knative/community/pull/109

**Comment by navidshaikh** [comment]
/close

alternate WG meeting schedule is in place, thanks @rhuss!
