### ISSUE TITLE
Need to run e2e tests on different platforms, e.g., Windows, Mac OS X, and Linux

### ISSUE THREAD

**Issue by maximilien** [knative/client#741]
### Feature request

Currently the e2e tests are automated in CI and run only on Linux containers. This is great but does not reflect the different platforms we intend `kn` users to utilize. As a user client tool, we should expect more users to actually use Windows and Mac OS X as their execution platform.

In addition, some issues have already surfaced that are specific to the user’s platform. In particular when it comes to `kn` plugins. See issues #738 #733 and #417.

### Use case

* running plugins on the Windows platform
* running `kn` from the downloaded binary

In all of these cases, and solutions to issues above, we ideally would need to have e2e tests specific to the platform and running these tests in CI.

> /kind bug

**Comment by rhuss** [comment]
@chaodaiG @chizhg Does our Prow CI infrastructure support running on other platforms than Unix ?

**Comment by coryrc** [comment]
> @chaodaiG @chizhg Does our Prow CI infrastructure support running on other platforms than Unix ?

No

**Comment by coryrc** [comment]
> @chaodaiG @chizhg Does our Prow CI infrastructure support running on other platforms than Unix ?

Well, it doesn't even support Unix! It only supports Kubernetes.

But if someone was able to provide a kubernetes cluster running Windows and created the image performing desired e2e test (along with downloading repository and uploading files to GCS) I think we actually could do this.

**Comment by coryrc** [comment]
There might also be a non-Prow way of doing things that interacts with Github and could be a blocking presubmit, though there wouldn't be any periodic job.

**Comment by navidshaikh** [comment]
/close

feel free to re-open if you've further comments.
