### ISSUE TITLE
kn trigger create fails without --filter flag

### ISSUE THREAD

**Issue by dsimansk** [knative/client#744]
### Bug report

There was a bug in Eventing 0.13.0 that rejected triggers without filters. However, even on version `0.13.1` the creation of such trigger will fail. There's a bug in our current impl that will initialize empty `trigger.Spec.Filter.Attributes` regardless of no flag provided that causes the error behaviour. 

Beware, that `kn trigger describe` has to be fixed for empty filters also. 

```bash
$ kn trigger create test --broker default --sink svc:svc1
cannot create trigger 'test' in namespace 'default' because: admission webhook "validation.webhook.eventing.knative.dev" denied the request: validation failed: At least one filtered attribute must be specified: spec.filter.attributes
```

### Expected behavior

Trigger can be created without `--filter` flag.

### Steps to reproduce the problem

1. kn trigger create test --broker default --sink svc:svc1

### kn version

HEAD 

### Knative (serving/eventing) version

0.13.1

/kind good-first-issue

**Comment by mvinkler** [comment]
Also, `kn trigger create -h` should be updated accordingly, now it suggests `--filter` is mandatory:
```
[root@ocp-dynamic-7202 eventing]# kn trigger create -h
Create a trigger

Usage:
  kn trigger create NAME --broker BROKER --filter KEY=VALUE --sink SINK [flags]
```
