### ISSUE TITLE
kn service list -o name doesn't seem to work

### ISSUE THREAD

**Issue by duglin** [knative/client#754]
### Bug report

```
$ kn service list -o name
list types are not supported by name printing: *v1.ServiceList
```

### Expected behavior

Show me the list of services by name - e.g.: `service.serving.knative.dev/echo`

### Steps to reproduce the problem

```
kn service create echo --image duglin/echo
kn service list -o name
kn service list echo -o name
```

Both of the last 2 cmds should work

### kn version

master/HEAD

### Knative (serving/eventing) version

master/HEAD

**Comment by daisy-ycguo** [comment]
/assign daisy-ycguo
I will take a look at this issue.

**Comment by rhuss** [comment]
Thanks, @daisy-ycguo  !

Actually the expected behaviour would be a list of service names, line by line (like in `kubectl get pod -o name`
