### ISSUE TITLE
Misleading error message with multiple names

### ISSUE THREAD

**Issue by duglin** [knative/client#762]
### Bug report

```
$ kn service update echo echo1 --image duglin/echo
requires the service name
```

### Expected behavior

I would have expected either something like:
```
$ kn service create echo echo1 --image duglin/echo
'service create' requires the service name given as single argument
```
or for it to do the update on both services (I kind of like this option).

### Steps to reproduce the problem

See above

### kn version

master/head as of 2020/03/26

**Comment by duglin** [comment]
It would be nice if the fix was global and not just for the update cmd

**Comment by rhuss** [comment]
Good point and also related to #213 which we should tackle within the next 3 months.

**Comment by maximilien** [comment]
But for this one I think passing one name for create makes a lot of sense since the command is not `kn services create ...` which would say many creates. if you want to create many services then you can easily issue command many times.

**Comment by duglin** [comment]
I can see an argument for 'create' being special and not allowing multiple
