### ISSUE TITLE
Add "--target-utilization" to manage "autoscaling.knative.dev/targetUtilizationPercentage" annotation

### ISSUE THREAD

**Issue by rhuss** [knative/client#768]
### Feature request

In order to override the default utilization of 70% it would be cool if `kn` would allow an option `--target-utilization` for setting the percentage of utilization before scaling up. This option should go to `kn service create` and `kn service update`

**Comment by MIBc** [comment]
I can do this.

**Comment by navidshaikh** [comment]
/close

fixed with https://github.com/knative/client/pull/788
