### ISSUE TITLE
`service describe` show repetitive revisions if service has multi revisions

### ISSUE THREAD

**Issue by MIBc** [knative/client#789]
### Bug report

If a service has more than three revisons. The 'kn service describe -v' will show repetitive revisions.
Here is a screenshot：
![image](https://user-images.githubusercontent.com/4477478/78783192-c9de3780-79d5-11ea-8a3c-c78a358a2e7f.png)

I have read the [code](https://github.com/knative/client/blob/master/pkg/kn/commands/service/describe.go#L324).
The reason is that the revison would be covered by next one.
We should use deep copy.

### Expected behavior

Show every revision in knative service.

### Steps to reproduce the problem

Creating more than three revisions for a knative service.
### kn version
v0.13

/kind bug

**Comment by dsimansk** [comment]
Fixed in PR #790.

/close
