### ISSUE TITLE
Consider adding support for `--all` on `kn service delete`

### ISSUE THREAD

**Issue by duglin** [knative/client#792]
### Feature request

Kubectl has a `--all` option to mean "all instances of the specified resource in the namespace". So for example: `kubectl delete ksvc --all` will delete all KnServices in the default namespace. I find this very useful when I want to quickly clean things up.

It would be really nice if we could do: `kn service delete --all` to delete all KnServices.

It might be good to look into whether we should support `--all` on other commands, like: describe, export, list and update. I'm less sure about some of those, but I do think `delete` will be popular.

### Use case

/kind proposal

**Comment by rhuss** [comment]
Looks like a good addition, however, I'm afraid that it can't be in an atomic fashion if the backend doesn't support atomic delete. What if new objects are created during deletion ? What if queried objects are removed in parallel ? (which is not made up considering that a sync delete can take several seconds).

But for a 'best-effort' delete, I think would be fine, although I doubt its useful except for demoware and experimentation.

**Comment by duglin** [comment]
Even if it were atomic the user could still experience a new Ksvc being created right as it was completing the atomic delete, or even during the return of the "200 OK". So, yep, I think a "best-effort" delete is fine and really all anyone can hope for. I think anyone who uses this is just looking for a convenience thing anyway.

**Comment by danielhelfand** [comment]
Anyone working on this, or is there any further discussion to be had with this? Would be interested in picking this up if this is ready to be worked on.

**Comment by duglin** [comment]
@danielhelfand go for it! thanks
