### ISSUE TITLE
e2e: Update tekton e2e tests

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#795]
Update tekton e2e tests to use latest pipeline release v0.11.1.

**Comment by rhuss** [comment]
@navidshaikh can this be closed ?

**Comment by navidshaikh** [comment]
/close

Yes.
We're now `tekton.dev/v1alpha1` tasks for test pipeline on pipeline release v0.11.1. 
There are `tekton.dev/v1beta1` tasks available we can update our pipeline accordingly, can be tracked in a separate ticket.

Fixed by https://github.com/knative/client/pull/803
