### ISSUE TITLE
Package kn in a container image

### ISSUE THREAD

**Issue by ImJasonH** [knative/client#80]
This would enable users of Tekton and Google Cloud Build to more easily invoke `kn`, e.g.:

```
...
steps
- name: kn-deploy-image
  image: gcr.io/knative-something/kn:v0.X.Y
  command: ['kn', 'service', 'update', 'foo', '--image', 'gcr.io/my/image']
...
```

Assuming `kn` doesn't depend on any other tools, you could build and push the image using [`ko publish`](https://github.com/google/ko#ko-publish) (and [`crane copy`](https://github.com/google/go-containerregistry/blob/master/cmd/crane/doc/crane_copy.md) to shorten the image name):

```
$ KO_DOCKER_REPO=gcr.io/knative-something/ ko publish -P github.com/knative/client/cmd/kn
$ crane copy gcr.io/knative-something/github.com/knative/client/cmd/kn gcr.io/knative-something/kn:${RELEASE}
```

**Comment by ImJasonH** [comment]
Related: https://github.com/knative/client/issues/52 https://github.com/knative/client/issues/53

It'd be great to get nightly-built images tagged with the latest commit SHA (or just `:latest`), and release-tagged images built during releases.

**Comment by houshengbo** [comment]
We can directly run the command "ko publish github.com/knative/client/cmd/kn  -B -t ${tag}" to name the image <KO_DOCKER_REPO>/kn in the image registry. No need of crane copy.

We can define <KO_DOCKER_REPO> as gcr.io/[gcloud-project], docker.io/<username>, etc.

**Comment by houshengbo** [comment]
I have succeeded in creating the image in my own dockerhub repository, docker.io/houshengbo/kn:latest, with the command: 
```
ko publish github.com/knative/client/cmd/kn -B -t latest
```

When I pulled the image, and did the taskrun run for the following section:
```
steps
- name: kn-deploy-image
  image: docker.io/houshengbo/kn:latest
  command: ['kn', 'service', 'create', 'foo', '--image', 'gcr.io/knative-samples/helloworld-go', '--env', 'TARGET=Knative']
```
I have got:
```
kn in not in $PATH
```

I was wondering what I have done wrong or I am missing. @ImJasonH Do you have any ideas? Thx.

**Comment by rhuss** [comment]
@houshengbo just shot in the dark, but could you use `./kn` instead of plain `kn` ? Thoug, I'm not sure what working directory `ko` sets for the generated image, nor what working directory Tekton is using.

**Comment by houshengbo** [comment]
It looks like I need to install crane first to check the path of kn. This is what I have done:
```
go get github.com/google/go-containerregistry/cmd/crane
```
crane should be install under $GOPATH/bin.

Then run 
```
crane config ${image}
```

Here is the output for the image of kn:
```
{"architecture":"amd64","author":"Bazel","created":"1970-01-01T00:00:00Z","history":[{"author":"Bazel","created":"1970-01-01T00:00:00Z","created_by":"bazel build ..."},{"created":"0001-01-01T00:00:00Z"},{"created":"0001-01-01T00:00:00Z"}],"os":"linux","rootfs":{"type":"layers","diff_ids":["sha256:01092e5921c5543a918d54d9df752ee09a84c912a1d914b7eb37e7152f20b951","sha256:8f8d58d9708807553434fbd82014ea40b5ee0dc8b2eeefcde561a363461d3e66","sha256:0d411545791d984190d7488cad58d30fa9ae1aec52eda3262d65ecd1aa58d1dc"]},"config":{"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":null,"Healthcheck":null,"Domainname":"","Entrypoint":["/ko-app/kn"],"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt","KO_DATA_PATH=/var/run/ko"],"Hostname":"","Image":"","Labels":null,"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":null,"WorkingDir":"","ExposedPorts":null,"ArgsEscaped":false,"NetworkDisabled":false,"MacAddress":"","StopSignal":"","Shell":null},"container_config":{"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":null,"Healthcheck":null,"Domainname":"","Entrypoint":null,"Env":null,"Hostname":"","Image":"","Labels":null,"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":null,"WorkingDir":"","ExposedPorts":null,"ArgsEscaped":false,"NetworkDisabled":false,"MacAddress":"","StopSignal":"","Shell":null}}
```

The most important thing we need to look up is Entrypoint":["/ko-app/kn"], which tells us the path of the command.

I will try /ko-app/kn instead of kn to see how it goes.

**Comment by sixolet** [comment]
We have it now!

**Comment by ImJasonH** [comment]
That's `gcr.io/knative-releases/github.com/knative/client/cmd/kn` correct?

**Comment by rhuss** [comment]
Yes. With the gotcha that `kn version` is broken (we need to propagate ldflags to ko) --> https://github.com/knative/client/issues/257
