### ISSUE TITLE
kn plugins for eventing sources should be able to extend `kn source` group

### ISSUE THREAD

**Issue by maximilien** [knative/client#814]
### Feature request

Current `kn` plugin architecture prevents plugins to extend existing command groups. This makes sense since we would not want a `kn-service-create` plugin that redefines the `service create` commands. Same for almost all other `kn` command groups.

But there is at least one exception. This is for command groups where we want to define sub-groups but at the same time allow extensions. One such example is the `kn source` eventing command group.

### Use case

Kn ships with some eventing sources, e.g., `ping`, but we also want to have plugins be created and defined that also extends this command group, e.g., `source kafka` and `source github` and others.

These plugins are being defined in the [client-contrib](https://github.com/knative/client-contrib) repo for instance the [`kn-source-kafka`](https://github.com/knative/client-contrib/pull/19) is one such example.

### UI Example

```
kn source kafka create my-kafka-source --sink my-kafka-sink ...
...
kn source github create my-hithub-source --sink my-github-sink
...
```

> /kind proposal
> /kind bug

**Comment by rhuss** [comment]
> Current `kn` plugin architecture prevents plugins to extend existing command groups. This makes sense since we would not want a `kn-service-create` plugin that redefines the `service create` commands. Same for almost all other `kn` command groups.

tbh, I thought this would be true only for case where a terminal command would overwrite an built-in command (actually the command on which an "Run" is attached).

I suggest to implement this in the generic fashion to just verify that there is no collision on the terminal (sub) command.

**Comment by maximilien** [comment]
> tbh, I thought this would be true only for case where a terminal command would overwrite an built-in command (actually the command on which an "Run" is attached).

I think there is value to both. Some command group should not allow extensions. For instance adding any sub commands fo `service` would IMO a bad thing.

> I suggest to implement this in the generic fashion to just verify that there is no collision on the terminal (sub) command.

Sure but only for allowed command groups.

**Comment by rhuss** [comment]
> I think there is value to both. Some command group should not allow extensions. For instance adding any sub commands fo `service` would IMO a bad thing.

Why ? What's about a `kn service log` for showing los on a kubernetes based system (like stern does) ? or `kn source apiserver log` (so logs on various levels).

**Comment by rhuss** [comment]
I would allow it for every group, but forbid to override.
