### ISSUE TITLE
Honour deletionTimestamp for "kn revision delete", too

### ISSUE THREAD

**Issue by rhuss** [knative/client#815]
As followup to https://github.com/knative/client/pull/805 add the deletion timestamp handling also for `kn revision delete`.

**Comment by MIBc** [comment]
I want to continue working on it.

**Comment by rhuss** [comment]
Yes, sorry for already merging the other PR but we are cutting a release today (0.14.0), so wanted to have your contribution to be included.

**Comment by MIBc** [comment]
Why we need to check deletionTimestamp for revision delete? 
Unlike update command. Deleting revision will not hang until timeout. It may raise `resource not found` error if revision has been deleted.

**Comment by rhuss** [comment]
Not sure if I understand you comment correcly. Wouldn't it make sense to have consistent behaviour for deleting any resource ? I.e. if the the`deletionTimestamp` is set then no deletion is attempt again (regardless of what we delete).
