### ISSUE TITLE
kn source -h Returns Error: unknown command 'source' 

### ISSUE THREAD

**Issue by danielhelfand** [knative/client#845]
### Bug report

Running `kn source -h` returns `Error: unknown command 'source'`. This appears due to how `kn` validates commands with plugins. 

This occurs because [`HandlePluginCommand`](https://github.com/knative/client/blob/0df54bc500ad960568e5d00285d3f112b9db665e/pkg/kn/commands/plugin/handler.go#L126) searches for a binary on the local path and returns [`Could not find plugin to execute`](https://github.com/knative/client/blob/0df54bc500ad960568e5d00285d3f112b9db665e/pkg/kn/commands/plugin/handler.go#L151). 

This results in the command being reported as unknown:

https://github.com/knative/client/blob/0df54bc500ad960568e5d00285d3f112b9db665e/pkg/kn/core/root.go#L87

This is solved by adding a `-h` check in `HandlePluginCommand`:

```
if cmdArgs[idx] == "-h" {
    return nil
}
```

### Expected behavior

`kn source -h` returns the following:

```
Usage:
  kn source [flags]
  kn source [command]

Available Commands:
  apiserver   Kubernetes API Server Event Source command group
  binding     Sink binding command group
  list        List available sources
  list-types  List available source types
  ping        Ping source command group

Flags:
  -h, --help   help for source

Global Flags:
      --config string       kn config file (default is ~/.config/kn/config.yaml)
      --kubeconfig string   kubectl config file (default is ~/.kube/config)
      --log-http            log http traffic

Use "kn source [command] --help" for more information about a command.

```

### Steps to reproduce the problem

Run `kn source -h`

### kn version

What is currently in master.

### Knative (serving/eventing) version

N/A

**Comment by rhuss** [comment]
Thanks for spotting this and working on this. See my comment on the PR why I think ignoring plugins can not be the full solution.
