### ISSUE TITLE
kn service describe should show cluster local endpoint url

### ISSUE THREAD

**Issue by ZhuangYuZY** [knative/client#852]
Today kn service describe can show many information, but I think it miss cluster local endpoint url when it available. Cluster local endpoint url is important when developer want to build multiple micro services. Only one micro service as external endpoints, but others using cluster local endpoint to communicate. 

kn client should show cluster local endpoint when it available to make developer know it easily, and encourage to use it.

kn service describe not show my kn service cluster local endpoint url.
```
$ kn service describe custom-route

Name:       custom-route
Namespace:  default
Labels:     env=prod
Age:        4d
URL:        http://custom-route-default.zytest0427-93e5c3271ec31087fc6cac2cda1357a7-0000.us-south.containers.appdomain.cloud

Revisions:
  100%  @latest (custom-route-htxsp-1) [1] (4d)
        Image:  agrawals18/helloworld (pinned to be18cb)

Conditions:
  OK TYPE                   AGE REASON
  ++ Ready                  21h
  ++ ConfigurationsReady     4d
  ++ RoutesReady            21h
```

but I can get it from kubectl command.
```
$kubectl get ksvc mydemo -o jsonpath="{.status.address.url}"
http://mydemo.5d14dd3a-1703.svc.cluster.local
```

**Comment by rhuss** [comment]
Could you try `kn service describe --verbose` ? This should include the Cluster URL, too.

Please reopen the issue if it does not fit your bill.
