### ISSUE TITLE
kn service delete didn't return within 5m in sync mode

### ISSUE THREAD

**Issue by cdlliuy** [knative/client#858]
### Bug report
In our environments,  *sometimes*,  the `kn service delete` cmd didn't return within 300 seconds.

We are running with the latest kn client in which the deletion works in a sync approach.

Once the deletion is hang,  we checked the ksvc and pod status:

```
Get KN Service details:
+ kn -n 32779bf7-9750 service describe e2e-test-1-knservice-9ea58974
services.serving.knative.dev "e2e-test-1-knservice-9ea58974" not found

+ kn -n 32779bf7-9750 route describe e2e-test-1-knservice-9ea58974
routes.serving.knative.dev "e2e-test-1-knservice-9ea58974" not found

+ kn -n 32779bf7-9750 revision list -s e2e-test-1-knservice-9ea58974
services.serving.knative.dev "e2e-test-1-knservice-9ea58974" not found

+ kubectl -n 32779bf7-9750 get pods --selector serving.knative.dev/service=e2e-test-1-knservice-9ea58974
No resources found in 32779bf7-9750 namespace.
```

I want to know if all the resources are gone already, what else is preventing the deletion from return ? 

### kn version

kn version
Version:      v0.13.0
Build Date:   2020-03-11 11:01:19
Git Revision: db569fa

### Knative (serving/eventing) version

 v0.13.0

**Comment by rhuss** [comment]
Have you tried 0.13.2 ? That does an async delete by default (but sync can be enabled with `--wait`).

If you need a sync delete (and I suspect this as your example looks like coming from an integration test), then this, of course, no option. Sync operation works by letting the client wait for a `delete` event delivered by the API Server. In this case it looks like that this event is missed for some reason.

what we could do quickly is that if a delete operation times out, we recheck whether the service exists and if not, kn doesn't return an error. This is not perfect as it will take the full timeout to detect this, but better than returning an error. 

Would this solve your use case ?

Jus re-read your bug description: What do you mean does not return within 300 seconds ? Does it return with an error after 300s then ? (in which case the solution above might be helpful)

**Comment by cdlliuy** [comment]
@rhuss ,  yes,  I have used "--no-wait" as a workaround.  

For the question regarding to `does not return within 300 seconds`  ,  that is not defined by --wait-timeout.  In fact, I executed the `kn` cmd with go code within a context timeout `300s` ..  I didn't get any response by the timeout setting. 

Can you explain this further?
```
Sync operation works by letting the client wait for a delete event delivered by the API Server. In this case it looks like that this event is missed for some reason.
```
We are not only the user of kn, but also operates `knative` service as well.   The `delete` issues happened more recently, so I would like to understand why it can't return in detail.

**Comment by rhuss** [comment]
I meant, did it return automatically (possibly with an error message ?) Or had you to interrupt it with ctrl-c because it hung ?

**Comment by cdlliuy** [comment]
Interrupt it :-)

**Comment by rhuss** [comment]
ok, so it looks like that also the timeout doesn't work properly (which is even a more severe issue), because it should have returned  with an error message after 300s.

Could you please try to extract a thread dump in this situation like described in https://stackoverflow.com/a/35290196/207604 ? (i.e. setting env var `GOTRACEBACK=all` before starting kn, and the interrupt with a `kill -QUIT <pid>` or, if on Linux, type `CTRL-\` )

**Comment by cdlliuy** [comment]
@rhuss ,  there should be some misunderstanding.  
I think the default timeout is 600 seconds when no "--wait-timeout" setting.   Instead of waiting up to 600s,  I used golang context timeout in my program to interrupt it (should be similar as ctrl+c when running in manual) . 

I am not worried about the timeout implementation for kn.. Instead,  I would like to know why it can't detect the service is gone when no ksvc,no revision, no route,  no pod are there. 

Can you explain your comment further?
```
Sync operation works by letting the client wait for a delete event delivered by the API Server. In this case it looks like that this event is missed for some reason.
```
Which `delete` event is expected in above ^^ ? 

We are not only the user of kn, but also operates knative service as well. The delete issues happened more recently, so I would like to understand why it can't return in detail.

**Comment by ericmillin** [comment]
@rhuss I'm hitting this issue in the kn client. I think the problem is here: https://github.com/knative/client/blob/c801e8205ab4712e71b724edaa5634805db2d902/pkg/serving/v1/client.go#L271

I added some crude logging and I saw an `ADDED` event first, then all the subsequent events received by the callback had empty `Type` fields and `nil` Objects.

**Comment by ericmillin** [comment]
Here's a repro:

```
kn service create deltest --image knativesamples/helloworld --min-scale 5
kn service delete deltest --wait
```

**Comment by ericmillin** [comment]
@rhuss Sync delete in the kn client fails for me consistently. It always times out. What I see is an "ADDED" event at start and all subsequent events that are handled in the DeleteService callback have empty `Type` and nil `Object` fields.

**Comment by ericmillin** [comment]
I can reproduce
Repro:
```
kn service create deltest --image knativesamples/helloworld --min-scale 5
kn service delete deltest --wait
```

**Comment by rhuss** [comment]
Let's reopen this if this is still an issue. I think we added some extra code to be prepared for this situation, but we should try to reproduce it with the latest kn release.
