### ISSUE TITLE
traffic tags: Error if requested for removing non-existing tag

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#874]
### Bug report
If requested to untag a non-existing tag in traffic block, add an error.

### Expected behavior
`service update` command returns error message indicating the tag doesnt exists for service and non-zero exit status.

### Steps to reproduce the problem
1. `kn service create hello --image knativesamples/helloworld`
2. `kn service update hello --untag foo --no-wait`

### kn version
latest

### Knative (serving/eventing) version
v0.15.0

**Comment by danielhelfand** [comment]
Anyone working on this, or further discussion to be had? Would be interested in picking this up.

**Comment by rhuss** [comment]
thanks !

/assign danielhelfand

**Comment by navidshaikh** [comment]
Thanks @danielhelfand! 

We can discuss on slack if needed, we'd need to raise the error if given tag is absent, this is mostly done here.
