### ISSUE TITLE
service update stuck if requested for no-op traffic block operations

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#875]
### Bug report
If requested for no-op traffic split related operation on service, `service update` hangs.

### Expected behavior
`service update` commands returns

### Steps to reproduce the problem
1. `kn service create hello2 --image knativesamples/helloworld`
2. `kn service update hello2 @latest=100`

Notice the second command here is a no-op on traffic spec as the traffic is already routed to `latestReadyRevision: true` target (also represented by `@latest`).

While the service update command waits, the service is already updated and ready if you check that in a separate window
```
kn service list hello2
NAME     URL                                 LATEST           AGE    CONDITIONS   READY   REASON
hello2   http://hello2.default.example.com   hello2-fzfnp-1   3m6s   3 OK / 3     True    
```
however the update command waits until timeout (600 seconds) and returns with error.

If we try to re-run the above command with `--no-wait` the `service update` returns properly.

I think the issue is, we're expecting event type as `MODIFIED` while waiting for service service to become ready, which never arrives in case of no-op for service update.

### kn version
0.15.1 / nightly

### Knative (serving/eventing) version
0.15

**Comment by MIBc** [comment]
Updating traffic will not create `MODIFIED`  event, right?

**Comment by rhuss** [comment]
That's a good question, but probably not. We should check why the MODIFIED check has been introduced (I think I was it ;-). However the challenge for traffic update and sync-wait is, to wait until the traffic reconfiguration has happened on the ApiGateway. Should be a certain event, too.

**Comment by rhuss** [comment]
@navidshaikh  is still an issue ? I don't remember that we fixed this ....

**Comment by navidshaikh** [comment]
@rhuss : yes, I could reproduce it against kn nightly.

**Comment by rhuss** [comment]
Ok, then we should fix it :)

**Comment by rhuss** [comment]
Sorry to bug you again @navidshaikh , but with the latest changes in traffic split UI is this issue still reproducible ?

**Comment by dsimansk** [comment]
The `update` command is not blocked by no-op anymore. However, the message seems a bit confusing, but it's another story.

I'd say it's OK to keep this one closed.

```
➜  ~ kn service create hello2 --image knativesamples/helloworld
Creating service 'hello2' in namespace 'default':

  0.028s The Route is still working to reflect the latest desired specification.
  0.056s Configuration "hello2" is waiting for a Revision to become ready.
  0.084s ...
  2.145s ...
  2.177s Ingress has not yet been reconciled.
  2.217s Waiting for load balancer to be ready
  2.400s Ready to serve.

Service 'hello2' created to latest revision 'hello2-00001' is available at URL:
http://hello2.default.127.0.0.1.nip.io
➜  ~ kn service update hello2 --traffic @latest=100            
Service 'hello2' updated in namespace 'default'.
No new revision has been created.
```
