### ISSUE TITLE
Proposal: Introduce a "public" top-level package directory for sharing outside

### ISSUE THREAD

**Issue by rhuss** [knative/client#889]
One design goal of `kn` was also to expose a public API to offer common client functionality to other go based applications. We already have some of those API hooks but at various places:

* The client API interfaces at
   - `pkg/serving/v1`
   - `pkg/sources/v1alpha2`
   - `pkg/eventing/v1beta1`
* A testing lib for E2E tests in
   - `lib/test`
* Utilities for parsing kn flags
   - `pkg/kn/flags`

This proposal suggests introducing a top-level package under which all externally shared code is collected.

This could be either the already exposed `lib` or maybe something more explicit like `public`.
Also, a CI test should check for whether any file of this directory is touched and raise some awareness (like an extra label) that a review should check for any backward compatibility issues.

Please add a 👍 for being positive for this change, 👎 if you against it.

**Comment by rhuss** [comment]
ballot is over, all positive. Thanks !

/assign rhuss

**Comment by rhuss** [comment]
@dsimansk I think we can close this issue but use it as an input for the new shared pkg repo structure ?

**Comment by dsimansk** [comment]
@rhuss yep, works for me.

**Comment by rhuss** [comment]
Closing this and track it in #1039
