### ISSUE TITLE
make 'cmd' an stringArray instead of string 

### ISSUE THREAD

**Issue by duglin** [knative/client#890]
Technically, the "command" in a podSpec can be an array of strings, not just a single string. So, it might make sense to support that from `kn`.  I've needed to use this before and had to split things across 'cmd' and 'args', which gave the same net result but wasn't what I wanted to do when trying to get my podSpec to align with the `kn` cmd line.

**Comment by rhuss** [comment]
I agree, we should just make `--cmd` a string array and allow multiple calls to this option.

@itsmurugappan do you still plan to work on it or should we move back the issue to the pool ?

**Comment by itsmurugappan** [comment]
I can work on it.

**Comment by rhuss** [comment]
great, thanks !
