### ISSUE TITLE
Has Knative alreay had open-source version Web Dashboard to manipulate ksvcs/revisions? Just like k8s dashboard for k8s cluster

### ISSUE THREAD

**Issue by pengcheng-cs** [knative/client#891]
Has Knative alreay had open-source version Web Dashboard to manipulate ksvcs/revisions? Just like k8s dashboard for k8s cluster.

If not, could I make one based on knative client? 

This requirement is from my work at company, we introduced knative@0.8 to our k8s clusters years ago, but that time we were modifing yaml templates to manipulate ksvcs. Now we have upgraded to knative@0.14 and want a more general way.

Want suggestions about making a Knative Web Dashboard based on knative client, thanks

**Comment by rhuss** [comment]
There is no such a WebUI coming from Knative directly, but you have the following options so far:

* OpenShift Serverless (Knative installed in OpenShift) has a nice UI but runs only on OpenShift. This UX has won an [award](https://designawards.core77.com/Interaction/95599/OpenShift-Topology-View) lately.
* There  is also a  [Visual Code plugin](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-knative) under-way which also interacts with Knative and runs `kn` under the hood currently (but there is still some way to go). 

These are that I'm aware of, but there might be more.
