### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ahmetb** [knative/client#9]
1. `git clone https://github.com/knative/client.git knative-client` (currently at 38932b1)
2. `cd knative-client`
3. `go install ./cmd/kn`
4. errors out with output:

```
...
...
go: downloading github.com/google/btree v0.0.0-20180813153112-4030bb1f1f0c
go: downloading github.com/emicklei/go-restful v2.8.0+incompatible
go: downloading github.com/go-openapi/spec v0.18.0
go: verifying github.com/knative/serving@v0.3.0: checksum mismatch
	downloaded: h1:kALSwD+P5GLdRj2mtZ2W4ZRRD//Q7nKjLqCPSpihkTY=
	go.sum:     h1:O8llkx4VL7C7AZm5wCxcQ9abz8yq02I62ZU++EAwBHk=
```

similarly `go clean -modcache` doesn't work (fails w/ the same error).

Is this only me (go1.11.4)?

**Comment by sixolet** [comment]
I made those files with 1.11.2, which it looks like has a bug when modules include symlinks. I'll go get 1.11.4 and see if I can fix it.

**Comment by sixolet** [comment]
This should be fixed now.
