### ISSUE TITLE
Add "-o url" to "kn service describe" and "kn revision describe"

### ISSUE THREAD

**Issue by rhuss** [knative/client#907]
### Feature request

Having a dedicated command to only show the  URL is very helpful in a scripted context so that one does not have to know the specifics of the Service schema to extract the URL via a jsonpath.

### Use case

Retrieve the URL to process it further in a script.

### UI Example

```
url=$(kn service describe myservice -o url)
```

**Comment by navidshaikh** [comment]
@rhuss : any particular in mind for `revision describe -o yaml` ? ( like showing custom-URL if the revision has a tag )

**Comment by rhuss** [comment]
maybe something like that. I haven't really thought about this but my its better to have a `kn service describe --tag mytag -o url` ? I just want to see the URL for a specific routed revision.
