### ISSUE TITLE
Add Port Name to kn service create options

### ISSUE THREAD

**Issue by itsmurugappan** [knative/client#912]
### Feature request

Add port name to kn service create options.

For deploying a grpc server as a ksvc,  port name should be "h2c". Currently kn cli doesnt support port name.

Example of grpc server as ksvc https://knative.dev/docs/serving/samples/grpc-ping-go/

**Comment by rhuss** [comment]
Sounds like an important use case. I suggest we add this to the `--port` option when creating a service and allows a prefix like `h2c:`  for specifying the port name:

```
kn service create mysvc --image myimage --port h2c:8080
```
