### ISSUE TITLE
add support for --context flag like kubectl

### ISSUE THREAD

**Issue by duglin** [knative/client#925]
### Feature request

`kubectl` has support for a `--context` flag that allows you to specify which cluster in the Kubernetes config file to use. W/o this it makes it harder to switch between kube cluster easily.
For example, I often have Makefiles that point to different clusters and I can just add the `--context` flag to each `kubectl` command w/o having to set KUBECONFIG or use some other tool to set my Kube context before running `make` - which might impact other things going on in my env that point to other clusters.

/kind proposal

**Comment by duglin** [comment]
/remove-lifecycle stale

would be a good first issue too I think

/kind good-first-issue

**Comment by rhuss** [comment]
+1, let's check how `kubectl` implements this.

**Comment by maximilien** [comment]
Does `kubectl` assumes a default location for the `KUBECONFIG` file, e.g., `.kube`

**Comment by duglin** [comment]
I believe it's ~/.kube/config

**Comment by rhuss** [comment]
Yes, it what @duglin says but the location can be overridden by setting `KUBECONFIG` env var. The default context itself (server, namespace) is set within the config in the `default:` section. Tools like `kubectx` (or also OpenShift's `oc`) can switch that default context.

With my comment above, I meant that we should check whether we can reuse code from `kubectl` for how it implements the `--context` flag.

**Comment by eletonia** [comment]
Can we use the implementation of `kubectl use-config` to help implement the `--context` flag for kn? 
https://github.com/kubernetes/kubectl/blob/c1df07341a15fb36264a018e130ee397332bdfc0/pkg/cmd/config/use_context.go

**Comment by dsimansk** [comment]
It's done similarly with help of  client-go config loader and `ConfigOverrides` hook, pls see the change on [PR](https://github.com/knative/client/pull/1234/files#diff-10591b341830c6b126e817c7813eecc94eebbb85c5dd97f6fe16e46dd46d0042R172-R178).
