### ISSUE TITLE
Create a common PodFlags for both Service command and ContainerSource command

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/client#935]
The specification of knative Service and eventing ContainerSource include common flags to describe the pod which will be created. I propose to create a common type under `pkg/kn/commands/flags` for these flags.

The specification of knative [Service](https://github.com/knative/serving/blob/master/pkg/apis/serving/v1/revision_types.go#L76) includes a `corev1.PodSpec`, while [ContainerSource](https://github.com/knative/eventing/blob/master/pkg/apis/sources/v1alpha2/container_types.go#L61) includes a `corev1.PodTemplateSpec`.  `corev1.PodTemplateSpec` includes `corev1.PodSpec`. So both Service and ContainerSource commands could accept a dozen of common flags for create command and update command.

In order to provide a unique interface and to leverage the existing code base, I propose to create a common `PodFlags` under `pkg/kn/commands/flags` and move some flags in `pkg/kn/commands/service/configuration_edit_flags.go` there.  Then this `PodFlags` can be used in both Service commands and ContainerSource commands.

I think below attributes in [`ConfigurationEditFlags`](https://github.com/knative/client/blob/master/pkg/kn/commands/service/configuration_edit_flags.go#L35) are common to both Service and ContainerSource.

	Image   uniqueStringArg
	Env     []string
	EnvFrom []string
	Mount   []string
	Volume  []string

	Command string
	Arg     []string

	RequestsFlags, LimitsFlags ResourceFlags // TODO: Flag marked deprecated in release v0.15.0, remove in release v0.18.0
	Resources                  knflags.ResourceOptions
	Scale                      int
	MinScale                   int
	MaxScale                   int
	ConcurrencyTarget          int
	ConcurrencyLimit           int
	ConcurrencyUtilization     int
	AutoscaleWindow            string
	Port                       string
	Labels                     []string
	LabelsService              []string
	LabelsRevision             []string
	NamePrefix                 string
	<del>RevisionName               string</del>
	ServiceAccountName         string
	ImagePullSecrets           string
	Annotations                []string
	ClusterLocal               bool
	User                       int64

	// Preferences about how to do the action.
	<del>LockToDigest         bool</del>
	<del>GenerateRevisionName bool</del>
	<del>ForceCreate          bool</del>

	Filename string

	// Bookkeeping
	<del>flags []string</del>

**Comment by daisy-ycguo** [comment]
@rhuss @navidshaikh let me know your opinion to this proposed changes.

**Comment by navidshaikh** [comment]
+1 for grouping the related flags together.

How about bringing PodFlags in `pkg/kn/flags` ?
Overall, the flag definitions are scattered in client repo: `pkg/kn/flags`, `pkg/kn/commands/flags`, `pkg/kn/commads/`, `pkg/kn/commands/human_readable_flags.go`. We can work on refactoring the flags defined in deeper pkg levels and bring them to `pkg/kn/flags`. This way its consistent for consumption within client and plugins.
Also, there are flags defined for properties like `ResourceOptions` (in `pkg/kn/flags/resources.go`), we could consider encapsulating them in PodFlags, this way the targeted utils like `func (o *ResourceOptions) Validate()` could be useful.
