### ISSUE TITLE
Add cmd option to allow "ls" for list

### ISSUE THREAD

**Issue by csantanapr** [knative/client#939]
### Feature request

I keep hitting an error using `ls` instead of `list` maybe I'm used to using it with other CLI tools like `tkn`

Can we add the option for `ls` but keep also `list` so the commands like `kn service ls` and `kn revision ls` work?

### UI Example
```
kn service ls
kn revision ls
kn trigger ls
```

/kind proposal
/kind good-first-issue

**Comment by danielhelfand** [comment]
Could certainly be done via an alias. Just depends on style guidelines for kn. 

Think it’s definitely a common abbreviation and find it’s nice when using tkn.

**Comment by csantanapr** [comment]
Reading the files under conventions https://github.com/knative/client/tree/master/conventions

It mentions that "list" is required but doesn't say anything to not allowed additional aliases where it makes sense for better UX.

Maybe this issue also should cover a proposal ch age to the conventions that "ls" is an alias to "list"

**Comment by rhuss** [comment]
Thanks for bringing that up @csantanapr  . I think we should generally open a discussion for introducing aliases, as there are other issues, too which ask for adding aliases (e.g. #812).

Personally I totally for aliases if they improve the UX, don't "clash" with a future possible (and different) usage of such an alias and does not clutter the help page with redundant descriptions. I will open a dedicated issues for this.

**Comment by maximilien** [comment]
We should close this and discuss in #812 and #940

**Comment by rhuss** [comment]
agreed, let's followup in #940 ....
