### ISSUE TITLE
Proposal: Add aliases to commands

### ISSUE THREAD

**Issue by rhuss** [knative/client#940]
# Feature request

There has been now two features requests which can be covered by command _aliases_

* Add `ls` as alias for `list` #939 
* Add plural form like e.g.`kn services` (or maybe also `kn ksvc`) #812 

Before tackling these suggestions, let's discuss how we would like to introduce aliases.

My design proposal for adding aliases would be:

* An alias should feel tightly connected to the aliases command
* An alias should not very likely do not cover any future command "slot" for a future feature (if that can be foreseen)
* Aliases should not clutter or dilute the help message (e.g. should not repeat descriptions and listed separately on the in the help message)
* Aliases that fix obvious typos, like the plural form of given commands should possibly not be added to the help message.
* We should not go overboard with alias usage and don't take the introduction of an alias lightly. 
* Alias should be limited to command, no option aliases should be introduced.

wdyt ? The goal of this issue should be to come up with an addition to the CLI convention doc, which describes how aliases should be handled.

**Comment by danielhelfand** [comment]
> Aliases should not clutter or dilute the help message (e.g. should not repeat descriptions and listed separately on the in the help message)

For clarification for the point above, an alias, with the exception of plurals, would still be listed on the help page correct? For instance `ls` for list or `ksvc` for `kn service`.

Other than the baseline acceptance criteria of it's nice to have abbreviations and an alias should `feel tightly connected to the aliases command`, wondering if there's any sort of vetting process to add here? Maybe a vote by maintainers or polling of users in some capacity?

**Comment by rhuss** [comment]
> For clarification for the point above, an alias, with the exception of plurals, would still be listed on the help page correct? For instance `ls` for list or `ksvc` for `kn service`.

I thought about adding as a suffix to an existing help entry like in:

```
kn service --help
Manage Knative services

Available Commands:
  create      Create a service
  delete      Delete services
  describe    Show details of a service
  export      Export a service and its revisions
  list        List services (Alias: "ls")
  update      Update a service

Usage:
  kn service [options]
  kn ksvc [options]

Use "kn <command> --help" for more information about a given command.
Use "kn options" for a list of global command-line options (applies to all commands).
```

Not sure what cobra already comes with for alias help support.

> Other than the baseline acceptance criteria of it's nice to have abbreviations and an alias should feel tightly connected to the aliases command, wondering if there's any sort of vetting process to add here? Maybe a vote by maintainers or polling of users in some capacity?

Good point. We should add kind of a process for how to add aliases, which includes some justifications for that alias (e.g. is shorter, already known from other commands, ...) and we should decide this from within the community, possibly with a poll.

**Comment by danielhelfand** [comment]
Cobra does support adding an alias section for `-h`, such as what `tkn` does:

```
tkn tr -h
Manage taskruns

Usage:
  tkn taskrun [command]

Aliases:
  taskrun, tr, taskruns
```

As far as how to exclude certain aliases (e.g. plurals), I am not sure.

**Comment by maximilien** [comment]
Do we have a list of the initial alias proposal? Perhaps we can keep track of that on a spreadsheet?

If no one has started this I can make a proposal. Let me know.

**Comment by rhuss** [comment]
> If no one has started this I can make a proposal. Let me know.

sorry, I promised to do it but haven't had any chance yet. @maximilien If you would create one that would be awesome !

fyi, I will be on PTO for the next 2 weeks ....

**Comment by navidshaikh** [comment]
Adding aliases should be straightforward once we agree on the set, lets target this for the v0.18 release? Adding to milestone.

**Comment by rhuss** [comment]
Added initial suggestions to https://docs.google.com/spreadsheets/d/1WOVoN2kmqdMAEwBJOL1bj4QwGXICqaOI59Za8DPr2Xo/edit?usp=sharing 

Please review, comment and/or add other suggestions (but please keep in mind that we don't want to go over-board and we should have a good reason for adding a particular alias)

**Comment by rhuss** [comment]
As there are no additional comments, let's settle on this initial set of aliases:


service | ksvc
-- | --
service | services
revision | revisions
route | routes
source | sources
broker | brokers
trigger | triggers
channel | channels
plugin | plugins
<cmd> list | <cmd> ls

**Comment by navidshaikh** [comment]
We've a subscription CRUD PR open, how about adding the following couple of aliases?

command | alias
-- | --
subscription | subscriptions
subscription | sub

**Comment by arghya88** [comment]
I would like to work on this if that's okay.

**Comment by navidshaikh** [comment]
@arghya88 : Awesome! please go ahead and thanks for your contributions!
