### ISSUE TITLE
e2e: Build and use e2e test images from repo source code

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#942]
### Feature request

We've hello world test image source in repo, https://github.com/knative/client/tree/master/test/test_images/helloworld and not being built and referenced in tests. The image used in tests [gcr.io/knative-samples/helloworld-go](https://console.cloud.google.com/gcr/images/knative-samples/GLOBAL/helloworld-go?gcrImageListsize=30) is stale, last updated on Nov 2018.
We should be building and using this helloworld test image during e2e test run.
Recently there was a `h2c` port name PR landed which is also missing e2e tests, we can build this image in CI for tests cc: @itsmurugappan.

### References:
https://github.com/knative/eventing/tree/master/test#test-images

/area e2e
/kind proposal

**Comment by itsmurugappan** [comment]
Yes, we could do like serving, where we initially specify the KO_DOCKER_REPO.
