### ISSUE TITLE
Support Subscription CRUD operations

### ISSUE THREAD

**Issue by rhuss** [knative/client#955]
### Feature request

`Subscriptions` should be supported and manageable like other entities

### Use case

Manage subscriptions in order to connect channels to sinks

### UI Example

```
# Create a subscription to connect a channel with a service
kn subscription create mysubscription --channel mychannel --mysink ksvc:mysvc

# Delete a subscription 
kn subscription delete mysubscription

# List all subscriptions
kn subscription list


# Show details of a subscription
kn subscription describe mysubscription
```

**Comment by maximilien** [comment]
Nice. I like that. Though the name `subscription` is rather long :) In time with aliases `sub` would be a nice shorter name. Cheers.

**Comment by navidshaikh** [comment]
@arghya88 : Welcome! I've a WIP PR #1013 for this, mind looking at some other open issues? thanks! :-)

**Comment by arghya88** [comment]
@navidshaikh okay..I was not aware of it as it was not linked

**Comment by navidshaikh** [comment]
@arghya88 : yup, I'd missed linking that, fixed now ;-) Here is another https://github.com/knative/client/issues/1014 that we'd like to get in the next release, feel free to assign it.

**Comment by abrennan89** [comment]
Added a PR for some docs for ths https://github.com/knative/docs/pull/3306
