### ISSUE TITLE
--mount flag in update command failed with more than one level of directory

### ISSUE THREAD

**Issue by zsxking** [knative/client#961]
### Bug report

When trying to mount a configmap with:
```
$ kn service update heloapp -n app --mount /my/path=cm:test
```
it gives error 
```
Error: giving up after 3 retries: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: invalid value: my.path-1f5d5125: spec.template.spec.volumes[1].name
```

### Expected behavior

It should work and mount the configmap onto `/my/path`

When mounting to folder on root, like `/mypath`, it work:
```
$ kn service update heloapp -n app --mount /mypath=cm:test
Updating Service 'heloapp' in namespace 'app':
...
```

### Steps to reproduce the problem

1. create a configmap called `test`
2. deploy a kn service: `kn service create hello --image gcr.io/cloudrun/hello`
3. use kn service update to mount the configmap to `mypath`: `kn service update hello --mount /my/path=cm:test`

### kn version

```
Version:      v20200728-4c246812
Build Date:   2020-07-28 10:36:25
Git Revision: 4c246812
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.16.1-0.20200715073232-81d40bfc82a6)
* Eventing
  - sources.knative.dev/v1alpha2 (knative-eventing v0.16.1-0.20200715062032-28f9f61e6131)
  - eventing.knative.dev/v1beta1 (knative-eventing v0.16.1-0.20200715062032-28f9f61e6131)
```

### Knative (serving/eventing) version

> 0.13.2

**Comment by navidshaikh** [comment]
The [volume spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#volume-v1-core) requires the volume to be[ DNS_LABEL,](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) which only allows `-` in the names. We are currently replacing all the `/` with `.` (except root `/`).
