### ISSUE TITLE
kn channel list-types

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#979]
### Feature request

List available channel types in cluster which can be used for creating channels.

### Use case
As a user I want to list available channel types in my cluster which can be used to create channels.

### UI Example
```
kn channel list-types
TYPE             GROUP                   VERSION
InMemoryChannel  messaging.knative.dev   v1abeta1
KafkaChannel     messaging.knative.dev   v1alpha1
```

### Implementation notes:
- The implementation could follow `kn source list-types` approach to query CRDs using dynamic client,
  filtered by label `messaging.knative.dev/subscribable=true`.

/kind proposal

**Comment by Kaustubh-pande** [comment]
As per the review comments, change the header fields to NAME & DESCRIPTION
```
TYPE              NAME                                     DESCRIPTION
InMemoryChannel   inmemorychannels.messaging.knative.dev   The events are stored in memory
KafkaChannel      kafkachannels.messaging.knative.dev      The events are stored in a Kafka cluster (must be installed separately)
```
