### ISSUE TITLE
jsonpath should emit json

### ISSUE THREAD

**Issue by duglin** [knative/client#983]
I know this will be a bit controversial but I'm gonna ask it anyway :-)

```
$ kn service describe echo -o jsonpath='{.status}'
```
will yield
```
map[address:map[url:http://echo.default.svc.cluster.local] conditions:[map[lastTransitionTime:2020-08-18T23:16:12Z
message:Revision "echo-kgvcq-8" failed with message: configmap "foo" not found. reason:RevisionFailed status:False
type:ConfigurationsReady] map[lastTransitionTime:2020-08-18T23:16:12Z message:Revision "echo-kgvcq-8" failed with
message: configmap "foo" not found. reason:RevisionFailed status:False type:Ready]
map[lastTransitionTime:2020-08-17T15:36:21Z status:True type:RoutesReady]] latestCreatedRevisionName:echo-kgvcq-8
latestReadyRevisionName:echo-wlrqt-7 observedGeneration:8 traffic:[map[latestRevision:true percent:100
revisionName:echo-wlrqt-7]] url:http://echo-default.kndev.us-south.containers.appdomain.cloud]
```
I believe this output is almost useless :-)

Emitting the golang formatting isn't machine readable and so I question its value. Yes a human can weed thru it, but they could just as easily scan actual json. It also seems really odd to me that an option with "json" in it doesn't produce json.

Proposal:
Either modify -ojsonpath to actually emit json (yes be different from kube!), or add support for a new -o type of thing to return json instead of golang data structures.

**Comment by rhuss** [comment]
I agree with you that the error message is not very useful. However, this should be fixed in https://github.com/kubernetes/cli-runtime as this is the library that we are using for printing out machine readable format

**Comment by rhuss** [comment]
btw for non-errors json should be the output anyway ....

**Comment by duglin** [comment]
the error message isn't really my concern, although yes it's hard to extract from there. My main point was just that the entire chunk of text isn't very helpful and should be in json, whether there an error message embedded in there or not.

**Comment by rhuss** [comment]
I see. However this still needs to be fixed on the kubectl side as the output is as described in https://kubernetes.io/docs/reference/kubectl/jsonpath/

**Comment by rhuss** [comment]
cool, let me check whether we are already leveraging this (i.e. whether we already have the appropriate dependency)

**Comment by rhuss** [comment]
Good point, @knative/client-writers anyone has some time to spend to investigate this issue? (I'm quite loaded these days)

**Comment by dsimansk** [comment]
@rhuss I'd say you've tagged a wrong team here. However, to the question the `jsonpath-as-json` is present in `cli-runtime` from version 1.19.x onwards. We're currently at `1.18.8` per [go.mod](https://github.com/knative/client/blob/master/go.mod#L38).

**Comment by rhuss** [comment]
Ah, I see. So I would wait until we do also an upgrade to 1.19.x

**Comment by rhuss** [comment]
So that we are now on k8s 1.19, have we fixed this issue magically automatically ?

**Comment by dsimansk** [comment]
Yep, it's look all right to me. The `jsonpath` produces json output now. And there's new option `jsonpath-as-json` as well coming from the updated cli-runtime.
```
➜  client git:(multiple-name-support) ✗ kn service describe hello -o jsonpath='{.status}' | jq  
{
  "address": {
    "url": "http://hello.default.svc.cluster.local"
  },
  "conditions": [
    {
      "lastTransitionTime": "2021-03-02T10:11:44Z",
      "message": "Revision \"hello-00006\" failed with message: Unable to fetch image \"docker.io/dsimansk/helloworld:2.0\": failed to resolve image to digest: HEAD https://index.docker.io/v2/dsimansk/helloworld/manifests/2.0: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details).",
      "reason": "RevisionFailed",
      "status": "False",
      "type": "ConfigurationsReady"
    },
    {
      "lastTransitionTime": "2021-03-02T10:11:44Z",
      "message": "Revision \"hello-00006\" failed with message: Unable to fetch image \"docker.io/dsimansk/helloworld:2.0\": failed to resolve image to digest: HEAD https://index.docker.io/v2/dsimansk/helloworld/manifests/2.0: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details).",
      "reason": "RevisionFailed",
      "status": "False",
      "type": "Ready"
    },
    {
      "lastTransitionTime": "2021-02-24T18:32:45Z",
      "status": "True",
      "type": "RoutesReady"
    }
  ],
  "latestCreatedRevisionName": "hello-00006",
  "latestReadyRevisionName": "hello-00005",
  "observedGeneration": 6,
  "traffic": [
    {
      "latestRevision": true,
      "percent": 100,
      "revisionName": "hello-00005"
    }
  ],
  "url": "http://hello.default.example.com"
}

```
