### ISSUE TITLE
KnServingClient::UpdateServiceWithRetry signature references private function type

### ISSUE THREAD

**Issue by ericmillin** [knative/client#988]
### Bug report

I was trying to implement the `KnServingClient` interface, but I could not implement all of it because `UpdateServiceWithRetry` contains a private function type, `serviceUpdateFunc`.
```go
UpdateServiceWithRetry(name string, updateFunc serviceUpdateFunc, nrRetries int) error
```

### Expected behavior

Publicly exposed functions depend on publicly exposed types

### Steps to reproduce the problem

Try to implement `KnServingClient` in a package without access to `serviceUpdateFunc`

### kn version

current

```

```

### Knative (serving/eventing) version

> Nightly
> 0.12.x
> 0.11.x
> 0.10.x
> 0.9.x

**Comment by rhuss** [comment]
@ericmillin could find ! that should be easy to fix and then available for 0.18.0 (or 0.17.1)
