### ISSUE TITLE
Why service list always show "Waiting for load balancer to be ready"?

### ISSUE THREAD

**Issue by sirius1024** [knative/client#993]
/kind question

I've created a new knative serving with kubectl apply -f some.yaml
when I use `kn service list` it always show:
NAME            URL                                    LATEST                AGE   CONDITIONS   READY     REASON
helloworld-go   http://helloworld-go.default.k8s.ren   helloworld-go-7ml4z   16h   1 OK / 3     Unknown   Uninitialized : Waiting for load balancer to be ready

**Comment by navidshaikh** [comment]
looks like the setup issue, can you add more details ? What serving version is installed ? What networking layer is used and if its ready?

docs: https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-serving-component

**Comment by sirius1024** [comment]
@navidshaikh I think it's because of I access kn servings with NodePort and istio. And "Waiting for load balancer to be ready" clearly.
So is this means that I need to access them with ingress to resolve the warning? Nginx-ingress or traefik-on-k8s right?

```sh
kubectl get namespace knative-serving -o 'go-template={{index .metadata.labels "serving.knative.dev/release"}}'
> v0.17.0
```

```sh
kubectl get namespace knative-eventing -o 'go-template={{index .metadata.labels "eventing.knative.dev/release"}}'
> v0.16.0
```
serving and eventing is different version case I upgrade it with https://knative.dev/docs/install/upgrade-installation/
seems that only serving components upgraded in the docs.

**Comment by navidshaikh** [comment]
@sirius1024 : do you still see the issue? feel free to re-open in that case
