### ISSUE TITLE
BYO revision names 

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#994]
There was a recent discussion about a scenario to
  - create a service using kn
  - get service yaml using `kubectl get ksvc foo -oyaml`
  - edit a field/image and apply
fails with; 
```
validation failed: Saw the following changes without a name change (-old +new): spec.template.metadata.name
{*v1.RevisionTemplateSpec}.Spec.PodSpec.Containers[0].Image:
```
This is expected as the revision template name must be updated as well OR leave it blank for the server to fill in.

Per configuration update, kn's default behavior is to generate a revision name for you, in the format `{{.Service}}-{{.Random 5}}-{{.Generation}}`. Notice the generation placeholder there, its helpful to know the generation number by just looking at the revision name. (see `--revision-name` flag for more details using `kn service update  -h`)
~Irrespective of this behavior, if you create the service without BYO revision name using kn or via YAML and fetch using kubectl, one would need to update the revision name for subsequent update. Thus this isn't specific to kn and how its handling the revision names.~

For the original scenario mentioned, its even simpler to update the image using
`kn service update foo --image my.image/name:tag` than going through yaml way.

Besides, I think we could use this discussion to articulate a better workflow for such scenarios, wdyt ?
cc: @jchesterpivotal @evankanderson @duglin 

slack thread: https://knative.slack.com/archives/C93E33SN8/p1597795702039500

**Comment by duglin** [comment]
I wonder if the high-order question here is: should the CLI be assigning a name to the revision w/o the user asking for one?

If the presence of the generation number provides value, should we instead consider having serving include the generation number in the name it generates? Then the CLI doesn't need to do it and I think we'd avoid the scenario that Jacques ran into.  I've seen other people run into this condition too.

**Comment by navidshaikh** [comment]
> should we instead consider having serving include the generation number in the name it generates? 

Yes, planning to open an issue at serving for this.

> I wonder if the high-order question here is: should the CLI be assigning a name to the revision w/o the user asking for one?

Correct. The other difference here is, with kn if user provides same the value for a Configuration field (i.e. no change), it would (unnecessarily) generate a new revision, since kn has generated a *new* revision name for you (which is seen as Configuration update by server).

**Comment by rhuss** [comment]
I always wonder what exactly was the reasoning of introducing BYO revision names as a feature of Knative Serving (i remember that @sixolet explained it to me in the past, but i forgot and can't find the reasoning in the docs)

However, as this is a backend feature I don't see an issue to support it on the client side. The question is of course whether it needs to be the default.

If a user decides to use BYO revision names (by specifying the `name:` field) with yaml fields only, she has the same dilemma that for any update a new name need to be chosen within the yaml file. So in this respect, this is not really a `kn` issue.

However, where we could improve is, that we could update the name in `kn service update -f mysvc.yaml` if we detect a BYO name situation (btw, can this even be detected by the client on a given resource ?). This would also offer a benefit over `kubectl` usage when handling with YAML descriptors.

**Comment by dsimansk** [comment]
In Serving `0.19.0` there's change to more consistent naming, PR https://github.com/knative/serving/pull/9740. It seems to me as another good reason to move away from `kn` generating those names by default.

**Comment by rhuss** [comment]
See #1144 for finally deciding to change the default.
