### ISSUE TITLE
Add CLI support to specify multiple containers

### ISSUE THREAD

**Issue by savitaashture** [knative/client#997]
### Feature request

Knative Serving release [v0.16.0](https://github.com/knative/serving/releases/tag/v0.16.0) has support for multiple containers as an alpha feature.

To propose multi container feature to beta user experience is one of the important aspects to be considered as part of CLI(kn).

The samples has been added as part of [PR](https://github.com/knative/docs/pull/2732)

For more info refer serving [issue](https://github.com/knative/serving/issues/8665) 

### Use case

User will get the flexibility to provide multiple containers information as part of command line tool.
### UI Example

```
```

/kind proposal

**Comment by rhuss** [comment]
Good point, we definitely should add this to `kn`. The tricky part will be how to add this to the UX

* Allow multiple `--image` parameters (but what would be then the main container ?)
* How to add container specific options for the second container, separating them from the ones of the first container (like environment variables).

Or maybe just support a simplified usage of adding a second container, and then delegate to full yaml usage when there are more complex needs ?

@savitaashture are all container related fields possible for the second container, too ?

**Comment by savitaashture** [comment]
@rhuss Yes i agree with you this is bit tricky to support as part of UX

> Allow multiple --image parameters (but what would be then the main container ?)

The main container will be the one where `containerPort` specified by the user

 > How to add container specific options for the second container, separating them from the ones of the first container (like environment variables).

Yes, there are few options which are not supported in sidecar but supported as part of main container (specifically Probes, ContainerPort )


For more info here is the design doc https://docs.google.com/document/d/1XjIRnOGaq9UGllkZgYXQHuTQmhbECNAOk6TT6RNfJMw/edit?ts=5e25d093#heading=h.n8a530nnrb

**Comment by skonto** [comment]
@rhuss @savitaashture one way to do this safely is via a [template file](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-multi-container-group). It should be essentially a copy of what the user would use in a ksvc and that should be validated by the existing Serving logic.

**Comment by rhuss** [comment]
An example could be to used the `--file` option that we already for something like

```
kn service create mysvc --file multicontainers-service.yaml --concurrency-limit ... --scale-max ....
```

**Comment by rhuss** [comment]
After thinking a bit around the issue, in order to stay scalable (wrt the number of options and length of the command-line)  and still being able to provide a decent UX, I think we can't avoid to make multi-container management a multi-step interaction with an intermediate file. 

Some ideas about the UX:

* Using a new `container` command the builds up a list of container specs in a file (option names are just illustrative for now): 

```
kn container create --image foo.bar --env FOO=BAR --target container.yaml
kn container update --image bar.foo --target container.yaml
kn service create mysvc --image yet.another --label bla=blu --additional-containers container.yaml
```

* Leveraging standard out / standard in for allowing a pipe-like mechanism:

```
kn container create --image foo.bar | kn container create --image bar.foo | kn service create --image yet.another --additional-containers -
```

**Comment by rhuss** [comment]
@dprotaso we are going to discuss these two alternatives above in the client WG call. 

btw, I don't think it's a 'good first issue', it touches quite a bit ;-)

**Comment by dprotaso** [comment]
@rhuss mentioned this has an owner - if things have changed feel free to un-assign

/assign @dsimansk

**Comment by rhuss** [comment]
It's still close to the top of the client bucket list, we just don't have a huge velocity right now .. :(

**Comment by evankanderson** [comment]
(This still needs a _design_ before we can start implementation)
