### ISSUE TITLE
when `kn service create` fails, there is no container error message

### ISSUE THREAD

**Issue by ericmillin** [knative/client#998]
### Bug report
When a service create fails, sometimes the revision container error is empty, i.e. `Container failed with: .`. E.g.,
```
❱❱ kn service create example2 --image busybox
Creating service 'example2' in namespace '57aca2f5-aea8':

  0.731s The Configuration is still working to reflect the latest desired specification.
  1.100s The Route is still working to reflect the latest desired specification.
  1.100s Configuration "example2" is waiting for a Revision to become ready.
 19.764s Revision "example2-bpphv-1" failed with message: Container failed with: .
 19.765s Configuration "example2" does not have any ready Revision.
Error: RevisionFailed: Revision "example2-bpphv-1" failed with message: Container failed with: .
Run 'kn --help' for usage
```

`kn service describe example2` has the same problem.

### Expected behavior

Some sort of error message, ideally a helpful one

### Steps to reproduce the problem

Run `kn service create example --image busybox`

### Versions
```
❱❱ kn version
Version:      v20200821-4ea31c44
Build Date:   2020-08-21 10:36:33
Git Revision: 4ea31c44
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.17.0)
* Eventing
  - sources.knative.dev/v1alpha2 (knative-eventing v0.17.0)
  - eventing.knative.dev/v1beta1 (knative-eventing v0.17.0)
```

**Comment by MIBc** [comment]
I think it is not suitable to run an application using busybox image. The knative will test the probe which default port is 8080. I think budybox don't have such application server. You can use helloworld-go image instead.

**Comment by navidshaikh** [comment]
> Some sort of error message, ideally a helpful one

those error messages are produced at server and relayed by client, @ericmillin do you mind opening the issue against serving ?  
(since the client dont cross the boundary of knative APIs and cant inspect the underlying resources for the errors)

**Comment by ericmillin** [comment]
@MIBc I know why it didn't work. The point is the error message is empty.

@navidshaikh I created an issue in serving. Thanks :)
